// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ofdm_tx_process_symbol (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bits_in_TDATA,
        bits_in_TVALID,
        bits_in_TREADY,
        iq_out_TDATA,
        iq_out_TVALID,
        iq_out_TREADY,
        ifft_in_TDATA,
        ifft_in_TVALID,
        ifft_in_TREADY,
        ifft_out_TDATA,
        ifft_out_TVALID,
        ifft_out_TREADY,
        mod_r,
        is_last
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] bits_in_TDATA;
input   bits_in_TVALID;
output   bits_in_TREADY;
output  [47:0] iq_out_TDATA;
output   iq_out_TVALID;
input   iq_out_TREADY;
output  [31:0] ifft_in_TDATA;
output   ifft_in_TVALID;
input   ifft_in_TREADY;
input  [31:0] ifft_out_TDATA;
input   ifft_out_TVALID;
output   ifft_out_TREADY;
input  [0:0] mod_r;
input  [0:0] is_last;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bits_in_TREADY;
reg[47:0] iq_out_TDATA;
reg[31:0] ifft_in_TDATA;
reg ifft_out_TREADY;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state7;
reg   [7:0] freq_buf_M_real_address0;
reg    freq_buf_M_real_ce0;
reg    freq_buf_M_real_we0;
wire   [15:0] freq_buf_M_real_q0;
reg   [7:0] freq_buf_M_imag_address0;
reg    freq_buf_M_imag_ce0;
reg    freq_buf_M_imag_we0;
wire   [15:0] freq_buf_M_imag_q0;
reg   [7:0] time_buf_M_real_address0;
reg    time_buf_M_real_ce0;
reg    time_buf_M_real_we0;
wire   [15:0] time_buf_M_real_q0;
reg   [7:0] time_buf_M_imag_address0;
reg    time_buf_M_imag_ce0;
reg    time_buf_M_imag_we0;
wire   [15:0] time_buf_M_imag_q0;
wire    grp_unpack_bits_fu_92_ap_start;
wire    grp_unpack_bits_fu_92_ap_done;
wire    grp_unpack_bits_fu_92_ap_idle;
wire    grp_unpack_bits_fu_92_ap_ready;
wire    grp_unpack_bits_fu_92_bits_in_TREADY;
wire   [3:0] grp_unpack_bits_fu_92_sym_fifo_din;
wire    grp_unpack_bits_fu_92_sym_fifo_write;
wire    grp_fill_freq_buffer_fu_101_ap_start;
wire    grp_fill_freq_buffer_fu_101_ap_done;
wire    grp_fill_freq_buffer_fu_101_ap_idle;
wire    grp_fill_freq_buffer_fu_101_ap_ready;
wire    grp_fill_freq_buffer_fu_101_sym_fifo_read;
wire   [7:0] grp_fill_freq_buffer_fu_101_freq_buf_M_real_address0;
wire    grp_fill_freq_buffer_fu_101_freq_buf_M_real_ce0;
wire    grp_fill_freq_buffer_fu_101_freq_buf_M_real_we0;
wire   [15:0] grp_fill_freq_buffer_fu_101_freq_buf_M_real_d0;
wire   [7:0] grp_fill_freq_buffer_fu_101_freq_buf_M_imag_address0;
wire    grp_fill_freq_buffer_fu_101_freq_buf_M_imag_ce0;
wire    grp_fill_freq_buffer_fu_101_freq_buf_M_imag_we0;
wire   [15:0] grp_fill_freq_buffer_fu_101_freq_buf_M_imag_d0;
wire    grp_run_ifft_fu_111_ap_start;
wire    grp_run_ifft_fu_111_ap_done;
wire    grp_run_ifft_fu_111_ap_idle;
wire    grp_run_ifft_fu_111_ap_ready;
wire   [7:0] grp_run_ifft_fu_111_in_M_real_address0;
wire    grp_run_ifft_fu_111_in_M_real_ce0;
wire   [7:0] grp_run_ifft_fu_111_in_M_imag_address0;
wire    grp_run_ifft_fu_111_in_M_imag_ce0;
wire   [7:0] grp_run_ifft_fu_111_out_M_real_address0;
wire    grp_run_ifft_fu_111_out_M_real_ce0;
wire    grp_run_ifft_fu_111_out_M_real_we0;
wire   [15:0] grp_run_ifft_fu_111_out_M_real_d0;
wire   [7:0] grp_run_ifft_fu_111_out_M_imag_address0;
wire    grp_run_ifft_fu_111_out_M_imag_ce0;
wire    grp_run_ifft_fu_111_out_M_imag_we0;
wire   [15:0] grp_run_ifft_fu_111_out_M_imag_d0;
wire   [31:0] grp_run_ifft_fu_111_ifft_in_TDATA;
wire    grp_run_ifft_fu_111_ifft_in_TVALID;
wire    grp_run_ifft_fu_111_ifft_in_TREADY;
wire    grp_run_ifft_fu_111_ifft_out_TREADY;
wire    grp_insert_cp_and_send_fu_123_ap_start;
wire    grp_insert_cp_and_send_fu_123_ap_done;
wire    grp_insert_cp_and_send_fu_123_ap_idle;
wire    grp_insert_cp_and_send_fu_123_ap_ready;
wire   [7:0] grp_insert_cp_and_send_fu_123_sym_M_real_address0;
wire    grp_insert_cp_and_send_fu_123_sym_M_real_ce0;
wire   [7:0] grp_insert_cp_and_send_fu_123_sym_M_imag_address0;
wire    grp_insert_cp_and_send_fu_123_sym_M_imag_ce0;
wire   [47:0] grp_insert_cp_and_send_fu_123_iq_out_TDATA;
wire    grp_insert_cp_and_send_fu_123_iq_out_TVALID;
wire    grp_insert_cp_and_send_fu_123_iq_out_TREADY;
reg    grp_unpack_bits_fu_92_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    sym_fifo_full_n;
reg    sym_fifo_write;
reg    grp_fill_freq_buffer_fu_101_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [3:0] sym_fifo_dout;
wire    sym_fifo_empty_n;
reg    sym_fifo_read;
wire    ap_CS_fsm_state4;
reg    grp_run_ifft_fu_111_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [31:0] ifft_in_TDATA_reg;
reg    grp_insert_cp_and_send_fu_123_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [47:0] iq_out_TDATA_reg;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_unpack_bits_fu_92_ap_start_reg = 1'b0;
#0 grp_fill_freq_buffer_fu_101_ap_start_reg = 1'b0;
#0 grp_run_ifft_fu_111_ap_start_reg = 1'b0;
#0 grp_insert_cp_and_send_fu_123_ap_start_reg = 1'b0;
end

ofdm_tx_send_freq_symbol_time_buf_M_real_RAM_1P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
freq_buf_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(freq_buf_M_real_address0),
    .ce0(freq_buf_M_real_ce0),
    .we0(freq_buf_M_real_we0),
    .d0(grp_fill_freq_buffer_fu_101_freq_buf_M_real_d0),
    .q0(freq_buf_M_real_q0)
);

ofdm_tx_send_freq_symbol_time_buf_M_real_RAM_1P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
freq_buf_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(freq_buf_M_imag_address0),
    .ce0(freq_buf_M_imag_ce0),
    .we0(freq_buf_M_imag_we0),
    .d0(grp_fill_freq_buffer_fu_101_freq_buf_M_imag_d0),
    .q0(freq_buf_M_imag_q0)
);

ofdm_tx_send_freq_symbol_time_buf_M_real_RAM_1P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
time_buf_M_real_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(time_buf_M_real_address0),
    .ce0(time_buf_M_real_ce0),
    .we0(time_buf_M_real_we0),
    .d0(grp_run_ifft_fu_111_out_M_real_d0),
    .q0(time_buf_M_real_q0)
);

ofdm_tx_send_freq_symbol_time_buf_M_real_RAM_1P_BRAM_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
time_buf_M_imag_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(time_buf_M_imag_address0),
    .ce0(time_buf_M_imag_ce0),
    .we0(time_buf_M_imag_we0),
    .d0(grp_run_ifft_fu_111_out_M_imag_d0),
    .q0(time_buf_M_imag_q0)
);

ofdm_tx_unpack_bits grp_unpack_bits_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_unpack_bits_fu_92_ap_start),
    .ap_done(grp_unpack_bits_fu_92_ap_done),
    .ap_idle(grp_unpack_bits_fu_92_ap_idle),
    .ap_ready(grp_unpack_bits_fu_92_ap_ready),
    .bits_in_TDATA(bits_in_TDATA),
    .bits_in_TVALID(bits_in_TVALID),
    .bits_in_TREADY(grp_unpack_bits_fu_92_bits_in_TREADY),
    .sym_fifo_din(grp_unpack_bits_fu_92_sym_fifo_din),
    .sym_fifo_full_n(sym_fifo_full_n),
    .sym_fifo_write(grp_unpack_bits_fu_92_sym_fifo_write),
    .mod_r(mod_r)
);

ofdm_tx_fill_freq_buffer grp_fill_freq_buffer_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fill_freq_buffer_fu_101_ap_start),
    .ap_done(grp_fill_freq_buffer_fu_101_ap_done),
    .ap_idle(grp_fill_freq_buffer_fu_101_ap_idle),
    .ap_ready(grp_fill_freq_buffer_fu_101_ap_ready),
    .sym_fifo_dout(sym_fifo_dout),
    .sym_fifo_empty_n(sym_fifo_empty_n),
    .sym_fifo_read(grp_fill_freq_buffer_fu_101_sym_fifo_read),
    .freq_buf_M_real_address0(grp_fill_freq_buffer_fu_101_freq_buf_M_real_address0),
    .freq_buf_M_real_ce0(grp_fill_freq_buffer_fu_101_freq_buf_M_real_ce0),
    .freq_buf_M_real_we0(grp_fill_freq_buffer_fu_101_freq_buf_M_real_we0),
    .freq_buf_M_real_d0(grp_fill_freq_buffer_fu_101_freq_buf_M_real_d0),
    .freq_buf_M_imag_address0(grp_fill_freq_buffer_fu_101_freq_buf_M_imag_address0),
    .freq_buf_M_imag_ce0(grp_fill_freq_buffer_fu_101_freq_buf_M_imag_ce0),
    .freq_buf_M_imag_we0(grp_fill_freq_buffer_fu_101_freq_buf_M_imag_we0),
    .freq_buf_M_imag_d0(grp_fill_freq_buffer_fu_101_freq_buf_M_imag_d0),
    .mod_r(mod_r)
);

ofdm_tx_run_ifft grp_run_ifft_fu_111(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_ifft_fu_111_ap_start),
    .ap_done(grp_run_ifft_fu_111_ap_done),
    .ap_idle(grp_run_ifft_fu_111_ap_idle),
    .ap_ready(grp_run_ifft_fu_111_ap_ready),
    .in_M_real_address0(grp_run_ifft_fu_111_in_M_real_address0),
    .in_M_real_ce0(grp_run_ifft_fu_111_in_M_real_ce0),
    .in_M_real_q0(freq_buf_M_real_q0),
    .in_M_imag_address0(grp_run_ifft_fu_111_in_M_imag_address0),
    .in_M_imag_ce0(grp_run_ifft_fu_111_in_M_imag_ce0),
    .in_M_imag_q0(freq_buf_M_imag_q0),
    .out_M_real_address0(grp_run_ifft_fu_111_out_M_real_address0),
    .out_M_real_ce0(grp_run_ifft_fu_111_out_M_real_ce0),
    .out_M_real_we0(grp_run_ifft_fu_111_out_M_real_we0),
    .out_M_real_d0(grp_run_ifft_fu_111_out_M_real_d0),
    .out_M_imag_address0(grp_run_ifft_fu_111_out_M_imag_address0),
    .out_M_imag_ce0(grp_run_ifft_fu_111_out_M_imag_ce0),
    .out_M_imag_we0(grp_run_ifft_fu_111_out_M_imag_we0),
    .out_M_imag_d0(grp_run_ifft_fu_111_out_M_imag_d0),
    .ifft_in_TDATA(grp_run_ifft_fu_111_ifft_in_TDATA),
    .ifft_in_TVALID(grp_run_ifft_fu_111_ifft_in_TVALID),
    .ifft_in_TREADY(grp_run_ifft_fu_111_ifft_in_TREADY),
    .ifft_out_TDATA(ifft_out_TDATA),
    .ifft_out_TVALID(ifft_out_TVALID),
    .ifft_out_TREADY(grp_run_ifft_fu_111_ifft_out_TREADY)
);

ofdm_tx_insert_cp_and_send grp_insert_cp_and_send_fu_123(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_insert_cp_and_send_fu_123_ap_start),
    .ap_done(grp_insert_cp_and_send_fu_123_ap_done),
    .ap_idle(grp_insert_cp_and_send_fu_123_ap_idle),
    .ap_ready(grp_insert_cp_and_send_fu_123_ap_ready),
    .sym_M_real_address0(grp_insert_cp_and_send_fu_123_sym_M_real_address0),
    .sym_M_real_ce0(grp_insert_cp_and_send_fu_123_sym_M_real_ce0),
    .sym_M_real_q0(time_buf_M_real_q0),
    .sym_M_imag_address0(grp_insert_cp_and_send_fu_123_sym_M_imag_address0),
    .sym_M_imag_ce0(grp_insert_cp_and_send_fu_123_sym_M_imag_ce0),
    .sym_M_imag_q0(time_buf_M_imag_q0),
    .iq_out_TDATA(grp_insert_cp_and_send_fu_123_iq_out_TDATA),
    .iq_out_TVALID(grp_insert_cp_and_send_fu_123_iq_out_TVALID),
    .iq_out_TREADY(grp_insert_cp_and_send_fu_123_iq_out_TREADY),
    .is_last(is_last)
);

ofdm_tx_fifo_w4_d200_S sym_fifo_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_unpack_bits_fu_92_sym_fifo_din),
    .if_full_n(sym_fifo_full_n),
    .if_write(sym_fifo_write),
    .if_dout(sym_fifo_dout),
    .if_empty_n(sym_fifo_empty_n),
    .if_read(sym_fifo_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fill_freq_buffer_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fill_freq_buffer_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_fill_freq_buffer_fu_101_ap_ready == 1'b1)) begin
            grp_fill_freq_buffer_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_insert_cp_and_send_fu_123_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_insert_cp_and_send_fu_123_ap_start_reg <= 1'b1;
        end else if ((grp_insert_cp_and_send_fu_123_ap_ready == 1'b1)) begin
            grp_insert_cp_and_send_fu_123_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_ifft_fu_111_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_run_ifft_fu_111_ap_start_reg <= 1'b1;
        end else if ((grp_run_ifft_fu_111_ap_ready == 1'b1)) begin
            grp_run_ifft_fu_111_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_unpack_bits_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_unpack_bits_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_unpack_bits_fu_92_ap_ready == 1'b1)) begin
            grp_unpack_bits_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_run_ifft_fu_111_ifft_in_TVALID == 1'b1))) begin
        ifft_in_TDATA_reg <= grp_run_ifft_fu_111_ifft_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_insert_cp_and_send_fu_123_iq_out_TVALID == 1'b1))) begin
        iq_out_TDATA_reg <= grp_insert_cp_and_send_fu_123_iq_out_TDATA;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_unpack_bits_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fill_freq_buffer_fu_101_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_run_ifft_fu_111_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_insert_cp_and_send_fu_123_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state8) & (grp_insert_cp_and_send_fu_123_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_insert_cp_and_send_fu_123_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bits_in_TREADY = grp_unpack_bits_fu_92_bits_in_TREADY;
    end else begin
        bits_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq_buf_M_imag_address0 = grp_run_ifft_fu_111_in_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq_buf_M_imag_address0 = grp_fill_freq_buffer_fu_101_freq_buf_M_imag_address0;
    end else begin
        freq_buf_M_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq_buf_M_imag_ce0 = grp_run_ifft_fu_111_in_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq_buf_M_imag_ce0 = grp_fill_freq_buffer_fu_101_freq_buf_M_imag_ce0;
    end else begin
        freq_buf_M_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        freq_buf_M_imag_we0 = grp_fill_freq_buffer_fu_101_freq_buf_M_imag_we0;
    end else begin
        freq_buf_M_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq_buf_M_real_address0 = grp_run_ifft_fu_111_in_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq_buf_M_real_address0 = grp_fill_freq_buffer_fu_101_freq_buf_M_real_address0;
    end else begin
        freq_buf_M_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        freq_buf_M_real_ce0 = grp_run_ifft_fu_111_in_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        freq_buf_M_real_ce0 = grp_fill_freq_buffer_fu_101_freq_buf_M_real_ce0;
    end else begin
        freq_buf_M_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        freq_buf_M_real_we0 = grp_fill_freq_buffer_fu_101_freq_buf_M_real_we0;
    end else begin
        freq_buf_M_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_run_ifft_fu_111_ifft_in_TVALID == 1'b1))) begin
        ifft_in_TDATA = grp_run_ifft_fu_111_ifft_in_TDATA;
    end else begin
        ifft_in_TDATA = ifft_in_TDATA_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ifft_out_TREADY = grp_run_ifft_fu_111_ifft_out_TREADY;
    end else begin
        ifft_out_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_insert_cp_and_send_fu_123_iq_out_TVALID == 1'b1))) begin
        iq_out_TDATA = grp_insert_cp_and_send_fu_123_iq_out_TDATA;
    end else begin
        iq_out_TDATA = iq_out_TDATA_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sym_fifo_read = grp_fill_freq_buffer_fu_101_sym_fifo_read;
    end else begin
        sym_fifo_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        sym_fifo_write = grp_unpack_bits_fu_92_sym_fifo_write;
    end else begin
        sym_fifo_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        time_buf_M_imag_address0 = grp_insert_cp_and_send_fu_123_sym_M_imag_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        time_buf_M_imag_address0 = grp_run_ifft_fu_111_out_M_imag_address0;
    end else begin
        time_buf_M_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        time_buf_M_imag_ce0 = grp_insert_cp_and_send_fu_123_sym_M_imag_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        time_buf_M_imag_ce0 = grp_run_ifft_fu_111_out_M_imag_ce0;
    end else begin
        time_buf_M_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        time_buf_M_imag_we0 = grp_run_ifft_fu_111_out_M_imag_we0;
    end else begin
        time_buf_M_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        time_buf_M_real_address0 = grp_insert_cp_and_send_fu_123_sym_M_real_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        time_buf_M_real_address0 = grp_run_ifft_fu_111_out_M_real_address0;
    end else begin
        time_buf_M_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        time_buf_M_real_ce0 = grp_insert_cp_and_send_fu_123_sym_M_real_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        time_buf_M_real_ce0 = grp_run_ifft_fu_111_out_M_real_ce0;
    end else begin
        time_buf_M_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        time_buf_M_real_we0 = grp_run_ifft_fu_111_out_M_real_we0;
    end else begin
        time_buf_M_real_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_unpack_bits_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_fill_freq_buffer_fu_101_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_run_ifft_fu_111_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_insert_cp_and_send_fu_123_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign grp_fill_freq_buffer_fu_101_ap_start = grp_fill_freq_buffer_fu_101_ap_start_reg;

assign grp_insert_cp_and_send_fu_123_ap_start = grp_insert_cp_and_send_fu_123_ap_start_reg;

assign grp_insert_cp_and_send_fu_123_iq_out_TREADY = (iq_out_TREADY & ap_CS_fsm_state8);

assign grp_run_ifft_fu_111_ap_start = grp_run_ifft_fu_111_ap_start_reg;

assign grp_run_ifft_fu_111_ifft_in_TREADY = (ifft_in_TREADY & ap_CS_fsm_state6);

assign grp_unpack_bits_fu_92_ap_start = grp_unpack_bits_fu_92_ap_start_reg;

assign ifft_in_TVALID = grp_run_ifft_fu_111_ifft_in_TVALID;

assign iq_out_TVALID = grp_insert_cp_and_send_fu_123_iq_out_TVALID;

endmodule //ofdm_tx_process_symbol
