// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ofdm_tx_fft_fft_cfg_s (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        xn_dout,
        xn_empty_n,
        xn_read,
        xk_din,
        xk_full_n,
        xk_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [31:0] xn_dout;
input   xn_empty_n;
output   xn_read;
output  [31:0] xk_din;
input   xk_full_n;
output   xk_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_start;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_start_full_n;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_done;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_continue;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_idle;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_ready;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_start_out;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_start_write;
wire   [15:0] fft_fft_cfg_Block_newFuncRoot_proc_U0_config_ch_data_V_i_din;
wire    fft_fft_cfg_Block_newFuncRoot_proc_U0_config_ch_data_V_i_write;
wire    fft_syn_fft_cfg_U0_ap_start;
wire    fft_syn_fft_cfg_U0_ap_done;
wire    fft_syn_fft_cfg_U0_ap_idle;
wire    fft_syn_fft_cfg_U0_ap_ready;
wire    fft_syn_fft_cfg_U0_ap_continue;
wire    fft_syn_fft_cfg_U0_xn_read;
wire   [31:0] fft_syn_fft_cfg_U0_xk_din;
wire    fft_syn_fft_cfg_U0_xk_write;
wire   [7:0] fft_syn_fft_cfg_U0_status_data_V_din;
wire    fft_syn_fft_cfg_U0_status_data_V_write;
wire    fft_syn_fft_cfg_U0_config_ch_data_V_read;
wire    ap_sync_continue;
wire    fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_start;
wire    fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_done;
wire    fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_continue;
wire    fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_idle;
wire    fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_ready;
wire    fft_fft_cfg_Block_newFuncRoot_proc_1_U0_status_data_V_i_read;
wire    config_ch_data_V_full_n;
wire   [15:0] config_ch_data_V_dout;
wire    config_ch_data_V_empty_n;
wire   [2:0] config_ch_data_V_num_data_valid;
wire   [2:0] config_ch_data_V_fifo_cap;
wire    status_data_V_full_n;
wire   [7:0] status_data_V_dout;
wire    status_data_V_empty_n;
wire   [2:0] status_data_V_num_data_valid;
wire   [2:0] status_data_V_fifo_cap;
reg    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_fft_syn_fft_cfg_U0_din;
wire    start_for_fft_syn_fft_cfg_U0_full_n;
wire   [0:0] start_for_fft_syn_fft_cfg_U0_dout;
wire    start_for_fft_syn_fft_cfg_U0_empty_n;
wire   [0:0] start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_din;
wire    start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_full_n;
wire   [0:0] start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_dout;
wire    start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

ofdm_tx_fft_fft_cfg_Block_newFuncRoot_proc fft_fft_cfg_Block_newFuncRoot_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_start),
    .start_full_n(fft_fft_cfg_Block_newFuncRoot_proc_U0_start_full_n),
    .ap_done(fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_done),
    .ap_continue(fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_continue),
    .ap_idle(fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_idle),
    .ap_ready(fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_ready),
    .start_out(fft_fft_cfg_Block_newFuncRoot_proc_U0_start_out),
    .start_write(fft_fft_cfg_Block_newFuncRoot_proc_U0_start_write),
    .config_ch_data_V_i_din(fft_fft_cfg_Block_newFuncRoot_proc_U0_config_ch_data_V_i_din),
    .config_ch_data_V_i_full_n(config_ch_data_V_full_n),
    .config_ch_data_V_i_write(fft_fft_cfg_Block_newFuncRoot_proc_U0_config_ch_data_V_i_write),
    .config_ch_data_V_i_num_data_valid(config_ch_data_V_num_data_valid),
    .config_ch_data_V_i_fifo_cap(config_ch_data_V_fifo_cap)
);

ofdm_tx_fft_syn_fft_cfg_s fft_syn_fft_cfg_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(1'b1),
    .ap_start(fft_syn_fft_cfg_U0_ap_start),
    .ap_done(fft_syn_fft_cfg_U0_ap_done),
    .ap_idle(fft_syn_fft_cfg_U0_ap_idle),
    .ap_ready(fft_syn_fft_cfg_U0_ap_ready),
    .ap_continue(fft_syn_fft_cfg_U0_ap_continue),
    .xn_dout(xn_dout),
    .xn_empty_n(xn_empty_n),
    .xn_read(fft_syn_fft_cfg_U0_xn_read),
    .xk_din(fft_syn_fft_cfg_U0_xk_din),
    .xk_full_n(xk_full_n),
    .xk_write(fft_syn_fft_cfg_U0_xk_write),
    .status_data_V_din(fft_syn_fft_cfg_U0_status_data_V_din),
    .status_data_V_full_n(status_data_V_full_n),
    .status_data_V_write(fft_syn_fft_cfg_U0_status_data_V_write),
    .config_ch_data_V_dout(config_ch_data_V_dout),
    .config_ch_data_V_empty_n(config_ch_data_V_empty_n),
    .config_ch_data_V_read(fft_syn_fft_cfg_U0_config_ch_data_V_read)
);

ofdm_tx_fft_fft_cfg_Block_newFuncRoot_proc_1 fft_fft_cfg_Block_newFuncRoot_proc_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_start),
    .ap_done(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_done),
    .ap_continue(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_continue),
    .ap_idle(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_idle),
    .ap_ready(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_ready),
    .status_data_V_i_dout(status_data_V_dout),
    .status_data_V_i_empty_n(status_data_V_empty_n),
    .status_data_V_i_read(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_status_data_V_i_read),
    .status_data_V_i_num_data_valid(status_data_V_num_data_valid),
    .status_data_V_i_fifo_cap(status_data_V_fifo_cap)
);

ofdm_tx_fifo_w16_d2_S config_ch_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_fft_cfg_Block_newFuncRoot_proc_U0_config_ch_data_V_i_din),
    .if_full_n(config_ch_data_V_full_n),
    .if_write(fft_fft_cfg_Block_newFuncRoot_proc_U0_config_ch_data_V_i_write),
    .if_dout(config_ch_data_V_dout),
    .if_empty_n(config_ch_data_V_empty_n),
    .if_read(fft_syn_fft_cfg_U0_config_ch_data_V_read),
    .if_num_data_valid(config_ch_data_V_num_data_valid),
    .if_fifo_cap(config_ch_data_V_fifo_cap)
);

ofdm_tx_fifo_w8_d2_S status_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_syn_fft_cfg_U0_status_data_V_din),
    .if_full_n(status_data_V_full_n),
    .if_write(fft_syn_fft_cfg_U0_status_data_V_write),
    .if_dout(status_data_V_dout),
    .if_empty_n(status_data_V_empty_n),
    .if_read(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_status_data_V_i_read),
    .if_num_data_valid(status_data_V_num_data_valid),
    .if_fifo_cap(status_data_V_fifo_cap)
);

ofdm_tx_start_for_fft_syn_fft_cfg_U0 start_for_fft_syn_fft_cfg_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_syn_fft_cfg_U0_din),
    .if_full_n(start_for_fft_syn_fft_cfg_U0_full_n),
    .if_write(fft_fft_cfg_Block_newFuncRoot_proc_U0_start_write),
    .if_dout(start_for_fft_syn_fft_cfg_U0_dout),
    .if_empty_n(start_for_fft_syn_fft_cfg_U0_empty_n),
    .if_read(fft_syn_fft_cfg_U0_ap_ready)
);

ofdm_tx_start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0 start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_din),
    .if_full_n(start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_full_n),
    .if_write(fft_fft_cfg_Block_newFuncRoot_proc_U0_start_write),
    .if_dout(start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_dout),
    .if_empty_n(start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_empty_n),
    .if_read(fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_sync_done <= (fft_syn_fft_cfg_U0_ap_done & fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_done & ~ap_sync_continue);
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign ap_done = ap_sync_done;

assign ap_idle = (fft_syn_fft_cfg_U0_ap_idle & fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_idle & fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_idle);

assign ap_ready = fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_ready = fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_ready;

assign fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_continue = ap_sync_continue;

assign fft_fft_cfg_Block_newFuncRoot_proc_1_U0_ap_start = start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_empty_n;

assign fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_continue = 1'b1;

assign fft_fft_cfg_Block_newFuncRoot_proc_U0_ap_start = real_start;

assign fft_fft_cfg_Block_newFuncRoot_proc_U0_start_full_n = (start_for_fft_syn_fft_cfg_U0_full_n & start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_full_n);

assign fft_syn_fft_cfg_U0_ap_continue = ap_sync_continue;

assign fft_syn_fft_cfg_U0_ap_start = start_for_fft_syn_fft_cfg_U0_empty_n;

assign internal_ap_ready = ap_sync_ready;

assign start_for_fft_fft_cfg_Block_newFuncRoot_proc_1_U0_din = 1'b1;

assign start_for_fft_syn_fft_cfg_U0_din = 1'b1;

assign start_out = real_start;

assign xk_din = fft_syn_fft_cfg_U0_xk_din;

assign xk_write = fft_syn_fft_cfg_U0_xk_write;

assign xn_read = fft_syn_fft_cfg_U0_xn_read;

endmodule //ofdm_tx_fft_fft_cfg_s
