-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity interleaver_interleaver_Pipeline_PERM_Q is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_out_TREADY : IN STD_LOGIC;
    is_rx : IN STD_LOGIC_VECTOR (0 downto 0);
    buf_r_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    buf_r_ce0 : OUT STD_LOGIC;
    buf_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    data_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    data_out_TVALID : OUT STD_LOGIC );
end;


architecture behav of interleaver_interleaver_Pipeline_PERM_Q is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_190 : STD_LOGIC_VECTOR (8 downto 0) := "110010000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv9_4 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_const_lv19_290 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001010010000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_18 : STD_LOGIC_VECTOR (8 downto 0) := "000011000";
    constant ap_const_lv9_19 : STD_LOGIC_VECTOR (8 downto 0) := "000011001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln126_reg_402 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_402_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln115_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal data_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal lshr_ln1_reg_392 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln1_reg_392_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln126_fu_187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_402_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln126_reg_402_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal src_fu_239_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal src_reg_411 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln122_fu_255_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal phi_urem_fu_88 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln114_fu_275_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal phi_mul_fu_92 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    signal add_ln54_1_fu_213_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal out_byte_fu_96 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal out_byte_3_cast_fu_326_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal j_2_fu_100 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal j_1_fu_159_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_j : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal buf_r_ce0_local : STD_LOGIC;
    signal trunc_ln115_1_fu_169_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln115_fu_165_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_219_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln54_fu_207_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln54_fu_229_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_344_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln54_fu_233_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal lshr_ln2_fu_245_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln114_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln114_fu_263_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln119_fu_296_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal bit_fu_305_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal bit_fu_305_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln125_fu_313_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_fu_344_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_344_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_344_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_344_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_344_p10 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_344_p20 : STD_LOGIC_VECTOR (8 downto 0);
    signal bit_fu_305_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component interleaver_bitselect_1ns_8ns_3ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component interleaver_mac_muladd_5ns_4ns_5ns_9_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component interleaver_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    bitselect_1ns_8ns_3ns_1_1_1_U3 : component interleaver_bitselect_1ns_8ns_3ns_1_1_1
    generic map (
        DATAWIDTH => 8,
        ADDRWIDTH => 3)
    port map (
        din => buf_r_q0,
        sel => bit_fu_305_p2,
        dout => bit_fu_305_p3);

    mac_muladd_5ns_4ns_5ns_9_4_1_U4 : component interleaver_mac_muladd_5ns_4ns_5ns_9_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 5,
        din1_WIDTH => 4,
        din2_WIDTH => 5,
        dout_WIDTH => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_344_p0,
        din1 => grp_fu_344_p1,
        din2 => grp_fu_344_p2,
        ce => grp_fu_344_ce,
        dout => grp_fu_344_p3);

    flow_control_loop_pipe_sequential_init_U : component interleaver_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    j_2_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln115_fu_153_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_2_fu_100 <= j_1_fu_159_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_2_fu_100 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    out_byte_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln126_reg_402_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1)))) then 
                out_byte_fu_96 <= ap_const_lv7_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln126_reg_402_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                out_byte_fu_96 <= out_byte_3_cast_fu_326_p3;
            end if; 
        end if;
    end process;

    phi_mul_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_mul_fu_92 <= ap_const_lv19_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_mul_fu_92 <= add_ln54_1_fu_213_p2;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    phi_urem_fu_88 <= ap_const_lv9_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    phi_urem_fu_88 <= select_ln114_fu_275_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln126_reg_402 <= icmp_ln126_fu_187_p2;
                icmp_ln126_reg_402_pp0_iter1_reg <= icmp_ln126_reg_402;
                lshr_ln1_reg_392 <= ap_sig_allocacmp_j(8 downto 4);
                lshr_ln1_reg_392_pp0_iter1_reg <= lshr_ln1_reg_392;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln126_reg_402_pp0_iter2_reg <= icmp_ln126_reg_402_pp0_iter1_reg;
                icmp_ln126_reg_402_pp0_iter3_reg <= icmp_ln126_reg_402_pp0_iter2_reg;
                src_reg_411 <= src_fu_239_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln114_fu_263_p2 <= std_logic_vector(unsigned(phi_urem_fu_88) + unsigned(ap_const_lv9_1));
    add_ln54_1_fu_213_p2 <= std_logic_vector(unsigned(phi_mul_fu_92) + unsigned(ap_const_lv19_290));
    add_ln54_fu_233_p2 <= std_logic_vector(unsigned(shl_ln54_fu_207_p2) + unsigned(zext_ln54_fu_229_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter4_assign_proc : process(data_out_TREADY, icmp_ln126_reg_402_pp0_iter3_reg)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((icmp_ln126_reg_402_pp0_iter3_reg = ap_const_lv1_1) and (data_out_TREADY = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln115_fu_153_p2)
    begin
        if (((icmp_ln115_fu_153_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, j_2_fu_100)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_j <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_j <= j_2_fu_100;
        end if; 
    end process;

    bit_fu_305_p2 <= (trunc_ln119_fu_296_p1 xor ap_const_lv3_7);
    buf_r_address0 <= zext_ln122_fu_255_p1(7 - 1 downto 0);
    buf_r_ce0 <= buf_r_ce0_local;

    buf_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            buf_r_ce0_local <= ap_const_logic_1;
        else 
            buf_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    data_out_TDATA <= (out_byte_fu_96 & bit_fu_305_p3);

    data_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, data_out_TREADY, icmp_ln126_reg_402_pp0_iter3_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln126_reg_402_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            data_out_TDATA_blk_n <= data_out_TREADY;
        else 
            data_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter4, icmp_ln126_reg_402_pp0_iter3_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln126_reg_402_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            data_out_TVALID <= ap_const_logic_1;
        else 
            data_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_344_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_344_ce <= ap_const_logic_1;
        else 
            grp_fu_344_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_344_p0 <= ap_const_lv9_19(5 - 1 downto 0);
    grp_fu_344_p1 <= grp_fu_344_p10(4 - 1 downto 0);
    grp_fu_344_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln115_1_fu_169_p1),9));
    grp_fu_344_p2 <= grp_fu_344_p20(5 - 1 downto 0);
    grp_fu_344_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_reg_392_pp0_iter1_reg),9));
    icmp_ln114_fu_269_p2 <= "1" when (phi_urem_fu_88 = ap_const_lv9_18) else "0";
    icmp_ln115_fu_153_p2 <= "1" when (ap_sig_allocacmp_j = ap_const_lv9_190) else "0";
    icmp_ln126_fu_187_p2 <= "1" when (trunc_ln115_fu_165_p1 = ap_const_lv3_7) else "0";
    j_1_fu_159_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j) + unsigned(ap_const_lv9_1));
    lshr_ln2_fu_245_p4 <= src_fu_239_p3(8 downto 3);
    out_byte_3_cast_fu_326_p3 <= (trunc_ln125_fu_313_p1 & bit_fu_305_p3);
    select_ln114_fu_275_p3 <= 
        ap_const_lv9_0 when (icmp_ln114_fu_269_p2(0) = '1') else 
        add_ln114_fu_263_p2;
    shl_ln54_fu_207_p2 <= std_logic_vector(shift_left(unsigned(phi_urem_fu_88),to_integer(unsigned('0' & ap_const_lv9_4(9-1 downto 0)))));
    src_fu_239_p3 <= 
        grp_fu_344_p3 when (is_rx(0) = '1') else 
        add_ln54_fu_233_p2;
    tmp_fu_219_p4 <= phi_mul_fu_92(18 downto 14);
    trunc_ln115_1_fu_169_p1 <= ap_sig_allocacmp_j(4 - 1 downto 0);
    trunc_ln115_fu_165_p1 <= ap_sig_allocacmp_j(3 - 1 downto 0);
    trunc_ln119_fu_296_p1 <= src_reg_411(3 - 1 downto 0);
    trunc_ln125_fu_313_p1 <= out_byte_fu_96(6 - 1 downto 0);
    zext_ln122_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_245_p4),64));
    zext_ln54_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_219_p4),9));
end behav;
