// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cfo_correct_cfo_correct_Pipeline_CORRECT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        iq_in_TVALID,
        iq_out_TREADY,
        iq_out_TDATA,
        iq_out_TVALID,
        iq_in_TDATA,
        iq_in_TREADY,
        sext_ln148
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   iq_in_TVALID;
input   iq_out_TREADY;
output  [47:0] iq_out_TDATA;
output   iq_out_TVALID;
input  [47:0] iq_in_TDATA;
output   iq_in_TREADY;
input  [25:0] sext_ln148;

reg ap_idle;
reg iq_out_TVALID;
reg iq_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln152_fu_195_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] SIN_LUT_address0;
wire   [14:0] SIN_LUT_q0;
wire   [7:0] SIN_LUT_address1;
wire   [14:0] SIN_LUT_q1;
reg    iq_out_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    iq_in_TDATA_blk_n;
reg   [15:0] cos_p_3_reg_130;
reg   [15:0] sin_p_3_reg_144;
wire  signed [31:0] sext_ln148_cast_fu_172_p1;
reg  signed [31:0] sext_ln148_cast_reg_385;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [0:0] icmp_ln152_reg_390;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln152_reg_390_pp0_iter1_reg;
reg   [1:0] quadrant_reg_394;
wire  signed [30:0] sext_ln168_fu_287_p1;
wire  signed [30:0] sext_ln168_1_fu_291_p1;
wire  signed [30:0] sext_ln168_2_fu_295_p1;
wire   [30:0] mul_ln168_1_fu_303_p2;
reg   [30:0] mul_ln168_1_reg_424;
reg  signed [30:0] mul_ln168_1_reg_424_pp0_iter4_reg;
wire   [30:0] mul_ln169_1_fu_309_p2;
reg   [30:0] mul_ln169_1_reg_429;
reg  signed [30:0] mul_ln169_1_reg_429_pp0_iter4_reg;
reg   [0:0] tmp_reg_434;
reg   [0:0] tmp_reg_434_pp0_iter4_reg;
reg   [0:0] tmp_reg_434_pp0_iter5_reg;
wire   [15:0] zext_ln110_1_fu_261_p1;
wire   [15:0] ap_phi_reg_pp0_iter2_cos_p_3_reg_130;
wire   [15:0] grp_fu_165_p2;
wire   [15:0] grp_fu_158_p2;
wire   [15:0] zext_ln111_1_fu_268_p1;
wire   [15:0] ap_phi_reg_pp0_iter2_sin_p_3_reg_144;
wire   [63:0] zext_ln110_fu_230_p1;
wire   [63:0] zext_ln111_fu_241_p1;
reg   [16:0] n_fu_78;
wire   [16:0] n_3_fu_189_p2;
wire    ap_loop_init;
reg   [16:0] ap_sig_allocacmp_n_2;
wire    ap_block_pp0_stage0;
reg   [31:0] phase_acc_fu_82;
wire   [31:0] phase_acc_3_fu_209_p2;
reg    ap_block_pp0_stage0_01001_grp1;
reg    SIN_LUT_ce1_local;
reg    SIN_LUT_ce0_local;
wire   [7:0] addr_fu_222_p3;
wire   [7:0] xor_ln111_fu_235_p2;
wire   [15:0] s_i_fu_275_p1;
wire   [15:0] s_q_fu_279_p3;
wire  signed [15:0] mul_ln168_1_fu_303_p0;
wire  signed [15:0] mul_ln168_1_fu_303_p1;
wire  signed [30:0] sext_ln168_3_fu_299_p1;
wire  signed [15:0] mul_ln169_1_fu_309_p0;
wire  signed [15:0] mul_ln169_1_fu_309_p1;
wire  signed [30:0] grp_fu_355_p3;
wire  signed [30:0] grp_fu_363_p3;
wire   [15:0] trunc_ln_fu_332_p4;
wire   [15:0] out_i_fu_323_p4;
wire   [32:0] or_ln_fu_341_p4;
wire  signed [15:0] grp_fu_355_p0;
wire  signed [15:0] grp_fu_355_p1;
wire  signed [15:0] grp_fu_363_p0;
wire  signed [15:0] grp_fu_363_p1;
reg    grp_fu_355_ce;
reg    grp_fu_363_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 n_fu_78 = 17'd0;
#0 phase_acc_fu_82 = 32'd0;
#0 ap_done_reg = 1'b0;
end

cfo_correct_cfo_correct_Pipeline_CORRECT_SIN_LUT_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
SIN_LUT_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(SIN_LUT_address0),
    .ce0(SIN_LUT_ce0_local),
    .q0(SIN_LUT_q0),
    .address1(SIN_LUT_address1),
    .ce1(SIN_LUT_ce1_local),
    .q1(SIN_LUT_q1)
);

cfo_correct_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U1(
    .din0(mul_ln168_1_fu_303_p0),
    .din1(mul_ln168_1_fu_303_p1),
    .dout(mul_ln168_1_fu_303_p2)
);

cfo_correct_mul_16s_16s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_16s_16s_31_1_1_U2(
    .din0(mul_ln169_1_fu_309_p0),
    .din1(mul_ln169_1_fu_309_p1),
    .dout(mul_ln169_1_fu_309_p2)
);

cfo_correct_mac_muladd_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_16s_31s_31_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_355_p0),
    .din1(grp_fu_355_p1),
    .din2(mul_ln168_1_reg_424_pp0_iter4_reg),
    .ce(grp_fu_355_ce),
    .dout(grp_fu_355_p3)
);

cfo_correct_mac_mulsub_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_mulsub_16s_16s_31s_31_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_363_p0),
    .din1(grp_fu_363_p1),
    .din2(mul_ln169_1_reg_429_pp0_iter4_reg),
    .ce(grp_fu_363_ce),
    .dout(grp_fu_363_p3)
);

cfo_correct_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((quadrant_reg_394 == 2'd0)) begin
            cos_p_3_reg_130 <= zext_ln111_1_fu_268_p1;
        end else if ((quadrant_reg_394 == 2'd1)) begin
            cos_p_3_reg_130 <= grp_fu_158_p2;
        end else if ((quadrant_reg_394 == 2'd2)) begin
            cos_p_3_reg_130 <= grp_fu_165_p2;
        end else if ((quadrant_reg_394 == 2'd3)) begin
            cos_p_3_reg_130 <= zext_ln110_1_fu_261_p1;
        end else if (~(icmp_ln152_reg_390_pp0_iter1_reg == 1'd1)) begin
            cos_p_3_reg_130 <= ap_phi_reg_pp0_iter2_cos_p_3_reg_130;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            n_fu_78 <= n_3_fu_189_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_78 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phase_acc_fu_82 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            phase_acc_fu_82 <= phase_acc_3_fu_209_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((quadrant_reg_394 == 2'd0)) begin
            sin_p_3_reg_144 <= zext_ln110_1_fu_261_p1;
        end else if ((quadrant_reg_394 == 2'd1)) begin
            sin_p_3_reg_144 <= zext_ln111_1_fu_268_p1;
        end else if ((quadrant_reg_394 == 2'd2)) begin
            sin_p_3_reg_144 <= grp_fu_158_p2;
        end else if ((quadrant_reg_394 == 2'd3)) begin
            sin_p_3_reg_144 <= grp_fu_165_p2;
        end else if (~(icmp_ln152_reg_390_pp0_iter1_reg == 1'd1)) begin
            sin_p_3_reg_144 <= ap_phi_reg_pp0_iter2_sin_p_3_reg_144;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln152_reg_390 <= icmp_ln152_fu_195_p2;
        icmp_ln152_reg_390_pp0_iter1_reg <= icmp_ln152_reg_390;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        mul_ln168_1_reg_424 <= mul_ln168_1_fu_303_p2;
        mul_ln168_1_reg_424_pp0_iter4_reg <= mul_ln168_1_reg_424;
        mul_ln169_1_reg_429 <= mul_ln169_1_fu_309_p2;
        mul_ln169_1_reg_429_pp0_iter4_reg <= mul_ln169_1_reg_429;
        tmp_reg_434 <= iq_in_TDATA[48'd32];
        tmp_reg_434_pp0_iter4_reg <= tmp_reg_434;
        tmp_reg_434_pp0_iter5_reg <= tmp_reg_434_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quadrant_reg_394 <= {{phase_acc_3_fu_209_p2[31:30]}};
        sext_ln148_cast_reg_385 <= sext_ln148_cast_fu_172_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        SIN_LUT_ce0_local = 1'b1;
    end else begin
        SIN_LUT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        SIN_LUT_ce1_local = 1'b1;
    end else begin
        SIN_LUT_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln152_fu_195_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_2 = 17'd0;
    end else begin
        ap_sig_allocacmp_n_2 = n_fu_78;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_355_ce = 1'b1;
    end else begin
        grp_fu_355_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        grp_fu_363_ce = 1'b1;
    end else begin
        grp_fu_363_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        iq_in_TDATA_blk_n = iq_in_TVALID;
    end else begin
        iq_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        iq_in_TREADY = 1'b1;
    end else begin
        iq_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        iq_out_TDATA_blk_n = iq_out_TREADY;
    end else begin
        iq_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        iq_out_TVALID = 1'b1;
    end else begin
        iq_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign SIN_LUT_address0 = zext_ln111_fu_241_p1;

assign SIN_LUT_address1 = zext_ln110_fu_230_p1;

assign addr_fu_222_p3 = {{phase_acc_3_fu_209_p2[29:22]}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((iq_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((iq_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((iq_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((iq_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((iq_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((iq_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((iq_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((iq_in_TVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter2_cos_p_3_reg_130 = 'bx;

assign ap_phi_reg_pp0_iter2_sin_p_3_reg_144 = 'bx;

assign ap_ready = ap_ready_sig;

assign grp_fu_158_p2 = (16'd0 - zext_ln110_1_fu_261_p1);

assign grp_fu_165_p2 = (16'd0 - zext_ln111_1_fu_268_p1);

assign grp_fu_355_p0 = sext_ln168_fu_287_p1;

assign grp_fu_355_p1 = sext_ln168_1_fu_291_p1;

assign grp_fu_363_p0 = sext_ln168_1_fu_291_p1;

assign grp_fu_363_p1 = sext_ln168_2_fu_295_p1;

assign icmp_ln152_fu_195_p2 = ((ap_sig_allocacmp_n_2 == 17'd74015) ? 1'b1 : 1'b0);

assign iq_out_TDATA = or_ln_fu_341_p4;

assign mul_ln168_1_fu_303_p0 = sext_ln168_2_fu_295_p1;

assign mul_ln168_1_fu_303_p1 = sext_ln168_3_fu_299_p1;

assign mul_ln169_1_fu_309_p0 = sext_ln168_fu_287_p1;

assign mul_ln169_1_fu_309_p1 = sext_ln168_3_fu_299_p1;

assign n_3_fu_189_p2 = (ap_sig_allocacmp_n_2 + 17'd1);

assign or_ln_fu_341_p4 = {{{tmp_reg_434_pp0_iter5_reg}, {trunc_ln_fu_332_p4}}, {out_i_fu_323_p4}};

assign out_i_fu_323_p4 = {{grp_fu_355_p3[30:15]}};

assign phase_acc_3_fu_209_p2 = ($signed(phase_acc_fu_82) - $signed(sext_ln148_cast_reg_385));

assign s_i_fu_275_p1 = iq_in_TDATA[15:0];

assign s_q_fu_279_p3 = {{iq_in_TDATA[31:16]}};

assign sext_ln148_cast_fu_172_p1 = $signed(sext_ln148);

assign sext_ln168_1_fu_291_p1 = $signed(s_i_fu_275_p1);

assign sext_ln168_2_fu_295_p1 = $signed(sin_p_3_reg_144);

assign sext_ln168_3_fu_299_p1 = $signed(s_q_fu_279_p3);

assign sext_ln168_fu_287_p1 = $signed(cos_p_3_reg_130);

assign trunc_ln_fu_332_p4 = {{grp_fu_363_p3[30:15]}};

assign xor_ln111_fu_235_p2 = (8'd255 ^ addr_fu_222_p3);

assign zext_ln110_1_fu_261_p1 = SIN_LUT_q1;

assign zext_ln110_fu_230_p1 = addr_fu_222_p3;

assign zext_ln111_1_fu_268_p1 = SIN_LUT_q0;

assign zext_ln111_fu_241_p1 = xor_ln111_fu_235_p2;

endmodule //cfo_correct_cfo_correct_Pipeline_CORRECT
