// ============================================================
// ofdm_rx.cpp  —  OFDM Receiver (Vitis HLS)
// ============================================================
#include "ofdm_rx.h"
#include <hls_math.h>

// ============================================================
// Internal equalized-channel type
//
// geq_t / cgeq_t hold precomputed G_eq = conj(G)/|G|² values.
//   With scale_sch=0xAA (RX FFT ÷256): G ≈ 1/256, G_eq ≈ 256.
//   ap_fixed<32,10>: range [-512, +512), 22 fractional bits.
//   Holds G_eq ≈ 256 with sufficient precision.
// ============================================================
typedef ap_fixed<32, 10>         geq_t;
typedef std::complex<geq_t>     cgeq_t;

// ============================================================
// SECTION 1: ROM Tables  (must match ofdm_tx.cpp exactly)
// ============================================================

static const int PILOT_IDX[NUM_PILOT_SC] = {50, 75, 100, 154, 179, 204};

static const int DATA_SC_IDX[NUM_DATA_SC] = {
    // Positive half (bins 25–127, pilots at 50, 75, 100 excluded)
    25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
    51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,
    76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,
    101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,
    120,121,122,123,124,125,126,127,
    // Negative half (bins 129–231, pilots at 154, 179, 204 excluded)
    129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,
    148,149,150,151,152,153,
    155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,
    174,175,176,177,178,
    180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,
    199,200,201,202,203,
    205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
    224,225,226,227,228,229,230,231
};

// Zadoff-Chu LUT: Re and Im of zc[DATA_SC_IDX[d]] for d = 0..199
// Generated by gen_zc_lut.py — root u=25, N=256
// ZC_I_LUT[d] = Re(zc[DATA_SC_IDX[d]])
// ZC_Q_LUT[d] = Im(zc[DATA_SC_IDX[d]])
static const sample_t ZC_I_LUT[NUM_DATA_SC] = {
    sample_t(-0.073565), sample_t(-0.170962), sample_t(0.857729), sample_t(-0.595699), sample_t(-0.992480), sample_t(-0.844854), sample_t(-0.923880), sample_t(-0.923880),
    sample_t(0.219101), sample_t(0.788346), sample_t(-0.989177), sample_t(0.970031), sample_t(-0.575808), sample_t(-0.653173), sample_t(0.471397), sample_t(0.881921),
    sample_t(0.870087), sample_t(0.405241), sample_t(-0.740951), sample_t(-0.427555), sample_t(0.893224), sample_t(-0.914210), sample_t(0.555570), sample_t(0.555570),
    sample_t(-0.689541), sample_t(-0.998795), sample_t(-0.903989), sample_t(-0.024541), sample_t(0.992480), sample_t(-0.773010), sample_t(0.634393), sample_t(-0.893224),
    sample_t(0.844854), sample_t(0.595699), sample_t(-0.242980), sample_t(-0.492898), sample_t(-0.170962), sample_t(0.707107), sample_t(0.707107), sample_t(-0.985278),
    sample_t(0.870087), sample_t(-0.970031), sample_t(0.803208), sample_t(0.534998), sample_t(-0.449611), sample_t(-0.773010), sample_t(-0.634393), sample_t(0.122411),
    sample_t(0.999699), sample_t(-0.049068), sample_t(-0.073565), sample_t(0.724247), sample_t(-0.831470), sample_t(-0.831470), sample_t(-0.405241), sample_t(-0.449611),
    sample_t(-0.903989), sample_t(-0.671559), sample_t(0.914210), sample_t(-0.492898), sample_t(0.471397), sample_t(-0.881921), sample_t(0.757209), sample_t(0.817585),
    sample_t(0.242980), sample_t(0.146730), sample_t(0.615232), sample_t(0.975702), sample_t(-0.382683), sample_t(-0.382683), sample_t(0.534998), sample_t(-0.122411),
    sample_t(-0.803208), sample_t(0.985278), sample_t(0.997290), sample_t(0.956940), sample_t(0.290285), sample_t(-0.963776), sample_t(0.359895), sample_t(-0.049068),
    sample_t(0.336890), sample_t(-0.949528), sample_t(0.359895), sample_t(0.980785), sample_t(0.980785), sample_t(0.999699), sample_t(0.653173), sample_t(-0.671559),
    sample_t(-0.336890), sample_t(0.724247), sample_t(-0.615232), sample_t(-0.098017), sample_t(0.995185), sample_t(0.313682), sample_t(-0.219101), sample_t(-0.146730),
    sample_t(0.514103), sample_t(0.963776), sample_t(-0.575808), sample_t(0.000000), sample_t(0.575808), sample_t(-0.963776), sample_t(-0.514103), sample_t(0.146730),
    sample_t(0.219101), sample_t(-0.313682), sample_t(-0.995185), sample_t(0.098017), sample_t(0.615232), sample_t(-0.724247), sample_t(0.336890), sample_t(0.671559),
    sample_t(-0.653173), sample_t(-0.999699), sample_t(-0.980785), sample_t(-0.980785), sample_t(-0.359895), sample_t(0.949528), sample_t(-0.336890), sample_t(0.049068),
    sample_t(-0.359895), sample_t(0.963776), sample_t(-0.290285), sample_t(-0.956940), sample_t(-0.997290), sample_t(-0.514103), sample_t(0.803208), sample_t(0.122411),
    sample_t(-0.534998), sample_t(0.382683), sample_t(0.382683), sample_t(-0.975702), sample_t(-0.615232), sample_t(-0.146730), sample_t(-0.242980), sample_t(-0.817585),
    sample_t(-0.757209), sample_t(0.881921), sample_t(-0.471397), sample_t(0.492898), sample_t(-0.914210), sample_t(0.671559), sample_t(0.903989), sample_t(0.449611),
    sample_t(0.405241), sample_t(0.831470), sample_t(0.831470), sample_t(-0.724247), sample_t(0.073565), sample_t(0.427555), sample_t(-0.999699), sample_t(-0.122411),
    sample_t(0.634393), sample_t(0.773010), sample_t(0.449611), sample_t(-0.534998), sample_t(-0.803208), sample_t(0.970031), sample_t(-0.870087), sample_t(0.985278),
    sample_t(-0.707107), sample_t(-0.707107), sample_t(0.170962), sample_t(0.492898), sample_t(0.242980), sample_t(-0.595699), sample_t(-0.844854), sample_t(0.893224),
    sample_t(-0.634393), sample_t(0.773010), sample_t(-0.992480), sample_t(0.024541), sample_t(0.903989), sample_t(0.997290), sample_t(0.689541), sample_t(-0.555570),
    sample_t(-0.555570), sample_t(0.914210), sample_t(-0.893224), sample_t(0.427555), sample_t(0.740951), sample_t(-0.405241), sample_t(-0.870087), sample_t(-0.881921),
    sample_t(-0.471397), sample_t(0.653173), sample_t(0.575808), sample_t(-0.970031), sample_t(0.989177), sample_t(-0.788346), sample_t(-0.219101), sample_t(0.923880),
    sample_t(0.923880), sample_t(0.844854), sample_t(0.992480), sample_t(0.595699), sample_t(-0.857729), sample_t(0.170962), sample_t(0.073565), sample_t(0.290285),
};

static const sample_t ZC_Q_LUT[NUM_DATA_SC] = {
    sample_t(0.997290), sample_t(-0.985278), sample_t(0.514103), sample_t(0.803208), sample_t(-0.122411), sample_t(-0.534998), sample_t(-0.382683), sample_t(0.382683),
    sample_t(0.975702), sample_t(-0.615232), sample_t(0.146730), sample_t(-0.242980), sample_t(0.817585), sample_t(-0.757209), sample_t(-0.881921), sample_t(-0.471397),
    sample_t(-0.492898), sample_t(-0.914210), sample_t(-0.671559), sample_t(0.903989), sample_t(-0.449611), sample_t(0.405241), sample_t(-0.831470), sample_t(0.831470),
    sample_t(0.724247), sample_t(-0.049068), sample_t(0.427555), sample_t(0.999699), sample_t(-0.122411), sample_t(-0.634393), sample_t(0.773010), sample_t(-0.449611),
    sample_t(-0.534998), sample_t(0.803208), sample_t(0.970031), sample_t(0.870087), sample_t(0.985278), sample_t(0.707107), sample_t(-0.707107), sample_t(-0.170962),
    sample_t(0.492898), sample_t(-0.242980), sample_t(-0.595699), sample_t(0.844854), sample_t(0.893224), sample_t(0.634393), sample_t(0.773010), sample_t(0.992480),
    sample_t(0.024541), sample_t(0.998795), sample_t(-0.997290), sample_t(0.689541), sample_t(0.555570), sample_t(-0.555570), sample_t(-0.914210), sample_t(-0.893224),
    sample_t(-0.427555), sample_t(0.740951), sample_t(0.405241), sample_t(-0.870087), sample_t(0.881921), sample_t(-0.471397), sample_t(-0.653173), sample_t(0.575808),
    sample_t(0.970031), sample_t(0.989177), sample_t(0.788346), sample_t(-0.219101), sample_t(-0.923880), sample_t(0.923880), sample_t(-0.844854), sample_t(0.992480),
    sample_t(-0.595699), sample_t(-0.170962), sample_t(0.073565), sample_t(-0.290285), sample_t(-0.956940), sample_t(-0.266713), sample_t(0.932993), sample_t(-0.998795),
    sample_t(0.941544), sample_t(-0.313682), sample_t(-0.932993), sample_t(-0.195090), sample_t(0.195090), sample_t(-0.024541), sample_t(-0.757209), sample_t(-0.740951),
    sample_t(0.941544), sample_t(-0.689541), sample_t(0.788346), sample_t(-0.995185), sample_t(0.098017), sample_t(0.949528), sample_t(0.975702), sample_t(0.989177),
    sample_t(0.857729), sample_t(-0.266713), sample_t(-0.817585), sample_t(0.999969), sample_t(0.817585), sample_t(0.266713), sample_t(-0.857729), sample_t(-0.989177),
    sample_t(-0.975702), sample_t(-0.949528), sample_t(-0.098017), sample_t(0.995185), sample_t(-0.788346), sample_t(0.689541), sample_t(-0.941544), sample_t(0.740951),
    sample_t(0.757209), sample_t(0.024541), sample_t(-0.195090), sample_t(0.195090), sample_t(0.932993), sample_t(0.313682), sample_t(-0.941544), sample_t(0.998795),
    sample_t(-0.932993), sample_t(0.266713), sample_t(0.956940), sample_t(0.290285), sample_t(-0.073565), sample_t(0.857729), sample_t(0.595699), sample_t(-0.992480),
    sample_t(0.844854), sample_t(-0.923880), sample_t(0.923880), sample_t(0.219101), sample_t(-0.788346), sample_t(-0.989177), sample_t(-0.970031), sample_t(-0.575808),
    sample_t(0.653173), sample_t(0.471397), sample_t(-0.881921), sample_t(0.870087), sample_t(-0.405241), sample_t(-0.740951), sample_t(0.427555), sample_t(0.893224),
    sample_t(0.914210), sample_t(0.555570), sample_t(-0.555570), sample_t(-0.689541), sample_t(0.997290), sample_t(0.903989), sample_t(-0.024541), sample_t(-0.992480),
    sample_t(-0.773010), sample_t(-0.634393), sample_t(-0.893224), sample_t(-0.844854), sample_t(0.595699), sample_t(0.242980), sample_t(-0.492898), sample_t(0.170962),
    sample_t(0.707107), sample_t(-0.707107), sample_t(-0.985278), sample_t(-0.870087), sample_t(-0.970031), sample_t(-0.803208), sample_t(0.534998), sample_t(0.449611),
    sample_t(-0.773010), sample_t(0.634393), sample_t(0.122411), sample_t(-0.999699), sample_t(-0.427555), sample_t(-0.073565), sample_t(-0.724247), sample_t(-0.831470),
    sample_t(0.831470), sample_t(-0.405241), sample_t(0.449611), sample_t(-0.903989), sample_t(0.671559), sample_t(0.914210), sample_t(0.492898), sample_t(0.471397),
    sample_t(0.881921), sample_t(0.757209), sample_t(-0.817585), sample_t(0.242980), sample_t(-0.146730), sample_t(0.615232), sample_t(-0.975702), sample_t(-0.382683),
    sample_t(0.382683), sample_t(0.534998), sample_t(0.122411), sample_t(-0.803208), sample_t(-0.514103), sample_t(0.985278), sample_t(-0.997290), sample_t(0.956940),
};

// ============================================================
// SECTION 2: Forward FFT
//
// fwd_inv = true → forward DFT
// scale_sch = 0xAA: Radix-4, 4 stages, 10_10_10_10 → ÷4 each → total ÷256
//
// Same schedule as TX IFFT (also 0xAA, ÷256).  Round-trip:
//   x[n] = IDFT{X[k]} / 256   (TX HLS IFFT)
//   Y[k] = DFT{x[n]}  / 256   (RX HLS FFT)
//   DFT{IDFT{X}/256} = (1/256)·N·X = X  →  Y[k] = X[k] / 256
//
// 0xAA is REQUIRED for input-range safety: a Radix-4 butterfly has
// natural gain ×4; dividing by exactly 4 per stage keeps intermediate
// values bounded for ANY input in [-1,+1).
// 0x55 (÷2/stage) allows 2× net growth per stage → 16× overflow for
// full-scale noisy inputs and MUST NOT be used here.
//
// With Y[k] = X[k]/256:  G ≈ 1/256,  G_eq ≈ 256 (fits ap_fixed<32,10>).
// ============================================================
static void run_fft(csample_t in[FFT_SIZE], csample_t out[FFT_SIZE]) {
    #pragma HLS INLINE off
    hls::fft<fft_cfg>(in, out, /*fwd_inv=*/true, /*scale_sch=*/0xAA);
}

// ============================================================
// SECTION 3: CP Removal
//
// Reads (CP_LEN + FFT_SIZE) samples from stream.
// Discards the first CP_LEN samples (cyclic prefix).
// Stores the remaining FFT_SIZE samples in buf[].
// ============================================================
static void remove_cp_and_read(
    hls::stream<iq_t> &iq_in,
    csample_t          buf[FFT_SIZE]
) {
    #pragma HLS INLINE off
    iq_t s;

    // Discard CP
    SKIP_CP: for (int i = 0; i < CP_LEN; i++) {
        #pragma HLS PIPELINE II=1
        s = iq_in.read();
        (void)s;
    }

    // Read symbol body into FFT input buffer
    READ_SYM: for (int i = 0; i < FFT_SIZE; i++) {
        #pragma HLS PIPELINE II=1
        s = iq_in.read();
        buf[i] = csample_t(s.i, s.q);
    }
}

// ============================================================
// SECTION 4: Channel Estimation (with precomputed G_eq)
//
// Two-phase computation:
//
// Phase 1 — Estimate G[d] = Y_pre[k] * conj(ZC[d]) for each data SC:
//   G[d] = Y_pre[k] * conj(ZC[d])
//   In ideal channel: Y_pre[k] = ZC[k]/256, so G[d] ≈ 1/256
//   (real-valued, positive; ZC is unit-magnitude).
//   This loop is PIPELINED → fast, multiple DSP48s in parallel.
//
// Phase 2 — Precompute G_eq[k] = conj(G[d]) / |G[d]|²:
//   G_eq = conj(G) / |G|²
//   In ideal channel: G_eq = (1/256) / (1/256)² = 256
//   This loop has NO pipeline pragma → HLS serializes it → one
//   divider instance is REUSED for all 200 data subcarriers.
//   This is the key resource fix (was 200× dividers before).
//
// Phase 3 — G_eq for pilot SCs (preamble pilots are known +1):
//   G_pilot[p] = Y_pre[PILOT_IDX[p]] × conj(+1) = Y_pre[PILOT_IDX[p]]
//   G_eq at pilot indices is filled by the same conj/|.|² formula.
//   Used per-symbol for CPE phase tracking.
//
// Equalization in hot path then becomes multiply-only:
//   X_hat[k] = Y_data[k] * G_eq[k]
//   In ideal: (X/256) * 256 = X ✓
// ============================================================
static void estimate_channel(
    csample_t  fft_pre[FFT_SIZE],
    cgeq_t     G_eq[FFT_SIZE]       // precomputed conj(G)/|G|², ≈256 ideal
) {
    #pragma HLS INLINE off
    typedef ap_fixed<32, 10> wide_t;  // range [-512,+512): holds G_eq ≈ 256 (ideal)

    // Temporary G storage (data SCs only, indexed by d not k)
    csample_t G[NUM_DATA_SC];

    // Phase 1: compute G[d] = Y_pre[k] * conj(ZC[d])
    CH_DATA: for (int d = 0; d < NUM_DATA_SC; d++) {
        #pragma HLS PIPELINE II=1
        int k = DATA_SC_IDX[d];
        wide_t y_re = (wide_t)fft_pre[k].real();
        wide_t y_im = (wide_t)fft_pre[k].imag();
        wide_t z_re = (wide_t)ZC_I_LUT[d];
        wide_t z_im = (wide_t)ZC_Q_LUT[d];
        // Y * conj(ZC): (y_re*z_re + y_im*z_im) + j*(y_im*z_re - y_re*z_im)
        G[d] = csample_t(sample_t(y_re * z_re + y_im * z_im),
                         sample_t(y_im * z_re - y_re * z_im));
    }

    // Zero G_eq array
    CH_ZERO: for (int k = 0; k < FFT_SIZE; k++) {
        #pragma HLS PIPELINE II=1
        G_eq[k] = cgeq_t(geq_t(0), geq_t(0));
    }

    // Phase 2: G_eq[k] = conj(G[d]) / |G[d]|²
    // No PIPELINE → HLS serializes → one divider reused for all SCs.
    // Two divisions per SC (g_re/denom, -g_im/denom): correct approach since
    // a single reciprocal would overflow ap_fixed<32,10> (inv≈62500 >> range±512).
    CH_EQ: for (int d = 0; d < NUM_DATA_SC; d++) {
        int k = DATA_SC_IDX[d];
        wide_t g_re = (wide_t)G[d].real();
        wide_t g_im = (wide_t)G[d].imag();
        wide_t denom = g_re * g_re + g_im * g_im;
        if (denom == wide_t(0)) {
            G_eq[k] = cgeq_t(geq_t(0), geq_t(0));
        } else {
            // conj(G) = (g_re, -g_im)
            G_eq[k] = cgeq_t(geq_t(g_re / denom), geq_t(-g_im / denom));
        }
    }

    // Phase 3: G_eq for pilot SCs.
    // Preamble pilots are known BPSK +1, so G_pilot = Y_pre[k] × conj(+1) = Y_pre[k].
    // Same conj(G)/|G|² formula as data SCs.
    // No PIPELINE → one divider instance reused across 6 pilots.
    CH_PILOT: for (int p = 0; p < NUM_PILOT_SC; p++) {
        int k = PILOT_IDX[p];
        wide_t y_re = (wide_t)fft_pre[k].real();
        wide_t y_im = (wide_t)fft_pre[k].imag();
        wide_t denom = y_re * y_re + y_im * y_im;
        if (denom == wide_t(0)) {
            G_eq[k] = cgeq_t(geq_t(0), geq_t(0));
        } else {
            G_eq[k] = cgeq_t(geq_t(y_re / denom), geq_t(-y_im / denom));
        }
    }
}

// ============================================================
// SECTION 5: Single-Subcarrier Equalizer (multiply-only)
//
// Computes X_hat = Y * G_eq  where G_eq = conj(G)/|G|²
// was precomputed once during preamble processing (Section 4).
//
// This replaces the original Y*conj(G)/|G|² division with a
// complex multiply.  In ideal channel:
//   Y ≈ X/256,  G_eq ≈ 256  →  X_hat = (X/256)*256 = X ✓
//
// Resource saving: no combinational dividers in the hot path.
// HLS maps each multiply to a DSP48; the loop can be fully
// pipelined without triggering 200× divider instantiation.
// ============================================================
static cgeq_t equalize_sc(csample_t Y, cgeq_t G_eq) {
    #pragma HLS INLINE
    typedef ap_fixed<32, 10> acc_t;  // range [-512,+512): holds noisy equalized value ≈ ±1.4

    acc_t y_re = (acc_t)Y.real();
    acc_t y_im = (acc_t)Y.imag();
    acc_t g_re = (acc_t)G_eq.real();
    acc_t g_im = (acc_t)G_eq.imag();

    // Complex multiply: (y_re + j*y_im) * (g_re + j*g_im)
    acc_t x_re = y_re * g_re - y_im * g_im;
    acc_t x_im = y_re * g_im + y_im * g_re;

    // Return as cgeq_t (ap_fixed<32,10>) — do NOT cast down to sample_t here.
    // With noise, x_re can exceed ±1.0 and would wrap in ap_fixed<16,1>.
    // The demapper only needs sign/threshold comparison, not a narrow type.
    return cgeq_t(geq_t(x_re), geq_t(x_im));
}

// ============================================================
// SECTION 5b: CPE Rotation Helper
//
// Applies the inverse of the common phase error to a single equalized symbol.
//   cpe_cos = cos(phase_err),  cpe_sin = sin(phase_err)  — both geq_t ∈ [-1,+1)
//   corrected = sym × exp(-j·phase_err)
//   re' =  re × cpe_cos + im × cpe_sin
//   im' = -re × cpe_sin + im × cpe_cos
//
// All arithmetic in ap_fixed<32,10> — 4 DSP48 multiplies per call.
// Caller converts sincosf float output to geq_t once per symbol.
// ============================================================
static cgeq_t apply_cpe(cgeq_t sym, geq_t cpe_cos, geq_t cpe_sin) {
    #pragma HLS INLINE
    return cgeq_t( sym.real() * cpe_cos + sym.imag() * cpe_sin,
                  -sym.real() * cpe_sin + sym.imag() * cpe_cos);
}

// ============================================================
// SECTION 5c: Pilot-Based CPE Estimation
//
// Computes the common phase error (CPE) for one data symbol using
// the 6 BPSK pilot subcarriers at PILOT_IDX = {50,75,100,154,179,204}.
//
// Pilots are transmitted as known +1 (real), so after equalization any
// residual phase (from residual CFO, oscillator phase noise, etc.) appears
// directly as angle(equalized_pilot).
//
// Averaging 6 pilots reduces noise on the estimate.
// Returns phase_err in radians; caller computes cos/sin once per symbol.
// ============================================================
static float compute_pilot_cpe(csample_t fft_out[FFT_SIZE], cgeq_t G_eq[FFT_SIZE]) {
    #pragma HLS INLINE off
    // Fixed-point accumulators: a float adder has ~6-cycle latency, which would
    // prevent II=1 on the loop-carried sum. geq_t (ap_fixed<32,10>) adder is 1 cycle.
    geq_t sum_sin = 0;
    geq_t sum_cos = 0;

    CPE_PILOTS: for (int p = 0; p < NUM_PILOT_SC; p++) {
        #pragma HLS PIPELINE II=1
        cgeq_t eq = equalize_sc(fft_out[PILOT_IDX[p]], G_eq[PILOT_IDX[p]]);
        // Pilot expected at +1 (angle 0); measured angle = CPE
        sum_sin += (geq_t)eq.imag();
        sum_cos += (geq_t)eq.real();
    }
    // Cast to float only once for the atan2f CORDIC call
    return hls::atan2f((float)sum_sin, (float)sum_cos);
}

// ============================================================
// SECTION 6: QPSK Demapper
//
// Inverts qpsk_map() from ofdm_tx.cpp:
//   bit1 = sign(I): I < 0 → 1,  I ≥ 0 → 0
//   bit0 = sign(Q): Q < 0 → 1,  Q ≥ 0 → 0
// Returns 2-bit QPSK index matching qpsk_map() encoding.
// ============================================================
static ap_uint<2> qpsk_demap(cgeq_t sym) {
    #pragma HLS INLINE
    // Input is cgeq_t (ap_fixed<32,10>) — wide enough to hold noisy equalized
    // values without overflow (e.g. ±1.4 at 10 dB SNR fits, ±1.0 would wrap
    // in the old ap_fixed<16,1> input type).
    ap_uint<2> result;
    result[1] = (sym.real() < geq_t(0)) ? ap_uint<1>(1) : ap_uint<1>(0);
    result[0] = (sym.imag() < geq_t(0)) ? ap_uint<1>(1) : ap_uint<1>(0);
    return result;
}

// ============================================================
// SECTION 7: 16-QAM Demapper
//
// Inverts qam16_map() from ofdm_tx.cpp.
// Each axis is sliced into 4 regions using threshold ±2/√10:
//   v ≥ +2/√10          → bits 00  (+3/√10)
//   0 ≤ v < +2/√10      → bits 01  (+1/√10)
//   -2/√10 ≤ v < 0      → bits 11  (-1/√10)
//   v < -2/√10           → bits 10  (-3/√10)
// Returns 4-bit index [I_bits(3:2), Q_bits(1:0)].
// ============================================================
static ap_uint<4> qam16_demap(cgeq_t sym) {
    #pragma HLS INLINE
    const geq_t THRESH = geq_t(0.6325);   // 2/sqrt(10), in ap_fixed<32,10>

    ap_uint<2> i_bits, q_bits;

    if (sym.real() >= THRESH)
        i_bits = ap_uint<2>(0b00);
    else if (sym.real() >= geq_t(0))
        i_bits = ap_uint<2>(0b01);
    else if (sym.real() >= -THRESH)
        i_bits = ap_uint<2>(0b11);
    else
        i_bits = ap_uint<2>(0b10);

    if (sym.imag() >= THRESH)
        q_bits = ap_uint<2>(0b00);
    else if (sym.imag() >= geq_t(0))
        q_bits = ap_uint<2>(0b01);
    else if (sym.imag() >= -THRESH)
        q_bits = ap_uint<2>(0b11);
    else
        q_bits = ap_uint<2>(0b10);

    // Explicit 4-bit container to avoid ap_uint<2><<2 truncation.
    ap_uint<4> result;
    result[3] = i_bits[1];
    result[2] = i_bits[0];
    result[1] = q_bits[1];
    result[0] = q_bits[0];
    return result;
}

// ============================================================
// SECTION 8: Equalize, CPE-Correct, Demap, and Pack one Data Symbol
//
// 1 SC per loop iteration, #pragma HLS PIPELINE II=1.
// No loop-unrolling: the byte accumulator has a 1-cycle carry dependency
// (ap_uint OR) which is the loop-carried critical path — well within II=1.
//
// cpe_cos/cpe_sin: geq_t (ap_fixed<32,10>), converted once per symbol by caller.
// apply_cpe(): 4 DSP48 multiplies (fixed-point), no float casts.
//
// QPSK  (mod=0): 200 iterations, write byte every 4th  → 50 bytes/symbol
// 16QAM (mod=1): 200 iterations, write byte every 2nd  → 100 bytes/symbol
//
// Byte layout (unchanged from TX):
//   QPSK:  [sc0[7:6]|sc1[5:4]|sc2[3:2]|sc3[1:0]]
//   16QAM: [sc0[7:4]|sc1[3:0]]
// ============================================================
static void equalize_demap_pack(
    csample_t               fft_out[FFT_SIZE],
    cgeq_t                  G_eq[FFT_SIZE],
    mod_t                   mod,
    geq_t                   cpe_cos,   // cos(phase_err), geq_t ∈ [-1,+1)
    geq_t                   cpe_sin,   // sin(phase_err), geq_t ∈ [-1,+1)
    hls::stream<ap_uint<8>> &bits_out
) {
    #pragma HLS INLINE off

    if (mod == 0) {
        // QPSK: 2 bits/SC → 4 SCs per byte
        ap_uint<8> byte_acc = 0;
        QPSK_PACK: for (int i = 0; i < NUM_DATA_SC; i++) {
            #pragma HLS PIPELINE II=1
            cgeq_t eq  = equalize_sc(fft_out[DATA_SC_IDX[i]], G_eq[DATA_SC_IDX[i]]);
            ap_uint<2> sym = qpsk_demap(apply_cpe(eq, cpe_cos, cpe_sin));

            // Place 2-bit symbol at the correct offset within the byte.
            // Reset accumulator at the start of each new byte (i%4==0).
            ap_uint<8> shifted = (ap_uint<8>)sym << ((3 - (i & 3)) * 2);
            byte_acc = ((i & 3) == 0) ? shifted : (byte_acc | shifted);

            if ((i & 3) == 3) bits_out.write(byte_acc);
        }
    } else {
        // 16-QAM: 4 bits/SC → 2 SCs per byte
        ap_uint<8> byte_acc = 0;
        QAM16_PACK: for (int i = 0; i < NUM_DATA_SC; i++) {
            #pragma HLS PIPELINE II=1
            cgeq_t eq  = equalize_sc(fft_out[DATA_SC_IDX[i]], G_eq[DATA_SC_IDX[i]]);
            ap_uint<4> sym = qam16_demap(apply_cpe(eq, cpe_cos, cpe_sin));

            // Even SC → upper nibble; odd SC → lower nibble.
            ap_uint<8> shifted = ((i & 1) == 0) ? (ap_uint<8>)((ap_uint<8>)sym << 4)
                                                 : (ap_uint<8>)sym;
            byte_acc = ((i & 1) == 0) ? shifted : (byte_acc | shifted);

            if ((i & 1) == 1) bits_out.write(byte_acc);
        }
    }
}

// ============================================================
// SECTION 8b: CRC-16/CCITT (polynomial 0x1021, init 0xFFFF)
//
// Identical to the TX-side crc16_hdr — computes CRC over the
// 10-bit header payload for verification.
// Fully unrolled → pure combinational.
// ============================================================
static ap_uint<16> crc16_hdr(ap_uint<10> data) {
    ap_uint<16> crc = 0xFFFF;
    for (int i = 9; i >= 0; i--) {
        #pragma HLS UNROLL
        ap_uint<1> x = crc[15] ^ data[i];
        crc = (ap_uint<16>)(crc << 1);
        if (x) crc ^= ap_uint<16>(0x1021);
    }
    return crc;
}

// ============================================================
// SECTION 9: Top-Level OFDM RX
//
// Timing and CFO are corrected upstream by sync_detect + cfo_correct.
// Frame structure: [Preamble] [Header] [Data × n_syms]
//
// Header symbol: BPSK on DATA_SC_IDX[0..25], MSB first.
//   bits[25:10] = CRC-16/CCITT over bits[9:0]
//   bits[9:2]   = n_syms[7:0]
//   bits[1]     = reserved (0)
//   bits[0]     = mod (0=QPSK, 1=16QAM)
// CRC failure: header_err=1, function returns without writing bits_out.
// ============================================================
void ofdm_rx(
    hls::stream<iq_t>       &iq_in,
    hls::stream<ap_uint<8>> &bits_out,
    ap_uint<1>              &header_err
) {
    #pragma HLS INTERFACE axis      port=iq_in
    #pragma HLS INTERFACE axis      port=bits_out
    #pragma HLS INTERFACE s_axilite port=header_err bundle=ctrl
    #pragma HLS INTERFACE s_axilite port=return     bundle=ctrl

    csample_t time_buf[FFT_SIZE];
    csample_t freq_buf[FFT_SIZE];
    cgeq_t    G_eq[FFT_SIZE];       // precomputed equalizer: conj(G)/|G|², ≈256 ideal

    // ── 1. Preamble: estimate channel, precompute G_eq ─────────
    remove_cp_and_read(iq_in, time_buf);
    run_fft(time_buf, freq_buf);
    estimate_channel(freq_buf, G_eq);

    // ── 2. Header symbol: BPSK demap 26 SCs → extract mod, n_syms ──
    remove_cp_and_read(iq_in, time_buf);
    run_fft(time_buf, freq_buf);

    float hdr_phase_err = compute_pilot_cpe(freq_buf, G_eq);
    float hdr_cos_f, hdr_sin_f;
    hls::sincosf(hdr_phase_err, &hdr_sin_f, &hdr_cos_f);
    geq_t hdr_cos = (geq_t)hdr_cos_f;
    geq_t hdr_sin = (geq_t)hdr_sin_f;

    // Demap 26 BPSK header bits, MSB first (d=0 → bit 25).
    // Separate raw-bit array avoids loop-carried read-modify-write on hdr_bits.
    ap_uint<1> hdr_raw[26];
    #pragma HLS ARRAY_PARTITION variable=hdr_raw complete
    HDR_DEMAP: for (int d = 0; d < 26; d++) {
        #pragma HLS PIPELINE II=1
        cgeq_t eq  = equalize_sc(freq_buf[DATA_SC_IDX[d]], G_eq[DATA_SC_IDX[d]]);
        cgeq_t rot = apply_cpe(eq, hdr_cos, hdr_sin);
        hdr_raw[d] = (rot.real() < geq_t(0)) ? ap_uint<1>(1) : ap_uint<1>(0);
    }

    ap_uint<26> hdr_bits = 0;
    for (int d = 0; d < 26; d++) {
        #pragma HLS UNROLL
        hdr_bits[25 - d] = hdr_raw[d];
    }

    ap_uint<16> rx_crc     = hdr_bits(25, 10);
    ap_uint<10> rx_payload = hdr_bits(9, 0);
    ap_uint<16> exp_crc    = crc16_hdr(rx_payload);

    if (rx_crc != exp_crc) {
        header_err = 1;
        // Drain remainder of this packet so the stream is clean for the next
        // invocation.  sync_detect sets TLAST on the last sample of the frame,
        // so this loop always terminates within one packet.
        DRAIN: do {
            #pragma HLS PIPELINE II=1
            iq_t s = iq_in.read();
            if (s.last) break;
        } while (true);
        return;
    }
    header_err = 0;
    mod_t     mod    = (mod_t)rx_payload[0];
    ap_uint<8> n_syms = rx_payload(9, 2);

    // ── 3. Data symbols: pilot CPE track → equalize → demap → pack ──
    RX_SYMBOL_LOOP: for (ap_uint<8> s = 0; s < n_syms; s++) {
        remove_cp_and_read(iq_in, time_buf);
        run_fft(time_buf, freq_buf);

        // Estimate common phase error from 6 BPSK pilots
        float phase_err = compute_pilot_cpe(freq_buf, G_eq);
        // sincosf → CORDIC once per symbol; convert to geq_t before the 200-SC hot path
        float cpe_cos_f, cpe_sin_f;
        hls::sincosf(phase_err, &cpe_sin_f, &cpe_cos_f);
        geq_t cpe_cos = (geq_t)cpe_cos_f;
        geq_t cpe_sin = (geq_t)cpe_sin_f;

        equalize_demap_pack(freq_buf, G_eq, mod, cpe_cos, cpe_sin, bits_out);
    }
}
