-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_enc is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    data_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    data_in_TVALID : IN STD_LOGIC;
    data_in_TREADY : OUT STD_LOGIC;
    coded_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    coded_out_TVALID : OUT STD_LOGIC;
    coded_out_TREADY : IN STD_LOGIC;
    s_axi_ctrl_AWVALID : IN STD_LOGIC;
    s_axi_ctrl_AWREADY : OUT STD_LOGIC;
    s_axi_ctrl_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_WVALID : IN STD_LOGIC;
    s_axi_ctrl_WREADY : OUT STD_LOGIC;
    s_axi_ctrl_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_ctrl_ARVALID : IN STD_LOGIC;
    s_axi_ctrl_ARREADY : OUT STD_LOGIC;
    s_axi_ctrl_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_RVALID : OUT STD_LOGIC;
    s_axi_ctrl_RREADY : IN STD_LOGIC;
    s_axi_ctrl_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_ctrl_BVALID : OUT STD_LOGIC;
    s_axi_ctrl_BREADY : IN STD_LOGIC;
    s_axi_ctrl_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv_enc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv_enc_conv_enc,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a50t-csg325-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.071600,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=426,HLS_SYN_LUT=769,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal rate : STD_LOGIC_VECTOR (0 downto 0);
    signal n_data_bytes : STD_LOGIC_VECTOR (31 downto 0);
    signal data_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln59_fu_245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal coded_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln62_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln67_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln67_reg_587 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln70_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal and_ln70_reg_596 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal n_data_bytes_read_reg_537 : STD_LOGIC_VECTOR (31 downto 0);
    signal rate_read_reg_542 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln59_1_fu_250_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln59_1_reg_553 : STD_LOGIC_VECTOR (30 downto 0);
    signal in_byte_reg_558 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln62_fu_278_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln62_reg_566 : STD_LOGIC_VECTOR (0 downto 0);
    signal g1_fu_367_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal g1_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal sr_1_fu_383_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sr_1_reg_576 : STD_LOGIC_VECTOR (5 downto 0);
    signal out_byte_3_fu_391_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_byte_3_reg_581 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_pos_3_fu_408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_pos_3_reg_591 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_byte_4_fu_447_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_pos_4_fu_463_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal global_bit_4_fu_469_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal bit_pos_1_fu_475_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal bit_pos_reg_135 : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_coded_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal ap_predicate_op97_write_state5 : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal global_bit_2_reg_147 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_out_byte_2_phi_fu_160_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op96_write_state4 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal ap_phi_mux_out_pos_2_phi_fu_171_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_out_byte_1_phi_fu_182_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_byte_1_reg_179 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_out_pos_1_phi_fu_195_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_pos_1_reg_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal byte_idx_fu_86 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    signal ap_predicate_op76_write_state3 : BOOLEAN;
    signal ap_block_state3 : BOOLEAN;
    signal indvars_iv_fu_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln59_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_byte_fu_94 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal global_bit_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_ln62_fu_414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_pos_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sr_fu_106 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal zext_ln59_fu_241_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln62_fu_274_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln63_fu_286_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_fu_291_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln25_fu_319_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_295_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_303_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln25_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln25_2_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln25_1_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_347_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_1_fu_361_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln_fu_373_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal out_byte_3_fu_391_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_byte_3_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_byte_4_fu_447_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_data_in_U_apdone_blk : STD_LOGIC;
    signal data_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal data_in_TVALID_int_regslice : STD_LOGIC;
    signal data_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_data_in_U_ack_in : STD_LOGIC;
    signal coded_out_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal coded_out_TVALID_int_regslice : STD_LOGIC;
    signal coded_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_coded_out_U_vld_out : STD_LOGIC;
    signal out_byte_3_fu_391_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_byte_4_fu_447_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv_enc_bitset_8ns_8ns_3ns_1ns_8_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        value : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component conv_enc_ctrl_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rate : OUT STD_LOGIC_VECTOR (0 downto 0);
        n_data_bytes : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv_enc_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    ctrl_s_axi_U : component conv_enc_ctrl_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_ctrl_AWVALID,
        AWREADY => s_axi_ctrl_AWREADY,
        AWADDR => s_axi_ctrl_AWADDR,
        WVALID => s_axi_ctrl_WVALID,
        WREADY => s_axi_ctrl_WREADY,
        WDATA => s_axi_ctrl_WDATA,
        WSTRB => s_axi_ctrl_WSTRB,
        ARVALID => s_axi_ctrl_ARVALID,
        ARREADY => s_axi_ctrl_ARREADY,
        ARADDR => s_axi_ctrl_ARADDR,
        RVALID => s_axi_ctrl_RVALID,
        RREADY => s_axi_ctrl_RREADY,
        RDATA => s_axi_ctrl_RDATA,
        RRESP => s_axi_ctrl_RRESP,
        BVALID => s_axi_ctrl_BVALID,
        BREADY => s_axi_ctrl_BREADY,
        BRESP => s_axi_ctrl_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        rate => rate,
        n_data_bytes => n_data_bytes,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    bitset_8ns_8ns_3ns_1ns_8_1_1_U1 : component conv_enc_bitset_8ns_8ns_3ns_1ns_8_1_1
    generic map (
        DATAWIDTH => 8,
        ADDRWIDTH => 3)
    port map (
        din => out_byte_fu_94,
        sel => out_byte_3_fu_391_p2,
        value => out_byte_3_fu_391_p3,
        dout => out_byte_3_fu_391_p4);

    bitset_8ns_8ns_3ns_1ns_8_1_1_U2 : component conv_enc_bitset_8ns_8ns_3ns_1ns_8_1_1
    generic map (
        DATAWIDTH => 8,
        ADDRWIDTH => 3)
    port map (
        din => ap_phi_mux_out_byte_2_phi_fu_160_p4,
        sel => out_byte_4_fu_447_p2,
        value => g1_reg_571,
        dout => out_byte_4_fu_447_p4);

    regslice_both_data_in_U : component conv_enc_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => data_in_TDATA,
        vld_in => data_in_TVALID,
        ack_in => regslice_both_data_in_U_ack_in,
        data_out => data_in_TDATA_int_regslice,
        vld_out => data_in_TVALID_int_regslice,
        ack_out => data_in_TREADY_int_regslice,
        apdone_blk => regslice_both_data_in_U_apdone_blk);

    regslice_both_coded_out_U : component conv_enc_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => coded_out_TDATA_int_regslice,
        vld_in => coded_out_TVALID_int_regslice,
        ack_in => coded_out_TREADY_int_regslice,
        data_out => coded_out_TDATA,
        vld_out => regslice_both_coded_out_U_vld_out,
        ack_out => coded_out_TREADY,
        apdone_blk => regslice_both_coded_out_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    bit_pos_reg_135_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                bit_pos_reg_135 <= bit_pos_1_fu_475_p2;
            elsif (((icmp_ln59_fu_245_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
                bit_pos_reg_135 <= ap_const_lv4_7;
            end if; 
        end if;
    end process;

    byte_idx_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                byte_idx_fu_86 <= ap_const_lv31_0;
            elsif (((icmp_ln62_fu_259_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then 
                byte_idx_fu_86 <= add_ln59_1_reg_553;
            end if; 
        end if;
    end process;

    global_bit_2_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                global_bit_2_reg_147 <= global_bit_4_fu_469_p2;
            elsif (((icmp_ln59_fu_245_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
                global_bit_2_reg_147 <= global_bit_fu_98;
            end if; 
        end if;
    end process;

    global_bit_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                global_bit_fu_98 <= ap_const_lv32_0;
            elsif (((icmp_ln62_fu_259_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then 
                global_bit_fu_98 <= add_ln62_fu_414_p2;
            end if; 
        end if;
    end process;

    indvars_iv_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvars_iv_fu_90 <= ap_const_lv32_8;
            elsif (((icmp_ln62_fu_259_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then 
                indvars_iv_fu_90 <= add_ln59_fu_419_p2;
            end if; 
        end if;
    end process;

    out_byte_1_reg_179_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln70_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
                out_byte_1_reg_179 <= ap_phi_mux_out_byte_2_phi_fu_160_p4;
            elsif (((icmp_ln71_fu_457_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln70_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
                out_byte_1_reg_179 <= out_byte_4_fu_447_p4;
            elsif (((icmp_ln71_reg_606 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_reg_596) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                out_byte_1_reg_179 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    out_byte_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_byte_fu_94 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                out_byte_fu_94 <= ap_phi_mux_out_byte_1_phi_fu_182_p6;
            end if; 
        end if;
    end process;

    out_pos_1_reg_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = and_ln70_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
                out_pos_1_reg_192 <= ap_phi_mux_out_pos_2_phi_fu_171_p4;
            elsif (((icmp_ln71_fu_457_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln70_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then 
                out_pos_1_reg_192 <= out_pos_4_fu_463_p2;
            elsif (((icmp_ln71_reg_606 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_reg_596) and (ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                out_pos_1_reg_192 <= ap_const_lv32_7;
            end if; 
        end if;
    end process;

    out_pos_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                out_pos_fu_102 <= ap_const_lv32_7;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                out_pos_fu_102 <= ap_phi_mux_out_pos_1_phi_fu_195_p6;
            end if; 
        end if;
    end process;

    sr_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sr_fu_106 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then 
                sr_fu_106 <= sr_1_reg_576;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln59_1_reg_553 <= add_ln59_1_fu_250_p2;
                in_byte_reg_558 <= data_in_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                and_ln70_reg_596 <= and_ln70_fu_443_p2;
                icmp_ln71_reg_606 <= icmp_ln71_fu_457_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                g1_reg_571 <= g1_fu_367_p2;
                icmp_ln67_reg_587 <= icmp_ln67_fu_402_p2;
                out_byte_3_reg_581 <= out_byte_3_fu_391_p4;
                out_pos_3_reg_591 <= out_pos_3_fu_408_p2;
                sr_1_reg_576 <= sr_1_fu_383_p3;
                trunc_ln62_reg_566 <= trunc_ln62_fu_278_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                n_data_bytes_read_reg_537 <= n_data_bytes;
                rate_read_reg_542 <= rate;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln59_fu_245_p2, ap_CS_fsm_state3, icmp_ln62_fu_259_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_block_state2, ap_block_state5, ap_block_state4, ap_block_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln59_fu_245_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln59_fu_245_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln62_fu_259_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln62_fu_259_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_const_boolean_0 = ap_block_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln59_1_fu_250_p2 <= std_logic_vector(unsigned(byte_idx_fu_86) + unsigned(ap_const_lv31_1));
    add_ln59_fu_419_p2 <= std_logic_vector(unsigned(indvars_iv_fu_90) + unsigned(ap_const_lv32_8));
    add_ln62_fu_414_p2 <= std_logic_vector(unsigned(global_bit_fu_98) + unsigned(ap_const_lv32_8));
    and_ln70_fu_443_p2 <= (trunc_ln62_reg_566 and rate_read_reg_542);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_assign_proc : process(icmp_ln59_fu_245_p2, regslice_both_coded_out_U_apdone_blk, data_in_TVALID_int_regslice)
    begin
                ap_block_state2 <= ((regslice_both_coded_out_U_apdone_blk = ap_const_logic_1) or ((icmp_ln59_fu_245_p2 = ap_const_lv1_1) and (data_in_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state3_assign_proc : process(ap_predicate_op76_write_state3, coded_out_TREADY_int_regslice)
    begin
                ap_block_state3 <= ((coded_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op76_write_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_assign_proc : process(icmp_ln67_reg_587, ap_predicate_op96_write_state4, coded_out_TREADY_int_regslice)
    begin
                ap_block_state4 <= (((icmp_ln67_reg_587 = ap_const_lv1_1) and (coded_out_TREADY_int_regslice = ap_const_logic_0)) or ((coded_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op96_write_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state5_assign_proc : process(ap_predicate_op97_write_state5, coded_out_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((coded_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op97_write_state5 = ap_const_boolean_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln59_fu_245_p2, ap_block_state2)
    begin
        if (((icmp_ln59_fu_245_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_out_byte_1_phi_fu_182_p6_assign_proc : process(ap_CS_fsm_state5, and_ln70_reg_596, icmp_ln71_reg_606, out_byte_1_reg_179)
    begin
        if (((icmp_ln71_reg_606 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_reg_596) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_phi_mux_out_byte_1_phi_fu_182_p6 <= ap_const_lv8_0;
        else 
            ap_phi_mux_out_byte_1_phi_fu_182_p6 <= out_byte_1_reg_179;
        end if; 
    end process;


    ap_phi_mux_out_byte_2_phi_fu_160_p4_assign_proc : process(ap_CS_fsm_state4, icmp_ln67_reg_587, out_byte_3_reg_581)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((icmp_ln67_reg_587 = ap_const_lv1_0)) then 
                ap_phi_mux_out_byte_2_phi_fu_160_p4 <= out_byte_3_reg_581;
            elsif ((icmp_ln67_reg_587 = ap_const_lv1_1)) then 
                ap_phi_mux_out_byte_2_phi_fu_160_p4 <= ap_const_lv8_0;
            else 
                ap_phi_mux_out_byte_2_phi_fu_160_p4 <= "XXXXXXXX";
            end if;
        else 
            ap_phi_mux_out_byte_2_phi_fu_160_p4 <= "XXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_out_pos_1_phi_fu_195_p6_assign_proc : process(ap_CS_fsm_state5, and_ln70_reg_596, icmp_ln71_reg_606, out_pos_1_reg_192)
    begin
        if (((icmp_ln71_reg_606 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_reg_596) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_phi_mux_out_pos_1_phi_fu_195_p6 <= ap_const_lv32_7;
        else 
            ap_phi_mux_out_pos_1_phi_fu_195_p6 <= out_pos_1_reg_192;
        end if; 
    end process;


    ap_phi_mux_out_pos_2_phi_fu_171_p4_assign_proc : process(ap_CS_fsm_state4, icmp_ln67_reg_587, out_pos_3_reg_591)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((icmp_ln67_reg_587 = ap_const_lv1_0)) then 
                ap_phi_mux_out_pos_2_phi_fu_171_p4 <= out_pos_3_reg_591;
            elsif ((icmp_ln67_reg_587 = ap_const_lv1_1)) then 
                ap_phi_mux_out_pos_2_phi_fu_171_p4 <= ap_const_lv32_7;
            else 
                ap_phi_mux_out_pos_2_phi_fu_171_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_out_pos_2_phi_fu_171_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_predicate_op76_write_state3_assign_proc : process(icmp_ln62_fu_259_p2, icmp_ln67_fu_402_p2)
    begin
                ap_predicate_op76_write_state3 <= ((icmp_ln67_fu_402_p2 = ap_const_lv1_1) and (icmp_ln62_fu_259_p2 = ap_const_lv1_0));
    end process;


    ap_predicate_op96_write_state4_assign_proc : process(and_ln70_fu_443_p2, icmp_ln71_fu_457_p2)
    begin
                ap_predicate_op96_write_state4 <= ((icmp_ln71_fu_457_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_fu_443_p2));
    end process;


    ap_predicate_op97_write_state5_assign_proc : process(and_ln70_reg_596, icmp_ln71_reg_606)
    begin
                ap_predicate_op97_write_state5 <= ((icmp_ln71_reg_606 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_reg_596));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln59_fu_245_p2, ap_block_state2)
    begin
        if (((icmp_ln59_fu_245_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    b_fu_291_p1 <= lshr_ln63_fu_286_p2(1 - 1 downto 0);
    bit_pos_1_fu_475_p2 <= std_logic_vector(unsigned(bit_pos_reg_135) + unsigned(ap_const_lv4_F));

    coded_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state3, icmp_ln62_fu_259_p2, icmp_ln67_fu_402_p2, ap_CS_fsm_state4, icmp_ln67_reg_587, and_ln70_fu_443_p2, icmp_ln71_fu_457_p2, ap_CS_fsm_state5, and_ln70_reg_596, icmp_ln71_reg_606, coded_out_TREADY_int_regslice)
    begin
        if ((((icmp_ln71_reg_606 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_reg_596) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((icmp_ln71_fu_457_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln70_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln67_reg_587 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln67_fu_402_p2 = ap_const_lv1_1) and (icmp_ln62_fu_259_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            coded_out_TDATA_blk_n <= coded_out_TREADY_int_regslice;
        else 
            coded_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    coded_out_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, out_byte_3_fu_391_p4, out_byte_4_fu_447_p4, ap_predicate_op96_write_state4, ap_block_state4, ap_predicate_op76_write_state3, ap_block_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_predicate_op96_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_state4))) then 
            coded_out_TDATA_int_regslice <= out_byte_4_fu_447_p4;
        elsif (((ap_predicate_op76_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3))) then 
            coded_out_TDATA_int_regslice <= out_byte_3_fu_391_p4;
        else 
            coded_out_TDATA_int_regslice <= "XXXXXXXX";
        end if; 
    end process;

    coded_out_TVALID <= regslice_both_coded_out_U_vld_out;

    coded_out_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_predicate_op96_write_state4, ap_block_state4, ap_predicate_op76_write_state3, ap_block_state3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_predicate_op96_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_state4)) or ((ap_predicate_op76_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_boolean_0 = ap_block_state3)))) then 
            coded_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            coded_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    data_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, icmp_ln59_fu_245_p2, data_in_TVALID_int_regslice)
    begin
        if (((icmp_ln59_fu_245_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            data_in_TDATA_blk_n <= data_in_TVALID_int_regslice;
        else 
            data_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    data_in_TREADY <= regslice_both_data_in_U_ack_in;

    data_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state2, icmp_ln59_fu_245_p2, ap_block_state2)
    begin
        if (((icmp_ln59_fu_245_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2))) then 
            data_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            data_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    g1_fu_367_p2 <= (xor_ln26_fu_355_p2 xor xor_ln26_1_fu_361_p2);
    global_bit_4_fu_469_p2 <= std_logic_vector(unsigned(global_bit_2_reg_147) + unsigned(ap_const_lv32_1));
    icmp_ln59_fu_245_p2 <= "1" when (signed(zext_ln59_fu_241_p1) < signed(n_data_bytes_read_reg_537)) else "0";
    icmp_ln62_fu_259_p2 <= "1" when (global_bit_2_reg_147 = indvars_iv_fu_90) else "0";
    icmp_ln67_fu_402_p2 <= "1" when (out_pos_fu_102 = ap_const_lv32_0) else "0";
    icmp_ln71_fu_457_p2 <= "1" when (ap_phi_mux_out_pos_2_phi_fu_171_p4 = ap_const_lv32_0) else "0";
    lshr_ln63_fu_286_p2 <= std_logic_vector(shift_right(unsigned(in_byte_reg_558),to_integer(unsigned('0' & zext_ln62_fu_274_p1(8-1 downto 0)))));
    lshr_ln_fu_373_p4 <= sr_fu_106(5 downto 1);
    out_byte_3_fu_391_p2 <= out_pos_fu_102(3 - 1 downto 0);
    out_byte_3_fu_391_p3 <= (xor_ln25_2_fu_335_p2 xor xor_ln25_1_fu_329_p2);
    out_byte_4_fu_447_p2 <= ap_phi_mux_out_pos_2_phi_fu_171_p4(3 - 1 downto 0);
    out_pos_3_fu_408_p2 <= std_logic_vector(unsigned(out_pos_fu_102) + unsigned(ap_const_lv32_FFFFFFFF));
    out_pos_4_fu_463_p2 <= std_logic_vector(unsigned(ap_phi_mux_out_pos_2_phi_fu_171_p4) + unsigned(ap_const_lv32_FFFFFFFF));
    sr_1_fu_383_p3 <= (b_fu_291_p1 & lshr_ln_fu_373_p4);
    tmp_1_fu_303_p3 <= sr_fu_106(3 downto 3);
    tmp_2_fu_311_p3 <= sr_fu_106(1 downto 1);
    tmp_3_fu_347_p3 <= sr_fu_106(5 downto 5);
    tmp_fu_295_p3 <= sr_fu_106(4 downto 4);
    trunc_ln25_fu_319_p1 <= sr_fu_106(1 - 1 downto 0);
    trunc_ln62_fu_278_p1 <= global_bit_2_reg_147(1 - 1 downto 0);
    xor_ln25_1_fu_329_p2 <= (tmp_fu_295_p3 xor tmp_1_fu_303_p3);
    xor_ln25_2_fu_335_p2 <= (xor_ln25_fu_323_p2 xor tmp_2_fu_311_p3);
    xor_ln25_fu_323_p2 <= (trunc_ln25_fu_319_p1 xor b_fu_291_p1);
    xor_ln26_1_fu_361_p2 <= (xor_ln25_fu_323_p2 xor tmp_1_fu_303_p3);
    xor_ln26_fu_355_p2 <= (tmp_fu_295_p3 xor tmp_3_fu_347_p3);
    zext_ln59_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(byte_idx_fu_86),32));
    zext_ln62_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bit_pos_reg_135),8));
end behav;
