// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="interleaver_interleaver,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a50t-csg325-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.832750,HLS_SYN_LAT=87251,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=577,HLS_SYN_LUT=1042,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module interleaver (
        ap_clk,
        ap_rst_n,
        data_in_TDATA,
        data_in_TVALID,
        data_in_TREADY,
        data_out_TDATA,
        data_out_TVALID,
        data_out_TREADY,
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] data_in_TDATA;
input   data_in_TVALID;
output   data_in_TREADY;
output  [7:0] data_out_TDATA;
output   data_out_TVALID;
input   data_out_TREADY;
input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [0:0] mod_r;
wire   [7:0] n_syms;
wire   [0:0] is_rx;
reg   [0:0] is_rx_read_reg_168;
reg   [7:0] n_syms_read_reg_174;
reg   [0:0] mod_r_read_reg_179;
wire   [7:0] s_2_fu_151_p2;
reg   [7:0] s_2_reg_186;
wire    ap_CS_fsm_state2;
reg   [6:0] buf_address0;
reg    buf_ce0;
reg    buf_we0;
reg   [7:0] buf_d0;
wire   [7:0] buf_q0;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_ap_done;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_ap_idle;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_ap_ready;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_data_in_TREADY;
wire   [6:0] grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_address0;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_ce0;
wire    grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_we0;
wire   [7:0] grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_d0;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_ap_start;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_ap_done;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_ap_idle;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_ap_ready;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_data_in_TREADY;
wire   [6:0] grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_address0;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_ce0;
wire    grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_we0;
wire   [7:0] grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_d0;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_ap_done;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_ap_idle;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_ap_ready;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TREADY;
wire   [6:0] grp_interleaver_Pipeline_PERM_Q_fu_122_buf_r_address0;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_buf_r_ce0;
wire   [7:0] grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TDATA;
wire    grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TVALID;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_ap_start;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_ap_done;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_ap_idle;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_ap_ready;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TREADY;
wire   [6:0] grp_interleaver_Pipeline_PERM_16_fu_130_buf_r_address0;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_buf_r_ce0;
wire   [7:0] grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TDATA;
wire    grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TVALID;
reg    grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start_reg;
wire   [0:0] icmp_ln105_fu_146_p2;
wire    ap_CS_fsm_state3;
reg    grp_interleaver_Pipeline_FILL_16_fu_115_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [7:0] data_out_TDATA_reg;
reg    grp_interleaver_Pipeline_PERM_16_fu_130_ap_start_reg;
wire    ap_CS_fsm_state7;
reg   [7:0] s_fu_82;
reg    ap_block_state5_on_subcall_done;
wire    ap_CS_fsm_state8;
wire    regslice_both_data_out_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_data_in_U_apdone_blk;
wire   [7:0] data_in_TDATA_int_regslice;
wire    data_in_TVALID_int_regslice;
reg    data_in_TREADY_int_regslice;
wire    regslice_both_data_in_U_ack_in;
reg   [7:0] data_out_TDATA_int_regslice;
reg    data_out_TVALID_int_regslice;
wire    data_out_TREADY_int_regslice;
wire    regslice_both_data_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start_reg = 1'b0;
#0 grp_interleaver_Pipeline_FILL_16_fu_115_ap_start_reg = 1'b0;
#0 grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start_reg = 1'b0;
#0 grp_interleaver_Pipeline_PERM_16_fu_130_ap_start_reg = 1'b0;
#0 s_fu_82 = 8'd0;
end

interleaver_buf_RAM_1P_LUTRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buf_address0),
    .ce0(buf_ce0),
    .we0(buf_we0),
    .d0(buf_d0),
    .q0(buf_q0)
);

interleaver_interleaver_Pipeline_FILL_Q grp_interleaver_Pipeline_FILL_Q_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start),
    .ap_done(grp_interleaver_Pipeline_FILL_Q_fu_108_ap_done),
    .ap_idle(grp_interleaver_Pipeline_FILL_Q_fu_108_ap_idle),
    .ap_ready(grp_interleaver_Pipeline_FILL_Q_fu_108_ap_ready),
    .data_in_TVALID(data_in_TVALID_int_regslice),
    .data_in_TDATA(data_in_TDATA_int_regslice),
    .data_in_TREADY(grp_interleaver_Pipeline_FILL_Q_fu_108_data_in_TREADY),
    .buf_r_address0(grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_address0),
    .buf_r_ce0(grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_ce0),
    .buf_r_we0(grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_we0),
    .buf_r_d0(grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_d0)
);

interleaver_interleaver_Pipeline_FILL_16 grp_interleaver_Pipeline_FILL_16_fu_115(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_interleaver_Pipeline_FILL_16_fu_115_ap_start),
    .ap_done(grp_interleaver_Pipeline_FILL_16_fu_115_ap_done),
    .ap_idle(grp_interleaver_Pipeline_FILL_16_fu_115_ap_idle),
    .ap_ready(grp_interleaver_Pipeline_FILL_16_fu_115_ap_ready),
    .data_in_TVALID(data_in_TVALID_int_regslice),
    .data_in_TDATA(data_in_TDATA_int_regslice),
    .data_in_TREADY(grp_interleaver_Pipeline_FILL_16_fu_115_data_in_TREADY),
    .buf_r_address0(grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_address0),
    .buf_r_ce0(grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_ce0),
    .buf_r_we0(grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_we0),
    .buf_r_d0(grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_d0)
);

interleaver_interleaver_Pipeline_PERM_Q grp_interleaver_Pipeline_PERM_Q_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start),
    .ap_done(grp_interleaver_Pipeline_PERM_Q_fu_122_ap_done),
    .ap_idle(grp_interleaver_Pipeline_PERM_Q_fu_122_ap_idle),
    .ap_ready(grp_interleaver_Pipeline_PERM_Q_fu_122_ap_ready),
    .data_out_TREADY(grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TREADY),
    .is_rx(is_rx_read_reg_168),
    .buf_r_address0(grp_interleaver_Pipeline_PERM_Q_fu_122_buf_r_address0),
    .buf_r_ce0(grp_interleaver_Pipeline_PERM_Q_fu_122_buf_r_ce0),
    .buf_r_q0(buf_q0),
    .data_out_TDATA(grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TDATA),
    .data_out_TVALID(grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TVALID)
);

interleaver_interleaver_Pipeline_PERM_16 grp_interleaver_Pipeline_PERM_16_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_interleaver_Pipeline_PERM_16_fu_130_ap_start),
    .ap_done(grp_interleaver_Pipeline_PERM_16_fu_130_ap_done),
    .ap_idle(grp_interleaver_Pipeline_PERM_16_fu_130_ap_idle),
    .ap_ready(grp_interleaver_Pipeline_PERM_16_fu_130_ap_ready),
    .data_out_TREADY(grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TREADY),
    .is_rx(is_rx_read_reg_168),
    .buf_r_address0(grp_interleaver_Pipeline_PERM_16_fu_130_buf_r_address0),
    .buf_r_ce0(grp_interleaver_Pipeline_PERM_16_fu_130_buf_r_ce0),
    .buf_r_q0(buf_q0),
    .data_out_TDATA(grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TDATA),
    .data_out_TVALID(grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TVALID)
);

interleaver_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .mod_r(mod_r),
    .n_syms(n_syms),
    .is_rx(is_rx),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

interleaver_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_in_TDATA),
    .vld_in(data_in_TVALID),
    .ack_in(regslice_both_data_in_U_ack_in),
    .data_out(data_in_TDATA_int_regslice),
    .vld_out(data_in_TVALID_int_regslice),
    .ack_out(data_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_data_in_U_apdone_blk)
);

interleaver_regslice_both #(
    .DataWidth( 8 ))
regslice_both_data_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(data_out_TDATA_int_regslice),
    .vld_in(data_out_TVALID_int_regslice),
    .ack_in(data_out_TREADY_int_regslice),
    .data_out(data_out_TDATA),
    .vld_out(regslice_both_data_out_U_vld_out),
    .ack_out(data_out_TREADY),
    .apdone_blk(regslice_both_data_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_interleaver_Pipeline_FILL_16_fu_115_ap_start_reg <= 1'b0;
    end else begin
        if (((mod_r_read_reg_179 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln105_fu_146_p2 == 1'd0))) begin
            grp_interleaver_Pipeline_FILL_16_fu_115_ap_start_reg <= 1'b1;
        end else if ((grp_interleaver_Pipeline_FILL_16_fu_115_ap_ready == 1'b1)) begin
            grp_interleaver_Pipeline_FILL_16_fu_115_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if (((mod_r_read_reg_179 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln105_fu_146_p2 == 1'd0))) begin
            grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_interleaver_Pipeline_FILL_Q_fu_108_ap_ready == 1'b1)) begin
            grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_interleaver_Pipeline_PERM_16_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_interleaver_Pipeline_PERM_16_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_interleaver_Pipeline_PERM_16_fu_130_ap_ready == 1'b1)) begin
            grp_interleaver_Pipeline_PERM_16_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_interleaver_Pipeline_PERM_Q_fu_122_ap_ready == 1'b1)) begin
            grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((mod_r_read_reg_179 == 1'd1) & (grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TVALID == 1'b1))) begin
            data_out_TDATA_reg <= grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TDATA;
        end else if (((grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TVALID == 1'b1) & (mod_r_read_reg_179 == 1'd0))) begin
            data_out_TDATA_reg <= grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TDATA;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        s_fu_82 <= 8'd0;
    end else if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        s_fu_82 <= s_2_reg_186;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        is_rx_read_reg_168 <= is_rx;
        mod_r_read_reg_179 <= mod_r;
        n_syms_read_reg_174 <= n_syms;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        s_2_reg_186 <= s_2_fu_151_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_interleaver_Pipeline_FILL_Q_fu_108_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_interleaver_Pipeline_FILL_16_fu_115_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_data_out_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_data_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_data_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((mod_r_read_reg_179 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        buf_address0 = grp_interleaver_Pipeline_PERM_16_fu_130_buf_r_address0;
    end else if (((mod_r_read_reg_179 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        buf_address0 = grp_interleaver_Pipeline_PERM_Q_fu_122_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_address0 = grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_address0 = grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_address0;
    end else begin
        buf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((mod_r_read_reg_179 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        buf_ce0 = grp_interleaver_Pipeline_PERM_16_fu_130_buf_r_ce0;
    end else if (((mod_r_read_reg_179 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        buf_ce0 = grp_interleaver_Pipeline_PERM_Q_fu_122_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_ce0 = grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_ce0 = grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_ce0;
    end else begin
        buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_d0 = grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_d0 = grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_d0;
    end else begin
        buf_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_we0 = grp_interleaver_Pipeline_FILL_16_fu_115_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_we0 = grp_interleaver_Pipeline_FILL_Q_fu_108_buf_r_we0;
    end else begin
        buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        data_in_TREADY_int_regslice = grp_interleaver_Pipeline_FILL_16_fu_115_data_in_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        data_in_TREADY_int_regslice = grp_interleaver_Pipeline_FILL_Q_fu_108_data_in_TREADY;
    end else begin
        data_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if (((mod_r_read_reg_179 == 1'd1) & (grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TVALID == 1'b1))) begin
            data_out_TDATA_int_regslice = grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TDATA;
        end else if (((grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TVALID == 1'b1) & (mod_r_read_reg_179 == 1'd0))) begin
            data_out_TDATA_int_regslice = grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TDATA;
        end else begin
            data_out_TDATA_int_regslice = data_out_TDATA_reg;
        end
    end else begin
        data_out_TDATA_int_regslice = data_out_TDATA_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        if ((mod_r_read_reg_179 == 1'd1)) begin
            data_out_TVALID_int_regslice = grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TVALID;
        end else if ((mod_r_read_reg_179 == 1'd0)) begin
            data_out_TVALID_int_regslice = grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TVALID;
        end else begin
            data_out_TVALID_int_regslice = 1'b0;
        end
    end else begin
        data_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((mod_r_read_reg_179 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln105_fu_146_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((mod_r_read_reg_179 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln105_fu_146_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_interleaver_Pipeline_FILL_Q_fu_108_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_interleaver_Pipeline_FILL_16_fu_115_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_data_out_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state5_on_subcall_done = (((grp_interleaver_Pipeline_PERM_Q_fu_122_ap_done == 1'b0) & (mod_r_read_reg_179 == 1'd0)) | ((mod_r_read_reg_179 == 1'd1) & (grp_interleaver_Pipeline_PERM_16_fu_130_ap_done == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_in_TREADY = regslice_both_data_in_U_ack_in;

assign data_out_TVALID = regslice_both_data_out_U_vld_out;

assign grp_interleaver_Pipeline_FILL_16_fu_115_ap_start = grp_interleaver_Pipeline_FILL_16_fu_115_ap_start_reg;

assign grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start = grp_interleaver_Pipeline_FILL_Q_fu_108_ap_start_reg;

assign grp_interleaver_Pipeline_PERM_16_fu_130_ap_start = grp_interleaver_Pipeline_PERM_16_fu_130_ap_start_reg;

assign grp_interleaver_Pipeline_PERM_16_fu_130_data_out_TREADY = (data_out_TREADY_int_regslice & ap_CS_fsm_state5);

assign grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start = grp_interleaver_Pipeline_PERM_Q_fu_122_ap_start_reg;

assign grp_interleaver_Pipeline_PERM_Q_fu_122_data_out_TREADY = (data_out_TREADY_int_regslice & ap_CS_fsm_state5);

assign icmp_ln105_fu_146_p2 = ((s_fu_82 == n_syms_read_reg_174) ? 1'b1 : 1'b0);

assign s_2_fu_151_p2 = (s_fu_82 + 8'd1);


reg find_kernel_block = 0;
// synthesis translate_off
`include "interleaver_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //interleaver

