// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ofdm_mac_do_tx_Pipeline_HDR_LEN (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        phy_tx_out_TREADY,
        crc_reload,
        zext_ln120,
        phy_tx_out_TDATA,
        phy_tx_out_TVALID,
        crc_22_out,
        crc_22_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   phy_tx_out_TREADY;
input  [31:0] crc_reload;
input  [12:0] zext_ln120;
output  [7:0] phy_tx_out_TDATA;
output   phy_tx_out_TVALID;
output  [31:0] crc_22_out;
output   crc_22_out_ap_vld;

reg ap_idle;
reg phy_tx_out_TVALID;
reg crc_22_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_111_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    phy_tx_out_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [7:0] b_fu_141_p1;
reg   [7:0] b_reg_423;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] crc_22_fu_60;
wire   [31:0] crc_63_fu_388_p3;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire    ap_block_pp0_stage0_grp0;
wire    ap_loop_init;
reg   [1:0] i_fu_64;
wire   [1:0] i_5_fu_145_p2;
reg   [1:0] ap_sig_allocacmp_i_4;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
wire    ap_block_pp0_stage0_01001_grp0;
wire   [0:0] trunc_ln136_fu_119_p1;
wire   [3:0] shl_ln3_fu_123_p3;
wire   [15:0] zext_ln120_cast_fu_94_p1;
wire   [15:0] zext_ln136_fu_131_p1;
wire   [15:0] lshr_ln136_fu_135_p2;
wire   [31:0] shl_ln15_1_fu_159_p3;
wire   [31:0] crc_fu_166_p2;
wire   [31:0] crc_43_fu_180_p2;
wire   [0:0] top_fu_172_p3;
wire   [31:0] crc_45_fu_186_p2;
wire   [31:0] crc_46_fu_192_p3;
wire   [31:0] crc_47_fu_208_p2;
wire   [0:0] top_15_fu_200_p3;
wire   [31:0] xor_ln20_8_fu_214_p2;
wire   [31:0] crc_48_fu_220_p3;
wire   [31:0] crc_49_fu_236_p2;
wire   [0:0] top_16_fu_228_p3;
wire   [31:0] crc_50_fu_242_p2;
wire   [31:0] crc_51_fu_248_p3;
wire   [31:0] crc_52_fu_264_p2;
wire   [0:0] top_17_fu_256_p3;
wire   [31:0] xor_ln20_10_fu_270_p2;
wire   [31:0] crc_53_fu_276_p3;
wire   [31:0] crc_54_fu_292_p2;
wire   [0:0] top_18_fu_284_p3;
wire   [31:0] crc_55_fu_298_p2;
wire   [31:0] crc_56_fu_304_p3;
wire   [31:0] crc_57_fu_320_p2;
wire   [0:0] top_19_fu_312_p3;
wire   [31:0] xor_ln20_fu_326_p2;
wire   [31:0] crc_58_fu_332_p3;
wire   [31:0] crc_59_fu_348_p2;
wire   [0:0] top_20_fu_340_p3;
wire   [31:0] crc_60_fu_354_p2;
wire   [31:0] crc_61_fu_360_p3;
wire   [31:0] crc_62_fu_376_p2;
wire   [0:0] top_21_fu_368_p3;
wire   [31:0] xor_ln20_12_fu_382_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_340;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 crc_22_fu_60 = 32'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 i_fu_64 = 2'd0;
#0 ap_done_reg = 1'b0;
end

ofdm_mac_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_340)) begin
        if ((ap_loop_init == 1'b1)) begin
            crc_22_fu_60 <= crc_reload;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            crc_22_fu_60 <= crc_63_fu_388_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_111_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_64 <= i_5_fu_145_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 2'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_reg_423 <= b_fu_141_p1;
    end
end

always @ (*) begin
    if (((tmp_fu_111_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_4 = 2'd1;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_64;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (tmp_fu_111_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        crc_22_out_ap_vld = 1'b1;
    end else begin
        crc_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phy_tx_out_TDATA_blk_n = phy_tx_out_TREADY;
    end else begin
        phy_tx_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        phy_tx_out_TVALID = 1'b1;
    end else begin
        phy_tx_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((phy_tx_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((phy_tx_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((phy_tx_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((phy_tx_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_340 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_fu_141_p1 = lshr_ln136_fu_135_p2[7:0];

assign crc_22_out = crc_22_fu_60;

assign crc_43_fu_180_p2 = crc_fu_166_p2 << 32'd1;

assign crc_45_fu_186_p2 = (crc_43_fu_180_p2 ^ 32'd79764919);

assign crc_46_fu_192_p3 = ((top_fu_172_p3[0:0] == 1'b1) ? crc_45_fu_186_p2 : crc_43_fu_180_p2);

assign crc_47_fu_208_p2 = crc_46_fu_192_p3 << 32'd1;

assign crc_48_fu_220_p3 = ((top_15_fu_200_p3[0:0] == 1'b1) ? xor_ln20_8_fu_214_p2 : crc_47_fu_208_p2);

assign crc_49_fu_236_p2 = crc_48_fu_220_p3 << 32'd1;

assign crc_50_fu_242_p2 = (crc_49_fu_236_p2 ^ 32'd79764919);

assign crc_51_fu_248_p3 = ((top_16_fu_228_p3[0:0] == 1'b1) ? crc_50_fu_242_p2 : crc_49_fu_236_p2);

assign crc_52_fu_264_p2 = crc_51_fu_248_p3 << 32'd1;

assign crc_53_fu_276_p3 = ((top_17_fu_256_p3[0:0] == 1'b1) ? xor_ln20_10_fu_270_p2 : crc_52_fu_264_p2);

assign crc_54_fu_292_p2 = crc_53_fu_276_p3 << 32'd1;

assign crc_55_fu_298_p2 = (crc_54_fu_292_p2 ^ 32'd79764919);

assign crc_56_fu_304_p3 = ((top_18_fu_284_p3[0:0] == 1'b1) ? crc_55_fu_298_p2 : crc_54_fu_292_p2);

assign crc_57_fu_320_p2 = crc_56_fu_304_p3 << 32'd1;

assign crc_58_fu_332_p3 = ((top_19_fu_312_p3[0:0] == 1'b1) ? xor_ln20_fu_326_p2 : crc_57_fu_320_p2);

assign crc_59_fu_348_p2 = crc_58_fu_332_p3 << 32'd1;

assign crc_60_fu_354_p2 = (crc_59_fu_348_p2 ^ 32'd79764919);

assign crc_61_fu_360_p3 = ((top_20_fu_340_p3[0:0] == 1'b1) ? crc_60_fu_354_p2 : crc_59_fu_348_p2);

assign crc_62_fu_376_p2 = crc_61_fu_360_p3 << 32'd1;

assign crc_63_fu_388_p3 = ((top_21_fu_368_p3[0:0] == 1'b1) ? xor_ln20_12_fu_382_p2 : crc_62_fu_376_p2);

assign crc_fu_166_p2 = (shl_ln15_1_fu_159_p3 ^ crc_22_fu_60);

assign i_5_fu_145_p2 = ($signed(ap_sig_allocacmp_i_4) + $signed(2'd3));

assign lshr_ln136_fu_135_p2 = zext_ln120_cast_fu_94_p1 >> zext_ln136_fu_131_p1;

assign phy_tx_out_TDATA = b_reg_423;

assign shl_ln15_1_fu_159_p3 = {{b_reg_423}, {24'd0}};

assign shl_ln3_fu_123_p3 = {{trunc_ln136_fu_119_p1}, {3'd0}};

assign tmp_fu_111_p3 = ap_sig_allocacmp_i_4[32'd1];

assign top_15_fu_200_p3 = crc_46_fu_192_p3[32'd31];

assign top_16_fu_228_p3 = crc_48_fu_220_p3[32'd31];

assign top_17_fu_256_p3 = crc_51_fu_248_p3[32'd31];

assign top_18_fu_284_p3 = crc_53_fu_276_p3[32'd31];

assign top_19_fu_312_p3 = crc_56_fu_304_p3[32'd31];

assign top_20_fu_340_p3 = crc_58_fu_332_p3[32'd31];

assign top_21_fu_368_p3 = crc_61_fu_360_p3[32'd31];

assign top_fu_172_p3 = crc_fu_166_p2[32'd31];

assign trunc_ln136_fu_119_p1 = ap_sig_allocacmp_i_4[0:0];

assign xor_ln20_10_fu_270_p2 = (crc_52_fu_264_p2 ^ 32'd79764919);

assign xor_ln20_12_fu_382_p2 = (crc_62_fu_376_p2 ^ 32'd79764919);

assign xor_ln20_8_fu_214_p2 = (crc_47_fu_208_p2 ^ 32'd79764919);

assign xor_ln20_fu_326_p2 = (crc_57_fu_320_p2 ^ 32'd79764919);

assign zext_ln120_cast_fu_94_p1 = zext_ln120;

assign zext_ln136_fu_131_p1 = shl_ln3_fu_123_p3;

endmodule //ofdm_mac_do_tx_Pipeline_HDR_LEN
