// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module ofdm_mac_do_tx (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        first_byte_seen,
        first_was_last,
        host_tx_in_TDATA,
        host_tx_in_TVALID,
        host_tx_in_TREADY,
        host_tx_in_TKEEP,
        host_tx_in_TSTRB,
        host_tx_in_TLAST,
        phy_tx_out_TDATA,
        phy_tx_out_TVALID,
        phy_tx_out_TREADY,
        m_axi_csr_master_0_AWVALID,
        m_axi_csr_master_0_AWREADY,
        m_axi_csr_master_0_AWADDR,
        m_axi_csr_master_0_AWID,
        m_axi_csr_master_0_AWLEN,
        m_axi_csr_master_0_AWSIZE,
        m_axi_csr_master_0_AWBURST,
        m_axi_csr_master_0_AWLOCK,
        m_axi_csr_master_0_AWCACHE,
        m_axi_csr_master_0_AWPROT,
        m_axi_csr_master_0_AWQOS,
        m_axi_csr_master_0_AWREGION,
        m_axi_csr_master_0_AWUSER,
        m_axi_csr_master_0_WVALID,
        m_axi_csr_master_0_WREADY,
        m_axi_csr_master_0_WDATA,
        m_axi_csr_master_0_WSTRB,
        m_axi_csr_master_0_WLAST,
        m_axi_csr_master_0_WID,
        m_axi_csr_master_0_WUSER,
        m_axi_csr_master_0_ARVALID,
        m_axi_csr_master_0_ARREADY,
        m_axi_csr_master_0_ARADDR,
        m_axi_csr_master_0_ARID,
        m_axi_csr_master_0_ARLEN,
        m_axi_csr_master_0_ARSIZE,
        m_axi_csr_master_0_ARBURST,
        m_axi_csr_master_0_ARLOCK,
        m_axi_csr_master_0_ARCACHE,
        m_axi_csr_master_0_ARPROT,
        m_axi_csr_master_0_ARQOS,
        m_axi_csr_master_0_ARREGION,
        m_axi_csr_master_0_ARUSER,
        m_axi_csr_master_0_RVALID,
        m_axi_csr_master_0_RREADY,
        m_axi_csr_master_0_RDATA,
        m_axi_csr_master_0_RLAST,
        m_axi_csr_master_0_RID,
        m_axi_csr_master_0_RFIFONUM,
        m_axi_csr_master_0_RUSER,
        m_axi_csr_master_0_RRESP,
        m_axi_csr_master_0_BVALID,
        m_axi_csr_master_0_BREADY,
        m_axi_csr_master_0_BRESP,
        m_axi_csr_master_0_BID,
        m_axi_csr_master_0_BUSER,
        phy_csr,
        my_mac_addr,
        modcod,
        tx_pkt_count_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] first_byte_seen;
input  [0:0] first_was_last;
input  [7:0] host_tx_in_TDATA;
input   host_tx_in_TVALID;
output   host_tx_in_TREADY;
input  [0:0] host_tx_in_TKEEP;
input  [0:0] host_tx_in_TSTRB;
input  [0:0] host_tx_in_TLAST;
output  [7:0] phy_tx_out_TDATA;
output   phy_tx_out_TVALID;
input   phy_tx_out_TREADY;
output   m_axi_csr_master_0_AWVALID;
input   m_axi_csr_master_0_AWREADY;
output  [63:0] m_axi_csr_master_0_AWADDR;
output  [0:0] m_axi_csr_master_0_AWID;
output  [31:0] m_axi_csr_master_0_AWLEN;
output  [2:0] m_axi_csr_master_0_AWSIZE;
output  [1:0] m_axi_csr_master_0_AWBURST;
output  [1:0] m_axi_csr_master_0_AWLOCK;
output  [3:0] m_axi_csr_master_0_AWCACHE;
output  [2:0] m_axi_csr_master_0_AWPROT;
output  [3:0] m_axi_csr_master_0_AWQOS;
output  [3:0] m_axi_csr_master_0_AWREGION;
output  [0:0] m_axi_csr_master_0_AWUSER;
output   m_axi_csr_master_0_WVALID;
input   m_axi_csr_master_0_WREADY;
output  [31:0] m_axi_csr_master_0_WDATA;
output  [3:0] m_axi_csr_master_0_WSTRB;
output   m_axi_csr_master_0_WLAST;
output  [0:0] m_axi_csr_master_0_WID;
output  [0:0] m_axi_csr_master_0_WUSER;
output   m_axi_csr_master_0_ARVALID;
input   m_axi_csr_master_0_ARREADY;
output  [63:0] m_axi_csr_master_0_ARADDR;
output  [0:0] m_axi_csr_master_0_ARID;
output  [31:0] m_axi_csr_master_0_ARLEN;
output  [2:0] m_axi_csr_master_0_ARSIZE;
output  [1:0] m_axi_csr_master_0_ARBURST;
output  [1:0] m_axi_csr_master_0_ARLOCK;
output  [3:0] m_axi_csr_master_0_ARCACHE;
output  [2:0] m_axi_csr_master_0_ARPROT;
output  [3:0] m_axi_csr_master_0_ARQOS;
output  [3:0] m_axi_csr_master_0_ARREGION;
output  [0:0] m_axi_csr_master_0_ARUSER;
input   m_axi_csr_master_0_RVALID;
output   m_axi_csr_master_0_RREADY;
input  [31:0] m_axi_csr_master_0_RDATA;
input   m_axi_csr_master_0_RLAST;
input  [0:0] m_axi_csr_master_0_RID;
input  [1:0] m_axi_csr_master_0_RFIFONUM;
input  [0:0] m_axi_csr_master_0_RUSER;
input  [1:0] m_axi_csr_master_0_RRESP;
input   m_axi_csr_master_0_BVALID;
output   m_axi_csr_master_0_BREADY;
input  [1:0] m_axi_csr_master_0_BRESP;
input  [0:0] m_axi_csr_master_0_BID;
input  [0:0] m_axi_csr_master_0_BUSER;
input  [63:0] phy_csr;
input  [47:0] my_mac_addr;
input  [1:0] modcod;
input  [31:0] tx_pkt_count_read;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg host_tx_in_TREADY;
reg[7:0] phy_tx_out_TDATA;
reg phy_tx_out_TVALID;
reg m_axi_csr_master_0_AWVALID;
reg[63:0] m_axi_csr_master_0_AWADDR;
reg m_axi_csr_master_0_WVALID;
reg[31:0] m_axi_csr_master_0_WDATA;
reg m_axi_csr_master_0_BREADY;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [11:0] buf_r_address0;
reg    buf_r_ce0;
reg    buf_r_we0;
reg   [7:0] buf_r_d0;
wire   [7:0] buf_r_q0;
reg    csr_master_blk_n_AW;
wire    ap_CS_fsm_state16;
reg    csr_master_blk_n_W;
wire    ap_CS_fsm_state17;
reg    csr_master_blk_n_B;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
wire   [12:0] n_data_bytes_fu_290_p2;
reg   [12:0] n_data_bytes_reg_610;
wire   [6:0] bps_fu_296_p11;
reg   [6:0] bps_reg_616;
wire   [6:0] add_ln108_fu_320_p2;
reg   [6:0] add_ln108_reg_621;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state15;
reg   [63:0] csr_master_addr_reg_651;
reg   [63:0] csr_master_addr_5_reg_658;
reg   [63:0] csr_master_addr_1_reg_665;
reg   [63:0] csr_master_addr_2_reg_672;
wire   [31:0] zext_ln107_fu_451_p1;
reg   [31:0] zext_ln107_reg_679;
reg   [63:0] csr_master_addr_3_reg_684;
reg   [63:0] csr_master_addr_4_reg_691;
reg   [63:0] csr_master_addr_6_reg_698;
wire   [7:0] n_syms_2_fu_540_p3;
reg   [7:0] n_syms_2_reg_705;
wire   [31:0] zext_ln55_fu_548_p1;
reg   [31:0] zext_ln55_reg_710;
wire   [31:0] fcs_fu_555_p2;
reg   [31:0] fcs_reg_715;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_ap_start;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_ap_done;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_ap_idle;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_ap_ready;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_host_tx_in_TREADY;
wire   [12:0] grp_do_tx_Pipeline_ABSORB_fu_228_plen_out;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_plen_out_ap_vld;
wire   [11:0] grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_address0;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_ce0;
wire    grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_we0;
wire   [7:0] grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_d0;
wire    grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start;
wire    grp_do_tx_Pipeline_HDR_DST_fu_245_ap_done;
wire    grp_do_tx_Pipeline_HDR_DST_fu_245_ap_idle;
wire    grp_do_tx_Pipeline_HDR_DST_fu_245_ap_ready;
wire    grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TREADY;
wire   [7:0] grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TDATA;
wire    grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TVALID;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_done;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_idle;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_ready;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TREADY;
wire   [7:0] grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TDATA;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TVALID;
wire   [31:0] grp_do_tx_Pipeline_HDR_SRC_fu_251_crc_out;
wire    grp_do_tx_Pipeline_HDR_SRC_fu_251_crc_out_ap_vld;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_done;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_idle;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_ready;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TREADY;
wire   [7:0] grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TDATA;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TVALID;
wire   [31:0] grp_do_tx_Pipeline_HDR_LEN_fu_260_crc_22_out;
wire    grp_do_tx_Pipeline_HDR_LEN_fu_260_crc_22_out_ap_vld;
wire    grp_do_tx_Pipeline_PAY_fu_269_ap_start;
wire    grp_do_tx_Pipeline_PAY_fu_269_ap_done;
wire    grp_do_tx_Pipeline_PAY_fu_269_ap_idle;
wire    grp_do_tx_Pipeline_PAY_fu_269_ap_ready;
wire    grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TREADY;
wire   [7:0] grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TDATA;
wire    grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TVALID;
wire   [31:0] grp_do_tx_Pipeline_PAY_fu_269_crc_34_out;
wire    grp_do_tx_Pipeline_PAY_fu_269_crc_34_out_ap_vld;
wire   [11:0] grp_do_tx_Pipeline_PAY_fu_269_buf_r_address0;
wire    grp_do_tx_Pipeline_PAY_fu_269_buf_r_ce0;
wire    grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start;
wire    grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done;
wire    grp_do_tx_Pipeline_FCS_TX_fu_280_ap_idle;
wire    grp_do_tx_Pipeline_FCS_TX_fu_280_ap_ready;
wire    grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TREADY;
wire   [7:0] grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TDATA;
wire    grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TVALID;
reg    grp_do_tx_Pipeline_ABSORB_fu_228_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    buf_r_we0_out;
reg    grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start_reg;
reg   [7:0] phy_tx_out_TDATA_reg;
reg    grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start_reg;
reg    grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_do_tx_Pipeline_PAY_fu_269_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start_reg;
wire  signed [63:0] sext_ln36_fu_367_p1;
wire  signed [63:0] sext_ln36_5_fu_387_p1;
wire  signed [63:0] sext_ln36_1_fu_412_p1;
wire  signed [63:0] sext_ln36_2_fu_441_p1;
wire  signed [63:0] sext_ln36_3_fu_470_p1;
wire  signed [63:0] sext_ln36_4_fu_495_p1;
wire  signed [63:0] sext_ln36_6_fu_520_p1;
reg    ap_block_state17_io;
reg    ap_block_state18_io;
reg    ap_block_state22_io;
wire   [31:0] zext_ln53_fu_422_p1;
reg    buf_r_we0_local;
reg    buf_r_ce0_local;
wire   [6:0] bps_fu_296_p9;
wire   [12:0] zext_ln108_1_fu_329_p1;
wire   [12:0] grp_fu_337_p0;
wire   [6:0] grp_fu_337_p1;
wire   [63:0] add_ln36_fu_351_p2;
wire   [61:0] trunc_ln_fu_357_p4;
wire   [61:0] trunc_ln36_5_fu_377_p4;
wire   [63:0] add_ln36_1_fu_397_p2;
wire   [61:0] trunc_ln36_1_fu_402_p4;
wire   [63:0] add_ln36_2_fu_426_p2;
wire   [61:0] trunc_ln36_2_fu_431_p4;
wire   [63:0] add_ln36_3_fu_455_p2;
wire   [61:0] trunc_ln36_3_fu_460_p4;
wire   [63:0] add_ln36_4_fu_480_p2;
wire   [61:0] trunc_ln36_4_fu_485_p4;
wire   [63:0] add_ln36_5_fu_505_p2;
wire   [61:0] trunc_ln36_6_fu_510_p4;
wire   [7:0] grp_fu_337_p2;
wire   [7:0] n_syms_fu_530_p1;
wire   [0:0] icmp_ln109_fu_534_p2;
reg    grp_fu_337_ap_start;
wire    grp_fu_337_ap_done;
reg    grp_fu_337_ce;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [31:0] add_ln160_fu_562_p2;
reg   [31:0] ap_return_preg;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire   [12:0] grp_fu_337_p10;
wire   [1:0] bps_fu_296_p1;
wire   [1:0] bps_fu_296_p3;
wire  signed [1:0] bps_fu_296_p5;
wire  signed [1:0] bps_fu_296_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_do_tx_Pipeline_ABSORB_fu_228_ap_start_reg = 1'b0;
#0 grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start_reg = 1'b0;
#0 grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start_reg = 1'b0;
#0 grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start_reg = 1'b0;
#0 grp_do_tx_Pipeline_PAY_fu_269_ap_start_reg = 1'b0;
#0 grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start_reg = 1'b0;
#0 ap_return_preg = 32'd0;
end

ofdm_mac_do_tx_buf_r_RAM_1P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
buf_r_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_r_address0),
    .ce0(buf_r_ce0),
    .we0(buf_r_we0),
    .d0(buf_r_d0),
    .q0(buf_r_q0)
);

ofdm_mac_do_tx_Pipeline_ABSORB grp_do_tx_Pipeline_ABSORB_fu_228(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_tx_Pipeline_ABSORB_fu_228_ap_start),
    .ap_done(grp_do_tx_Pipeline_ABSORB_fu_228_ap_done),
    .ap_idle(grp_do_tx_Pipeline_ABSORB_fu_228_ap_idle),
    .ap_ready(grp_do_tx_Pipeline_ABSORB_fu_228_ap_ready),
    .host_tx_in_TVALID(host_tx_in_TVALID),
    .first_was_last(first_was_last),
    .host_tx_in_TDATA(host_tx_in_TDATA),
    .host_tx_in_TREADY(grp_do_tx_Pipeline_ABSORB_fu_228_host_tx_in_TREADY),
    .host_tx_in_TKEEP(host_tx_in_TKEEP),
    .host_tx_in_TSTRB(host_tx_in_TSTRB),
    .host_tx_in_TLAST(host_tx_in_TLAST),
    .plen_out(grp_do_tx_Pipeline_ABSORB_fu_228_plen_out),
    .plen_out_ap_vld(grp_do_tx_Pipeline_ABSORB_fu_228_plen_out_ap_vld),
    .buf_r_address0(grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_address0),
    .buf_r_ce0(grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_ce0),
    .buf_r_we0(grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_we0),
    .buf_r_d0(grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_d0)
);

ofdm_mac_do_tx_Pipeline_HDR_DST grp_do_tx_Pipeline_HDR_DST_fu_245(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start),
    .ap_done(grp_do_tx_Pipeline_HDR_DST_fu_245_ap_done),
    .ap_idle(grp_do_tx_Pipeline_HDR_DST_fu_245_ap_idle),
    .ap_ready(grp_do_tx_Pipeline_HDR_DST_fu_245_ap_ready),
    .phy_tx_out_TREADY(grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TREADY),
    .phy_tx_out_TDATA(grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TDATA),
    .phy_tx_out_TVALID(grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TVALID)
);

ofdm_mac_do_tx_Pipeline_HDR_SRC grp_do_tx_Pipeline_HDR_SRC_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start),
    .ap_done(grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_done),
    .ap_idle(grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_idle),
    .ap_ready(grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_ready),
    .phy_tx_out_TREADY(grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TREADY),
    .my_mac_addr(my_mac_addr),
    .phy_tx_out_TDATA(grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TDATA),
    .phy_tx_out_TVALID(grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TVALID),
    .crc_out(grp_do_tx_Pipeline_HDR_SRC_fu_251_crc_out),
    .crc_out_ap_vld(grp_do_tx_Pipeline_HDR_SRC_fu_251_crc_out_ap_vld)
);

ofdm_mac_do_tx_Pipeline_HDR_LEN grp_do_tx_Pipeline_HDR_LEN_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start),
    .ap_done(grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_done),
    .ap_idle(grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_idle),
    .ap_ready(grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_ready),
    .phy_tx_out_TREADY(grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TREADY),
    .crc_reload(grp_do_tx_Pipeline_HDR_SRC_fu_251_crc_out),
    .zext_ln120(grp_do_tx_Pipeline_ABSORB_fu_228_plen_out),
    .phy_tx_out_TDATA(grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TDATA),
    .phy_tx_out_TVALID(grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TVALID),
    .crc_22_out(grp_do_tx_Pipeline_HDR_LEN_fu_260_crc_22_out),
    .crc_22_out_ap_vld(grp_do_tx_Pipeline_HDR_LEN_fu_260_crc_22_out_ap_vld)
);

ofdm_mac_do_tx_Pipeline_PAY grp_do_tx_Pipeline_PAY_fu_269(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_tx_Pipeline_PAY_fu_269_ap_start),
    .ap_done(grp_do_tx_Pipeline_PAY_fu_269_ap_done),
    .ap_idle(grp_do_tx_Pipeline_PAY_fu_269_ap_idle),
    .ap_ready(grp_do_tx_Pipeline_PAY_fu_269_ap_ready),
    .phy_tx_out_TREADY(grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TREADY),
    .crc_22_reload(grp_do_tx_Pipeline_HDR_LEN_fu_260_crc_22_out),
    .plen_reload(grp_do_tx_Pipeline_ABSORB_fu_228_plen_out),
    .phy_tx_out_TDATA(grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TDATA),
    .phy_tx_out_TVALID(grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TVALID),
    .crc_34_out(grp_do_tx_Pipeline_PAY_fu_269_crc_34_out),
    .crc_34_out_ap_vld(grp_do_tx_Pipeline_PAY_fu_269_crc_34_out_ap_vld),
    .buf_r_address0(grp_do_tx_Pipeline_PAY_fu_269_buf_r_address0),
    .buf_r_ce0(grp_do_tx_Pipeline_PAY_fu_269_buf_r_ce0),
    .buf_r_q0(buf_r_q0)
);

ofdm_mac_do_tx_Pipeline_FCS_TX grp_do_tx_Pipeline_FCS_TX_fu_280(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start),
    .ap_done(grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done),
    .ap_idle(grp_do_tx_Pipeline_FCS_TX_fu_280_ap_idle),
    .ap_ready(grp_do_tx_Pipeline_FCS_TX_fu_280_ap_ready),
    .phy_tx_out_TREADY(grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TREADY),
    .fcs(fcs_reg_715),
    .phy_tx_out_TDATA(grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TDATA),
    .phy_tx_out_TVALID(grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TVALID)
);

(* dissolve_hierarchy = "yes" *) ofdm_mac_sparsemux_9_2_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 7 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 7 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 7 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
sparsemux_9_2_7_1_1_U56(
    .din0(7'd25),
    .din1(7'd33),
    .din2(7'd50),
    .din3(7'd66),
    .def(bps_fu_296_p9),
    .sel(modcod),
    .dout(bps_fu_296_p11)
);

ofdm_mac_udiv_13ns_7ns_8_17_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 17 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 8 ))
udiv_13ns_7ns_8_17_seq_1_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_337_ap_start),
    .done(grp_fu_337_ap_done),
    .din0(grp_fu_337_p0),
    .din1(grp_fu_337_p1),
    .ce(grp_fu_337_ce),
    .dout(grp_fu_337_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if ((~((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state31))) begin
            ap_return_preg <= add_ln160_fu_562_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_tx_Pipeline_ABSORB_fu_228_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_do_tx_Pipeline_ABSORB_fu_228_ap_start_reg <= 1'b1;
        end else if ((grp_do_tx_Pipeline_ABSORB_fu_228_ap_ready == 1'b1)) begin
            grp_do_tx_Pipeline_ABSORB_fu_228_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state30) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
            grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start_reg <= 1'b1;
        end else if ((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_ready == 1'b1)) begin
            grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start_reg <= 1'b1;
        end else if ((grp_do_tx_Pipeline_HDR_DST_fu_245_ap_ready == 1'b1)) begin
            grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_ready == 1'b1)) begin
            grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start_reg <= 1'b1;
        end else if ((grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_ready == 1'b1)) begin
            grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_do_tx_Pipeline_PAY_fu_269_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_do_tx_Pipeline_PAY_fu_269_ap_start_reg <= 1'b1;
        end else if ((grp_do_tx_Pipeline_PAY_fu_269_ap_ready == 1'b1)) begin
            grp_do_tx_Pipeline_PAY_fu_269_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
        phy_tx_out_TDATA_reg <= grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        phy_tx_out_TDATA_reg <= grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        phy_tx_out_TDATA_reg <= grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        phy_tx_out_TDATA_reg <= grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        phy_tx_out_TDATA_reg <= grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln108_reg_621 <= add_ln108_fu_320_p2;
        bps_reg_616 <= bps_fu_296_p11;
        n_data_bytes_reg_610 <= n_data_bytes_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        csr_master_addr_1_reg_665 <= sext_ln36_1_fu_412_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        csr_master_addr_2_reg_672 <= sext_ln36_2_fu_441_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        csr_master_addr_3_reg_684 <= sext_ln36_3_fu_470_p1;
        zext_ln107_reg_679[1 : 0] <= zext_ln107_fu_451_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        csr_master_addr_4_reg_691 <= sext_ln36_4_fu_495_p1;
        csr_master_addr_6_reg_698 <= sext_ln36_6_fu_520_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        csr_master_addr_5_reg_658 <= sext_ln36_5_fu_387_p1;
        csr_master_addr_reg_651 <= sext_ln36_fu_367_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        fcs_reg_715 <= fcs_fu_555_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        n_syms_2_reg_705 <= n_syms_2_fu_540_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        zext_ln55_reg_710[7 : 0] <= zext_ln55_fu_548_p1[7 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((m_axi_csr_master_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state17_io)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state18_io)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state22_io) | (m_axi_csr_master_0_BVALID == 1'b0))) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0))) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

always @ (*) begin
    if ((m_axi_csr_master_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((m_axi_csr_master_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0))) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_do_tx_Pipeline_PAY_fu_269_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((~((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state31)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_return = add_ln160_fu_562_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_r_address0 = grp_do_tx_Pipeline_PAY_fu_269_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_r_address0 = grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_address0;
    end else begin
        buf_r_address0 = 12'd0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_r_ce0 = grp_do_tx_Pipeline_PAY_fu_269_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_r_ce0 = grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_ce0;
    end else begin
        buf_r_ce0 = buf_r_ce0_local;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_r_ce0_local = 1'b1;
    end else begin
        buf_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_r_d0 = grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_d0;
    end else begin
        buf_r_d0 = first_byte_seen;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_r_we0 = grp_do_tx_Pipeline_ABSORB_fu_228_buf_r_we0;
    end else begin
        buf_r_we0 = (buf_r_we0_out | 1'b0);
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        buf_r_we0_local = 1'b1;
    end else begin
        buf_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        csr_master_blk_n_AW = m_axi_csr_master_0_AWREADY;
    end else begin
        csr_master_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        csr_master_blk_n_B = m_axi_csr_master_0_BVALID;
    end else begin
        csr_master_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state17))) begin
        csr_master_blk_n_W = m_axi_csr_master_0_WREADY;
    end else begin
        csr_master_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        grp_fu_337_ap_start = 1'b1;
    end else begin
        grp_fu_337_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16))) begin
        grp_fu_337_ce = 1'b1;
    end else begin
        grp_fu_337_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        host_tx_in_TREADY = grp_do_tx_Pipeline_ABSORB_fu_228_host_tx_in_TREADY;
    end else begin
        host_tx_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state22_io) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state22))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_6_reg_698;
    end else if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_5_reg_658;
    end else if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_4_reg_691;
    end else if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_3_reg_684;
    end else if (((1'b0 == ap_block_state18_io) & (1'b1 == ap_CS_fsm_state18))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_2_reg_672;
    end else if (((1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_1_reg_665;
    end else if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        m_axi_csr_master_0_AWADDR = csr_master_addr_reg_651;
    end else begin
        m_axi_csr_master_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state22_io) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state22)) | ((1'b0 == ap_block_state18_io) & (1'b1 == ap_CS_fsm_state18)) | ((1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17)) | ((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21)) | ((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | ((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16)))) begin
        m_axi_csr_master_0_AWVALID = 1'b1;
    end else begin
        m_axi_csr_master_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((~((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state31)) | (~((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state23)) | (~((1'b1 == ap_block_state22_io) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state22)) | ((1'b1 == ap_CS_fsm_state30) & (m_axi_csr_master_0_BVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state29) & (m_axi_csr_master_0_BVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state28) & (m_axi_csr_master_0_BVALID == 1'b1)) | ((1'b1 == ap_CS_fsm_state27) & (m_axi_csr_master_0_BVALID == 1'b1)))) begin
        m_axi_csr_master_0_BREADY = 1'b1;
    end else begin
        m_axi_csr_master_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25))) begin
        m_axi_csr_master_0_WDATA = 32'd1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        m_axi_csr_master_0_WDATA = zext_ln55_reg_710;
    end else if (((1'b1 == ap_CS_fsm_state23) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
        m_axi_csr_master_0_WDATA = zext_ln107_reg_679;
    end else if (((1'b1 == ap_CS_fsm_state22) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
        m_axi_csr_master_0_WDATA = zext_ln55_fu_548_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        m_axi_csr_master_0_WDATA = zext_ln107_fu_451_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        m_axi_csr_master_0_WDATA = zext_ln53_fu_422_p1;
    end else begin
        m_axi_csr_master_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((m_axi_csr_master_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26)) | ((m_axi_csr_master_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25)) | ((m_axi_csr_master_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state24)) | (~((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state23)) | (~((1'b1 == ap_block_state22_io) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state22)) | ((1'b0 == ap_block_state18_io) & (1'b1 == ap_CS_fsm_state18)) | ((1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17)))) begin
        m_axi_csr_master_0_WVALID = 1'b1;
    end else begin
        m_axi_csr_master_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
        phy_tx_out_TDATA = grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        phy_tx_out_TDATA = grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        phy_tx_out_TDATA = grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        phy_tx_out_TDATA = grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TDATA;
    end else if (((grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        phy_tx_out_TDATA = grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TDATA;
    end else begin
        phy_tx_out_TDATA = phy_tx_out_TDATA_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        phy_tx_out_TVALID = grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        phy_tx_out_TVALID = grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        phy_tx_out_TVALID = grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        phy_tx_out_TVALID = grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TVALID;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        phy_tx_out_TVALID = grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TVALID;
    end else begin
        phy_tx_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_do_tx_Pipeline_PAY_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((1'b0 == ap_block_state17_io) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_io) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((m_axi_csr_master_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            if ((~((1'b1 == ap_block_state22_io) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            if ((~((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((m_axi_csr_master_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((m_axi_csr_master_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((m_axi_csr_master_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == ap_CS_fsm_state27) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((1'b1 == ap_CS_fsm_state28) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((1'b1 == ap_CS_fsm_state29) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            if (((1'b1 == ap_CS_fsm_state30) & (m_axi_csr_master_0_BVALID == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            if ((~((grp_do_tx_Pipeline_FCS_TX_fu_280_ap_done == 1'b0) | (m_axi_csr_master_0_BVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln108_fu_320_p2 = ($signed(bps_fu_296_p11) + $signed(7'd127));

assign add_ln160_fu_562_p2 = (tx_pkt_count_read + 32'd1);

assign add_ln36_1_fu_397_p2 = (phy_csr + 64'd24);

assign add_ln36_2_fu_426_p2 = (phy_csr + 64'd32);

assign add_ln36_3_fu_455_p2 = (phy_csr + 64'd4112);

assign add_ln36_4_fu_480_p2 = (phy_csr + 64'd4120);

assign add_ln36_5_fu_505_p2 = (phy_csr + 64'd4096);

assign add_ln36_fu_351_p2 = (phy_csr + 64'd16);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state17_io = ((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state18_io = ((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state22_io = ((m_axi_csr_master_0_WREADY == 1'b0) | (m_axi_csr_master_0_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_do_tx_Pipeline_HDR_DST_fu_245_ap_done == 1'b0) | (grp_do_tx_Pipeline_ABSORB_fu_228_ap_done == 1'b0));
end

assign bps_fu_296_p9 = 'bx;

assign buf_r_we0_out = buf_r_we0_local;

assign fcs_fu_555_p2 = (grp_do_tx_Pipeline_PAY_fu_269_crc_34_out ^ 32'd4294967295);

assign grp_do_tx_Pipeline_ABSORB_fu_228_ap_start = grp_do_tx_Pipeline_ABSORB_fu_228_ap_start_reg;

assign grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start = grp_do_tx_Pipeline_FCS_TX_fu_280_ap_start_reg;

assign grp_do_tx_Pipeline_FCS_TX_fu_280_phy_tx_out_TREADY = (phy_tx_out_TREADY & ap_CS_fsm_state31);

assign grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start = grp_do_tx_Pipeline_HDR_DST_fu_245_ap_start_reg;

assign grp_do_tx_Pipeline_HDR_DST_fu_245_phy_tx_out_TREADY = (phy_tx_out_TREADY & ap_CS_fsm_state3);

assign grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start = grp_do_tx_Pipeline_HDR_LEN_fu_260_ap_start_reg;

assign grp_do_tx_Pipeline_HDR_LEN_fu_260_phy_tx_out_TREADY = (phy_tx_out_TREADY & ap_CS_fsm_state7);

assign grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start = grp_do_tx_Pipeline_HDR_SRC_fu_251_ap_start_reg;

assign grp_do_tx_Pipeline_HDR_SRC_fu_251_phy_tx_out_TREADY = (phy_tx_out_TREADY & ap_CS_fsm_state5);

assign grp_do_tx_Pipeline_PAY_fu_269_ap_start = grp_do_tx_Pipeline_PAY_fu_269_ap_start_reg;

assign grp_do_tx_Pipeline_PAY_fu_269_phy_tx_out_TREADY = (phy_tx_out_TREADY & ap_CS_fsm_state9);

assign grp_fu_337_p0 = (zext_ln108_1_fu_329_p1 + n_data_bytes_reg_610);

assign grp_fu_337_p1 = grp_fu_337_p10;

assign grp_fu_337_p10 = bps_reg_616;

assign icmp_ln109_fu_534_p2 = ((n_syms_fu_530_p1 == 8'd0) ? 1'b1 : 1'b0);

assign m_axi_csr_master_0_ARADDR = 64'd0;

assign m_axi_csr_master_0_ARBURST = 2'd0;

assign m_axi_csr_master_0_ARCACHE = 4'd0;

assign m_axi_csr_master_0_ARID = 1'd0;

assign m_axi_csr_master_0_ARLEN = 32'd0;

assign m_axi_csr_master_0_ARLOCK = 2'd0;

assign m_axi_csr_master_0_ARPROT = 3'd0;

assign m_axi_csr_master_0_ARQOS = 4'd0;

assign m_axi_csr_master_0_ARREGION = 4'd0;

assign m_axi_csr_master_0_ARSIZE = 3'd0;

assign m_axi_csr_master_0_ARUSER = 1'd0;

assign m_axi_csr_master_0_ARVALID = 1'b0;

assign m_axi_csr_master_0_AWBURST = 2'd0;

assign m_axi_csr_master_0_AWCACHE = 4'd0;

assign m_axi_csr_master_0_AWID = 1'd0;

assign m_axi_csr_master_0_AWLEN = 64'd1;

assign m_axi_csr_master_0_AWLOCK = 2'd0;

assign m_axi_csr_master_0_AWPROT = 3'd0;

assign m_axi_csr_master_0_AWQOS = 4'd0;

assign m_axi_csr_master_0_AWREGION = 4'd0;

assign m_axi_csr_master_0_AWSIZE = 3'd0;

assign m_axi_csr_master_0_AWUSER = 1'd0;

assign m_axi_csr_master_0_RREADY = 1'b0;

assign m_axi_csr_master_0_WID = 1'd0;

assign m_axi_csr_master_0_WLAST = 1'b0;

assign m_axi_csr_master_0_WSTRB = 4'd15;

assign m_axi_csr_master_0_WUSER = 1'd0;

assign n_data_bytes_fu_290_p2 = (grp_do_tx_Pipeline_ABSORB_fu_228_plen_out + 13'd18);

assign n_syms_2_fu_540_p3 = ((icmp_ln109_fu_534_p2[0:0] == 1'b1) ? 8'd1 : n_syms_fu_530_p1);

assign n_syms_fu_530_p1 = grp_fu_337_p2[7:0];

assign sext_ln36_1_fu_412_p1 = $signed(trunc_ln36_1_fu_402_p4);

assign sext_ln36_2_fu_441_p1 = $signed(trunc_ln36_2_fu_431_p4);

assign sext_ln36_3_fu_470_p1 = $signed(trunc_ln36_3_fu_460_p4);

assign sext_ln36_4_fu_495_p1 = $signed(trunc_ln36_4_fu_485_p4);

assign sext_ln36_5_fu_387_p1 = $signed(trunc_ln36_5_fu_377_p4);

assign sext_ln36_6_fu_520_p1 = $signed(trunc_ln36_6_fu_510_p4);

assign sext_ln36_fu_367_p1 = $signed(trunc_ln_fu_357_p4);

assign trunc_ln36_1_fu_402_p4 = {{add_ln36_1_fu_397_p2[63:2]}};

assign trunc_ln36_2_fu_431_p4 = {{add_ln36_2_fu_426_p2[63:2]}};

assign trunc_ln36_3_fu_460_p4 = {{add_ln36_3_fu_455_p2[63:2]}};

assign trunc_ln36_4_fu_485_p4 = {{add_ln36_4_fu_480_p2[63:2]}};

assign trunc_ln36_5_fu_377_p4 = {{phy_csr[63:2]}};

assign trunc_ln36_6_fu_510_p4 = {{add_ln36_5_fu_505_p2[63:2]}};

assign trunc_ln_fu_357_p4 = {{add_ln36_fu_351_p2[63:2]}};

assign zext_ln107_fu_451_p1 = modcod;

assign zext_ln108_1_fu_329_p1 = add_ln108_reg_621;

assign zext_ln53_fu_422_p1 = n_data_bytes_reg_610;

assign zext_ln55_fu_548_p1 = n_syms_2_reg_705;

always @ (posedge ap_clk) begin
    zext_ln107_reg_679[31:2] <= 30'b000000000000000000000000000000;
    zext_ln55_reg_710[31:8] <= 24'b000000000000000000000000;
end

endmodule //ofdm_mac_do_tx
