// ============================================================
// ofdm_lut.h  —  Shared ROM tables and small helpers used by
//                ofdm_tx, ofdm_rx, and sync_detect.
//
// All static const arrays here are file-scope-static.  Each .cpp
// that includes this header gets its own private copy → HLS
// synthesises a per-module ROM, identical to having the table
// defined locally in the .cpp.
// ============================================================
#pragma once
#include "ofdm_tx.h"   // sample_t, NUM_DATA_SC, NUM_PILOT_SC, FFT_SIZE, ap_uint, ap_fixed

// ── Subcarrier index ROMs ────────────────────────────────────
static const int PILOT_IDX[NUM_PILOT_SC] = {50, 75, 100, 154, 179, 204};

// Precomputed data subcarrier indices → synthesizes as ROM.
// Using a ROM here (instead of runtime is_null/is_pilot checks) is what
// makes DATA_MAP achieve II=1: the address is known each cycle.
static const int DATA_SC_IDX[NUM_DATA_SC] = {
    // Positive half (bins 25–127, pilots at 50, 75, 100 excluded)
    25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,
    51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,
    76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,
    101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,
    120,121,122,123,124,125,126,127,
    // Negative half (bins 129–231, pilots at 154, 179, 204 excluded)
    129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,
    148,149,150,151,152,153,
    155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,
    174,175,176,177,178,
    180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,
    199,200,201,202,203,
    205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,
    224,225,226,227,228,229,230,231
};

// ── Zadoff-Chu preamble LUT ──────────────────────────────────
// Generated by sim/gen_zc_lut.py — root u=25, N=256.
// ZC_I_LUT[d] = Re(zc[DATA_SC_IDX[d]]),  ZC_Q_LUT[d] = Im(zc[DATA_SC_IDX[d]]).
// All magnitudes = 1.0 (constant-envelope → low PAPR for synchronisation).
// Used by ofdm_tx (preamble emission) and ofdm_rx (channel estimation).
static const sample_t ZC_I_LUT[NUM_DATA_SC] = {
    sample_t(-0.073565), sample_t(-0.170962), sample_t(0.857729), sample_t(-0.595699), sample_t(-0.992480), sample_t(-0.844854), sample_t(-0.923880), sample_t(-0.923880),
    sample_t(0.219101), sample_t(0.788346), sample_t(-0.989177), sample_t(0.970031), sample_t(-0.575808), sample_t(-0.653173), sample_t(0.471397), sample_t(0.881921),
    sample_t(0.870087), sample_t(0.405241), sample_t(-0.740951), sample_t(-0.427555), sample_t(0.893224), sample_t(-0.914210), sample_t(0.555570), sample_t(0.555570),
    sample_t(-0.689541), sample_t(-0.998795), sample_t(-0.903989), sample_t(-0.024541), sample_t(0.992480), sample_t(-0.773010), sample_t(0.634393), sample_t(-0.893224),
    sample_t(0.844854), sample_t(0.595699), sample_t(-0.242980), sample_t(-0.492898), sample_t(-0.170962), sample_t(0.707107), sample_t(0.707107), sample_t(-0.985278),
    sample_t(0.870087), sample_t(-0.970031), sample_t(0.803208), sample_t(0.534998), sample_t(-0.449611), sample_t(-0.773010), sample_t(-0.634393), sample_t(0.122411),
    sample_t(0.999699), sample_t(-0.049068), sample_t(-0.073565), sample_t(0.724247), sample_t(-0.831470), sample_t(-0.831470), sample_t(-0.405241), sample_t(-0.449611),
    sample_t(-0.903989), sample_t(-0.671559), sample_t(0.914210), sample_t(-0.492898), sample_t(0.471397), sample_t(-0.881921), sample_t(0.757209), sample_t(0.817585),
    sample_t(0.242980), sample_t(0.146730), sample_t(0.615232), sample_t(0.975702), sample_t(-0.382683), sample_t(-0.382683), sample_t(0.534998), sample_t(-0.122411),
    sample_t(-0.803208), sample_t(0.985278), sample_t(0.997290), sample_t(0.956940), sample_t(0.290285), sample_t(-0.963776), sample_t(0.359895), sample_t(-0.049068),
    sample_t(0.336890), sample_t(-0.949528), sample_t(0.359895), sample_t(0.980785), sample_t(0.980785), sample_t(0.999699), sample_t(0.653173), sample_t(-0.671559),
    sample_t(-0.336890), sample_t(0.724247), sample_t(-0.615232), sample_t(-0.098017), sample_t(0.995185), sample_t(0.313682), sample_t(-0.219101), sample_t(-0.146730),
    sample_t(0.514103), sample_t(0.963776), sample_t(-0.575808), sample_t(0.000000), sample_t(0.575808), sample_t(-0.963776), sample_t(-0.514103), sample_t(0.146730),
    sample_t(0.219101), sample_t(-0.313682), sample_t(-0.995185), sample_t(0.098017), sample_t(0.615232), sample_t(-0.724247), sample_t(0.336890), sample_t(0.671559),
    sample_t(-0.653173), sample_t(-0.999699), sample_t(-0.980785), sample_t(-0.980785), sample_t(-0.359895), sample_t(0.949528), sample_t(-0.336890), sample_t(0.049068),
    sample_t(-0.359895), sample_t(0.963776), sample_t(-0.290285), sample_t(-0.956940), sample_t(-0.997290), sample_t(-0.514103), sample_t(0.803208), sample_t(0.122411),
    sample_t(-0.534998), sample_t(0.382683), sample_t(0.382683), sample_t(-0.975702), sample_t(-0.615232), sample_t(-0.146730), sample_t(-0.242980), sample_t(-0.817585),
    sample_t(-0.757209), sample_t(0.881921), sample_t(-0.471397), sample_t(0.492898), sample_t(-0.914210), sample_t(0.671559), sample_t(0.903989), sample_t(0.449611),
    sample_t(0.405241), sample_t(0.831470), sample_t(0.831470), sample_t(-0.724247), sample_t(0.073565), sample_t(0.427555), sample_t(-0.999699), sample_t(-0.122411),
    sample_t(0.634393), sample_t(0.773010), sample_t(0.449611), sample_t(-0.534998), sample_t(-0.803208), sample_t(0.970031), sample_t(-0.870087), sample_t(0.985278),
    sample_t(-0.707107), sample_t(-0.707107), sample_t(0.170962), sample_t(0.492898), sample_t(0.242980), sample_t(-0.595699), sample_t(-0.844854), sample_t(0.893224),
    sample_t(-0.634393), sample_t(0.773010), sample_t(-0.992480), sample_t(0.024541), sample_t(0.903989), sample_t(0.997290), sample_t(0.689541), sample_t(-0.555570),
    sample_t(-0.555570), sample_t(0.914210), sample_t(-0.893224), sample_t(0.427555), sample_t(0.740951), sample_t(-0.405241), sample_t(-0.870087), sample_t(-0.881921),
    sample_t(-0.471397), sample_t(0.653173), sample_t(0.575808), sample_t(-0.970031), sample_t(0.989177), sample_t(-0.788346), sample_t(-0.219101), sample_t(0.923880),
    sample_t(0.923880), sample_t(0.844854), sample_t(0.992480), sample_t(0.595699), sample_t(-0.857729), sample_t(0.170962), sample_t(0.073565), sample_t(0.290285),
};

static const sample_t ZC_Q_LUT[NUM_DATA_SC] = {
    sample_t(0.997290), sample_t(-0.985278), sample_t(0.514103), sample_t(0.803208), sample_t(-0.122411), sample_t(-0.534998), sample_t(-0.382683), sample_t(0.382683),
    sample_t(0.975702), sample_t(-0.615232), sample_t(0.146730), sample_t(-0.242980), sample_t(0.817585), sample_t(-0.757209), sample_t(-0.881921), sample_t(-0.471397),
    sample_t(-0.492898), sample_t(-0.914210), sample_t(-0.671559), sample_t(0.903989), sample_t(-0.449611), sample_t(0.405241), sample_t(-0.831470), sample_t(0.831470),
    sample_t(0.724247), sample_t(-0.049068), sample_t(0.427555), sample_t(0.999699), sample_t(-0.122411), sample_t(-0.634393), sample_t(0.773010), sample_t(-0.449611),
    sample_t(-0.534998), sample_t(0.803208), sample_t(0.970031), sample_t(0.870087), sample_t(0.985278), sample_t(0.707107), sample_t(-0.707107), sample_t(-0.170962),
    sample_t(0.492898), sample_t(-0.242980), sample_t(-0.595699), sample_t(0.844854), sample_t(0.893224), sample_t(0.634393), sample_t(0.773010), sample_t(0.992480),
    sample_t(0.024541), sample_t(0.998795), sample_t(-0.997290), sample_t(0.689541), sample_t(0.555570), sample_t(-0.555570), sample_t(-0.914210), sample_t(-0.893224),
    sample_t(-0.427555), sample_t(0.740951), sample_t(0.405241), sample_t(-0.870087), sample_t(0.881921), sample_t(-0.471397), sample_t(-0.653173), sample_t(0.575808),
    sample_t(0.970031), sample_t(0.989177), sample_t(0.788346), sample_t(-0.219101), sample_t(-0.923880), sample_t(0.923880), sample_t(-0.844854), sample_t(0.992480),
    sample_t(-0.595699), sample_t(-0.170962), sample_t(0.073565), sample_t(-0.290285), sample_t(-0.956940), sample_t(-0.266713), sample_t(0.932993), sample_t(-0.998795),
    sample_t(0.941544), sample_t(-0.313682), sample_t(-0.932993), sample_t(-0.195090), sample_t(0.195090), sample_t(-0.024541), sample_t(-0.757209), sample_t(-0.740951),
    sample_t(0.941544), sample_t(-0.689541), sample_t(0.788346), sample_t(-0.995185), sample_t(0.098017), sample_t(0.949528), sample_t(0.975702), sample_t(0.989177),
    sample_t(0.857729), sample_t(-0.266713), sample_t(-0.817585), sample_t(0.999969), sample_t(0.817585), sample_t(0.266713), sample_t(-0.857729), sample_t(-0.989177),
    sample_t(-0.975702), sample_t(-0.949528), sample_t(-0.098017), sample_t(0.995185), sample_t(-0.788346), sample_t(0.689541), sample_t(-0.941544), sample_t(0.740951),
    sample_t(0.757209), sample_t(0.024541), sample_t(-0.195090), sample_t(0.195090), sample_t(0.932993), sample_t(0.313682), sample_t(-0.941544), sample_t(0.998795),
    sample_t(-0.932993), sample_t(0.266713), sample_t(0.956940), sample_t(0.290285), sample_t(-0.073565), sample_t(0.857729), sample_t(0.595699), sample_t(-0.992480),
    sample_t(0.844854), sample_t(-0.923880), sample_t(0.923880), sample_t(0.219101), sample_t(-0.788346), sample_t(-0.989177), sample_t(-0.970031), sample_t(-0.575808),
    sample_t(0.653173), sample_t(0.471397), sample_t(-0.881921), sample_t(0.870087), sample_t(-0.405241), sample_t(-0.740951), sample_t(0.427555), sample_t(0.893224),
    sample_t(0.914210), sample_t(0.555570), sample_t(-0.555570), sample_t(-0.689541), sample_t(0.997290), sample_t(0.903989), sample_t(-0.024541), sample_t(-0.992480),
    sample_t(-0.773010), sample_t(-0.634393), sample_t(-0.893224), sample_t(-0.844854), sample_t(0.595699), sample_t(0.242980), sample_t(-0.492898), sample_t(0.170962),
    sample_t(0.707107), sample_t(-0.707107), sample_t(-0.985278), sample_t(-0.870087), sample_t(-0.970031), sample_t(-0.803208), sample_t(0.534998), sample_t(0.449611),
    sample_t(-0.773010), sample_t(0.634393), sample_t(0.122411), sample_t(-0.999699), sample_t(-0.427555), sample_t(-0.073565), sample_t(-0.724247), sample_t(-0.831470),
    sample_t(0.831470), sample_t(-0.405241), sample_t(0.449611), sample_t(-0.903989), sample_t(0.671559), sample_t(0.914210), sample_t(0.492898), sample_t(0.471397),
    sample_t(0.881921), sample_t(0.757209), sample_t(-0.817585), sample_t(0.242980), sample_t(-0.146730), sample_t(0.615232), sample_t(-0.975702), sample_t(-0.382683),
    sample_t(0.382683), sample_t(0.534998), sample_t(0.122411), sample_t(-0.803208), sample_t(-0.514103), sample_t(0.985278), sample_t(-0.997290), sample_t(0.956940),
};

// ── CORDIC angle table  atan(2^-i)  for i = 0..15 ────────────
// Single source of truth.  Each consumer instantiates its own
// ap_fixed<…> ATAN_LUT[16] = CORDIC_ATAN_VALUES;  the brace-init
// converts each double to the consumer's preferred fixed-point type,
// so callers with different precisions (ofdm_rx uses ap_fixed<32,4>,
// sync_detect uses ap_fixed<20,8>) all stay correct.
#define CORDIC_ATAN_VALUES { \
    0.7853981634,  /* atan(2^0)  = π/4 */    \
    0.4636476090,  /* atan(2^-1)        */   \
    0.2449786631,  /* atan(2^-2)        */   \
    0.1243549945,  /* atan(2^-3)        */   \
    0.0624188100,  /* atan(2^-4)        */   \
    0.0312398334,  /* atan(2^-5)        */   \
    0.0156237286,  /* atan(2^-6)        */   \
    0.0078123766,  /* atan(2^-7)        */   \
    0.0039062301,  /* atan(2^-8)        */   \
    0.0019531226,  /* atan(2^-9)        */   \
    0.0009765622,  /* atan(2^-10)       */   \
    0.0004882812,  /* atan(2^-11)       */   \
    0.0002441406,  /* atan(2^-12)       */   \
    0.0001220703,  /* atan(2^-13)       */   \
    0.0000610352,  /* atan(2^-14)       */   \
    0.0000305176   /* atan(2^-15)       */   \
}

// ── CRC-16/CCITT (poly 0x1021, init 0xFFFF) over a 10-bit payload ──
// Used by ofdm_tx (header emission) and ofdm_rx (header check).
// Inline in header → fully unrolled at each call site → pure
// combinational XOR tree per call.
static inline ap_uint<16> crc16_hdr(ap_uint<10> data) {
    ap_uint<16> crc = 0xFFFF;
    for (int i = 9; i >= 0; i--) {
        #pragma HLS UNROLL
        ap_uint<1> x = crc[15] ^ data[i];
        crc = (ap_uint<16>)(crc << 1);
        if (x) crc ^= ap_uint<16>(0x1021);
    }
    return crc;
}
