-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ofdm_mac_do_tx_Pipeline_HDR_LEN is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    phy_tx_out_TREADY : IN STD_LOGIC;
    crc_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    zext_ln120 : IN STD_LOGIC_VECTOR (12 downto 0);
    phy_tx_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    phy_tx_out_TVALID : OUT STD_LOGIC;
    crc_22_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    crc_22_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of ofdm_mac_do_tx_Pipeline_HDR_LEN is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4C11DB7 : STD_LOGIC_VECTOR (31 downto 0) := "00000100110000010001110110110111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_111_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal phy_tx_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal b_fu_141_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_reg_423 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal crc_22_fu_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal crc_63_fu_388_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_64 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal i_5_fu_145_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp0 : BOOLEAN;
    signal trunc_ln136_fu_119_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln3_fu_123_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln120_cast_fu_94_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln136_fu_131_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln136_fu_135_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln15_1_fu_159_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_43_fu_180_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_fu_172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_45_fu_186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_46_fu_192_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_47_fu_208_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_15_fu_200_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_8_fu_214_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_48_fu_220_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_49_fu_236_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_16_fu_228_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_50_fu_242_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_51_fu_248_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_52_fu_264_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_17_fu_256_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_10_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_53_fu_276_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_54_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_18_fu_284_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_55_fu_298_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_56_fu_304_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_57_fu_320_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_19_fu_312_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_fu_326_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_58_fu_332_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_59_fu_348_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_20_fu_340_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal crc_60_fu_354_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_61_fu_360_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal crc_62_fu_376_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal top_21_fu_368_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln20_12_fu_382_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_340 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component ofdm_mac_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component ofdm_mac_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    crc_22_fu_60_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_340)) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    crc_22_fu_60 <= crc_reload;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    crc_22_fu_60 <= crc_63_fu_388_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((tmp_fu_111_p3 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_64 <= i_5_fu_145_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_64 <= ap_const_lv2_1;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                b_reg_423 <= b_fu_141_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, phy_tx_out_TREADY)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((phy_tx_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, phy_tx_out_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((phy_tx_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, phy_tx_out_TREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((phy_tx_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, phy_tx_out_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((phy_tx_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_340_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
                ap_condition_340 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_fu_111_p3)
    begin
        if (((tmp_fu_111_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, i_fu_64, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv2_1;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_64;
        end if; 
    end process;

    b_fu_141_p1 <= lshr_ln136_fu_135_p2(8 - 1 downto 0);
    crc_22_out <= crc_22_fu_60;

    crc_22_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, tmp_fu_111_p3, ap_loop_exit_ready, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (tmp_fu_111_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            crc_22_out_ap_vld <= ap_const_logic_1;
        else 
            crc_22_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    crc_43_fu_180_p2 <= std_logic_vector(shift_left(unsigned(crc_fu_166_p2),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_45_fu_186_p2 <= (crc_43_fu_180_p2 xor ap_const_lv32_4C11DB7);
    crc_46_fu_192_p3 <= 
        crc_45_fu_186_p2 when (top_fu_172_p3(0) = '1') else 
        crc_43_fu_180_p2;
    crc_47_fu_208_p2 <= std_logic_vector(shift_left(unsigned(crc_46_fu_192_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_48_fu_220_p3 <= 
        xor_ln20_8_fu_214_p2 when (top_15_fu_200_p3(0) = '1') else 
        crc_47_fu_208_p2;
    crc_49_fu_236_p2 <= std_logic_vector(shift_left(unsigned(crc_48_fu_220_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_50_fu_242_p2 <= (crc_49_fu_236_p2 xor ap_const_lv32_4C11DB7);
    crc_51_fu_248_p3 <= 
        crc_50_fu_242_p2 when (top_16_fu_228_p3(0) = '1') else 
        crc_49_fu_236_p2;
    crc_52_fu_264_p2 <= std_logic_vector(shift_left(unsigned(crc_51_fu_248_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_53_fu_276_p3 <= 
        xor_ln20_10_fu_270_p2 when (top_17_fu_256_p3(0) = '1') else 
        crc_52_fu_264_p2;
    crc_54_fu_292_p2 <= std_logic_vector(shift_left(unsigned(crc_53_fu_276_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_55_fu_298_p2 <= (crc_54_fu_292_p2 xor ap_const_lv32_4C11DB7);
    crc_56_fu_304_p3 <= 
        crc_55_fu_298_p2 when (top_18_fu_284_p3(0) = '1') else 
        crc_54_fu_292_p2;
    crc_57_fu_320_p2 <= std_logic_vector(shift_left(unsigned(crc_56_fu_304_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_58_fu_332_p3 <= 
        xor_ln20_fu_326_p2 when (top_19_fu_312_p3(0) = '1') else 
        crc_57_fu_320_p2;
    crc_59_fu_348_p2 <= std_logic_vector(shift_left(unsigned(crc_58_fu_332_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_60_fu_354_p2 <= (crc_59_fu_348_p2 xor ap_const_lv32_4C11DB7);
    crc_61_fu_360_p3 <= 
        crc_60_fu_354_p2 when (top_20_fu_340_p3(0) = '1') else 
        crc_59_fu_348_p2;
    crc_62_fu_376_p2 <= std_logic_vector(shift_left(unsigned(crc_61_fu_360_p3),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    crc_63_fu_388_p3 <= 
        xor_ln20_12_fu_382_p2 when (top_21_fu_368_p3(0) = '1') else 
        crc_62_fu_376_p2;
    crc_fu_166_p2 <= (shl_ln15_1_fu_159_p3 xor crc_22_fu_60);
    i_5_fu_145_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv2_3));
    lshr_ln136_fu_135_p2 <= std_logic_vector(shift_right(unsigned(zext_ln120_cast_fu_94_p1),to_integer(unsigned('0' & zext_ln136_fu_131_p1(16-1 downto 0)))));
    phy_tx_out_TDATA <= b_reg_423;

    phy_tx_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, phy_tx_out_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            phy_tx_out_TDATA_blk_n <= phy_tx_out_TREADY;
        else 
            phy_tx_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    phy_tx_out_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            phy_tx_out_TVALID <= ap_const_logic_1;
        else 
            phy_tx_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln15_1_fu_159_p3 <= (b_reg_423 & ap_const_lv24_0);
    shl_ln3_fu_123_p3 <= (trunc_ln136_fu_119_p1 & ap_const_lv3_0);
    tmp_fu_111_p3 <= ap_sig_allocacmp_i_4(1 downto 1);
    top_15_fu_200_p3 <= crc_46_fu_192_p3(31 downto 31);
    top_16_fu_228_p3 <= crc_48_fu_220_p3(31 downto 31);
    top_17_fu_256_p3 <= crc_51_fu_248_p3(31 downto 31);
    top_18_fu_284_p3 <= crc_53_fu_276_p3(31 downto 31);
    top_19_fu_312_p3 <= crc_56_fu_304_p3(31 downto 31);
    top_20_fu_340_p3 <= crc_58_fu_332_p3(31 downto 31);
    top_21_fu_368_p3 <= crc_61_fu_360_p3(31 downto 31);
    top_fu_172_p3 <= crc_fu_166_p2(31 downto 31);
    trunc_ln136_fu_119_p1 <= ap_sig_allocacmp_i_4(1 - 1 downto 0);
    xor_ln20_10_fu_270_p2 <= (crc_52_fu_264_p2 xor ap_const_lv32_4C11DB7);
    xor_ln20_12_fu_382_p2 <= (crc_62_fu_376_p2 xor ap_const_lv32_4C11DB7);
    xor_ln20_8_fu_214_p2 <= (crc_47_fu_208_p2 xor ap_const_lv32_4C11DB7);
    xor_ln20_fu_326_p2 <= (crc_57_fu_320_p2 xor ap_const_lv32_4C11DB7);
    zext_ln120_cast_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln120),16));
    zext_ln136_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln3_fu_123_p3),16));
end behav;
