-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ofdm_mac is
generic (
    C_M_AXI_CSR_MASTER_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_CSR_MASTER_ID_WIDTH : INTEGER := 1;
    C_M_AXI_CSR_MASTER_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_CSR_MASTER_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_CSR_MASTER_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_CSR_MASTER_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_CSR_MASTER_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_CSR_MASTER_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_CSR_MASTER_USER_VALUE : INTEGER := 0;
    C_M_AXI_CSR_MASTER_PROT_VALUE : INTEGER := 0;
    C_M_AXI_CSR_MASTER_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_csr_master_AWVALID : OUT STD_LOGIC;
    m_axi_csr_master_AWREADY : IN STD_LOGIC;
    m_axi_csr_master_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ADDR_WIDTH-1 downto 0);
    m_axi_csr_master_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ID_WIDTH-1 downto 0);
    m_axi_csr_master_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_csr_master_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_csr_master_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_csr_master_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_csr_master_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_csr_master_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_csr_master_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_csr_master_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_csr_master_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_AWUSER_WIDTH-1 downto 0);
    m_axi_csr_master_WVALID : OUT STD_LOGIC;
    m_axi_csr_master_WREADY : IN STD_LOGIC;
    m_axi_csr_master_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_DATA_WIDTH-1 downto 0);
    m_axi_csr_master_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_DATA_WIDTH/8-1 downto 0);
    m_axi_csr_master_WLAST : OUT STD_LOGIC;
    m_axi_csr_master_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ID_WIDTH-1 downto 0);
    m_axi_csr_master_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_WUSER_WIDTH-1 downto 0);
    m_axi_csr_master_ARVALID : OUT STD_LOGIC;
    m_axi_csr_master_ARREADY : IN STD_LOGIC;
    m_axi_csr_master_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ADDR_WIDTH-1 downto 0);
    m_axi_csr_master_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ID_WIDTH-1 downto 0);
    m_axi_csr_master_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_csr_master_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_csr_master_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_csr_master_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_csr_master_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_csr_master_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_csr_master_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_csr_master_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_csr_master_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ARUSER_WIDTH-1 downto 0);
    m_axi_csr_master_RVALID : IN STD_LOGIC;
    m_axi_csr_master_RREADY : OUT STD_LOGIC;
    m_axi_csr_master_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_DATA_WIDTH-1 downto 0);
    m_axi_csr_master_RLAST : IN STD_LOGIC;
    m_axi_csr_master_RID : IN STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ID_WIDTH-1 downto 0);
    m_axi_csr_master_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_RUSER_WIDTH-1 downto 0);
    m_axi_csr_master_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_csr_master_BVALID : IN STD_LOGIC;
    m_axi_csr_master_BREADY : OUT STD_LOGIC;
    m_axi_csr_master_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_csr_master_BID : IN STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_ID_WIDTH-1 downto 0);
    m_axi_csr_master_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_CSR_MASTER_BUSER_WIDTH-1 downto 0);
    host_tx_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    host_tx_in_TVALID : IN STD_LOGIC;
    host_tx_in_TREADY : OUT STD_LOGIC;
    host_tx_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    host_tx_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    host_tx_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    host_rx_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    host_rx_out_TVALID : OUT STD_LOGIC;
    host_rx_out_TREADY : IN STD_LOGIC;
    host_rx_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
    host_rx_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    host_rx_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    phy_tx_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    phy_tx_out_TVALID : OUT STD_LOGIC;
    phy_tx_out_TREADY : IN STD_LOGIC;
    phy_rx_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    phy_rx_in_TVALID : IN STD_LOGIC;
    phy_rx_in_TREADY : OUT STD_LOGIC;
    rx_modcod_in : IN STD_LOGIC_VECTOR (1 downto 0);
    rx_n_syms_in : IN STD_LOGIC_VECTOR (7 downto 0);
    rx_header_err : IN STD_LOGIC_VECTOR (0 downto 0);
    tx_done_pulse : OUT STD_LOGIC_VECTOR (0 downto 0);
    tx_done_pulse_ap_vld : OUT STD_LOGIC;
    rx_pkt_pulse : OUT STD_LOGIC_VECTOR (0 downto 0);
    rx_pkt_pulse_ap_vld : OUT STD_LOGIC;
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_ctrl_AWVALID : IN STD_LOGIC;
    s_axi_ctrl_AWREADY : OUT STD_LOGIC;
    s_axi_ctrl_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_WVALID : IN STD_LOGIC;
    s_axi_ctrl_WREADY : OUT STD_LOGIC;
    s_axi_ctrl_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_ctrl_ARVALID : IN STD_LOGIC;
    s_axi_ctrl_ARREADY : OUT STD_LOGIC;
    s_axi_ctrl_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_RVALID : OUT STD_LOGIC;
    s_axi_ctrl_RREADY : IN STD_LOGIC;
    s_axi_ctrl_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_ctrl_BVALID : OUT STD_LOGIC;
    s_axi_ctrl_BREADY : IN STD_LOGIC;
    s_axi_ctrl_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of ofdm_mac is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ofdm_mac_ofdm_mac,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a50t-csg325-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=10.565000,HLS_SYN_LAT=1303,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=2861,HLS_SYN_LUT=7587,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal phy_csr : STD_LOGIC_VECTOR (63 downto 0);
    signal my_mac_addr : STD_LOGIC_VECTOR (47 downto 0);
    signal promisc : STD_LOGIC_VECTOR (0 downto 0);
    signal modcod : STD_LOGIC_VECTOR (1 downto 0);
    signal mac_enable : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_pkt_count_i : STD_LOGIC_VECTOR (31 downto 0);
    signal tx_pkt_count_o : STD_LOGIC_VECTOR (31 downto 0);
    signal tx_pkt_count_o_ap_vld : STD_LOGIC;
    signal rx_pkt_count_i : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_pkt_count_o : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_pkt_count_o_ap_vld : STD_LOGIC;
    signal rx_drop_count_i : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_drop_count_o : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_drop_count_o_ap_vld : STD_LOGIC;
    signal rx_fcs_err_count_i : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_fcs_err_count_o : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_fcs_err_count_o_ap_vld : STD_LOGIC;
    signal last_rx_modcod : STD_LOGIC_VECTOR (1 downto 0);
    signal last_rx_n_syms : STD_LOGIC_VECTOR (7 downto 0);
    signal rx_hdr_err_count_i : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_hdr_err_count_o : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_hdr_err_count_o_ap_vld : STD_LOGIC;
    signal tx_done_pulse_1_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tx_done_pulse_1_data_in : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_done_pulse_1_vld_reg : STD_LOGIC := '0';
    signal tx_done_pulse_1_vld_in : STD_LOGIC;
    signal tx_done_pulse_1_ack_in : STD_LOGIC;
    signal rx_pkt_pulse_1_data_reg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal rx_pkt_pulse_1_data_in : STD_LOGIC_VECTOR (0 downto 0);
    signal rx_pkt_pulse_1_vld_reg : STD_LOGIC := '0';
    signal rx_pkt_pulse_1_vld_in : STD_LOGIC;
    signal rx_pkt_pulse_1_ack_in : STD_LOGIC;
    signal modcod_read_reg_414 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal promisc_read_reg_419 : STD_LOGIC_VECTOR (0 downto 0);
    signal my_mac_addr_read_reg_424 : STD_LOGIC_VECTOR (47 downto 0);
    signal rx_n_syms_in_read_reg_433 : STD_LOGIC_VECTOR (7 downto 0);
    signal rx_modcod_in_read_reg_438 : STD_LOGIC_VECTOR (1 downto 0);
    signal phy_csr_read_reg_443 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_vld_fu_376_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld_reg_448 : STD_LOGIC_VECTOR (0 downto 0);
    signal tx_first_data_reg_452 : STD_LOGIC_VECTOR (7 downto 0);
    signal tx_first_last_reg_457 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld9_fu_388_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld9_reg_462 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_reg_466 : STD_LOGIC_VECTOR (7 downto 0);
    signal rx_pkt_count_read_reg_471 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rx_drop_count_read_reg_476 : STD_LOGIC_VECTOR (31 downto 0);
    signal rx_fcs_err_count_read_reg_481 : STD_LOGIC_VECTOR (31 downto 0);
    signal tx_pkt_count_read_reg_486 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_do_rx_fu_312_ap_start : STD_LOGIC;
    signal grp_do_rx_fu_312_ap_done : STD_LOGIC;
    signal grp_do_rx_fu_312_ap_idle : STD_LOGIC;
    signal grp_do_rx_fu_312_ap_ready : STD_LOGIC;
    signal grp_do_rx_fu_312_phy_rx_in_TREADY : STD_LOGIC;
    signal grp_do_rx_fu_312_host_rx_out_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_do_rx_fu_312_host_rx_out_TVALID : STD_LOGIC;
    signal grp_do_rx_fu_312_host_rx_out_TREADY : STD_LOGIC;
    signal grp_do_rx_fu_312_host_rx_out_TKEEP : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_rx_fu_312_host_rx_out_TSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_rx_fu_312_host_rx_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_rx_fu_312_last_rx_modcod : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_do_rx_fu_312_last_rx_modcod_ap_vld : STD_LOGIC;
    signal grp_do_rx_fu_312_last_rx_n_syms : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_do_rx_fu_312_last_rx_n_syms_ap_vld : STD_LOGIC;
    signal grp_do_rx_fu_312_rx_pkt_pulse : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_rx_fu_312_rx_pkt_pulse_ap_vld : STD_LOGIC;
    signal grp_do_rx_fu_312_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_rx_fu_312_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_rx_fu_312_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_tx_fu_343_ap_start : STD_LOGIC;
    signal grp_do_tx_fu_343_ap_done : STD_LOGIC;
    signal grp_do_tx_fu_343_ap_idle : STD_LOGIC;
    signal grp_do_tx_fu_343_ap_ready : STD_LOGIC;
    signal grp_do_tx_fu_343_host_tx_in_TREADY : STD_LOGIC;
    signal grp_do_tx_fu_343_phy_tx_out_TDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_do_tx_fu_343_phy_tx_out_TVALID : STD_LOGIC;
    signal grp_do_tx_fu_343_phy_tx_out_TREADY : STD_LOGIC;
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWVALID : STD_LOGIC;
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_WVALID : STD_LOGIC;
    signal grp_do_tx_fu_343_m_axi_csr_master_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_WLAST : STD_LOGIC;
    signal grp_do_tx_fu_343_m_axi_csr_master_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARVALID : STD_LOGIC;
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_m_axi_csr_master_0_RREADY : STD_LOGIC;
    signal grp_do_tx_fu_343_m_axi_csr_master_0_BREADY : STD_LOGIC;
    signal grp_do_tx_fu_343_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal csr_master_0_AWVALID : STD_LOGIC;
    signal csr_master_0_AWREADY : STD_LOGIC;
    signal csr_master_0_WVALID : STD_LOGIC;
    signal csr_master_0_WREADY : STD_LOGIC;
    signal csr_master_0_ARREADY : STD_LOGIC;
    signal csr_master_0_RVALID : STD_LOGIC;
    signal csr_master_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal csr_master_0_RFIFONUM : STD_LOGIC_VECTOR (1 downto 0);
    signal csr_master_0_BVALID : STD_LOGIC;
    signal csr_master_0_BREADY : STD_LOGIC;
    signal grp_do_rx_fu_312_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal host_rx_out_TDATA_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal host_rx_out_TKEEP_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal host_rx_out_TSTRB_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal host_rx_out_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal last_rx_modcod_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal last_rx_n_syms_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal rx_pkt_pulse_1_data_in_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_do_tx_fu_343_ap_start_reg : STD_LOGIC := '0';
    signal phy_tx_out_TDATA_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal mac_enable_read_read_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rx_header_err_read_read_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln310_fu_369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_nbread_fu_241_p5_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal phy_rx_in_read_nbread_fu_253_p2_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op103_call_state4 : BOOLEAN;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal regslice_both_host_rx_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_phy_tx_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state6 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_host_tx_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal host_tx_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal host_tx_in_TVALID_int_regslice : STD_LOGIC;
    signal host_tx_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_host_tx_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_host_tx_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal host_tx_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_host_tx_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_host_tx_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_host_tx_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal host_tx_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_host_tx_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_host_tx_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_host_tx_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal host_tx_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_host_tx_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_host_tx_in_V_last_V_U_ack_in : STD_LOGIC;
    signal host_rx_out_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal host_rx_out_TVALID_int_regslice : STD_LOGIC;
    signal host_rx_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_host_rx_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_host_rx_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal host_rx_out_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_host_rx_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_host_rx_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_host_rx_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal host_rx_out_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_host_rx_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_host_rx_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_host_rx_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal host_rx_out_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_host_rx_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_host_rx_out_V_last_V_U_vld_out : STD_LOGIC;
    signal phy_tx_out_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal phy_tx_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_phy_tx_out_U_vld_out : STD_LOGIC;
    signal regslice_both_phy_rx_in_U_apdone_blk : STD_LOGIC;
    signal phy_rx_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal phy_rx_in_TVALID_int_regslice : STD_LOGIC;
    signal phy_rx_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_phy_rx_in_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ofdm_mac_do_rx IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        first_byte : IN STD_LOGIC_VECTOR (7 downto 0);
        phy_rx_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        phy_rx_in_TVALID : IN STD_LOGIC;
        phy_rx_in_TREADY : OUT STD_LOGIC;
        host_rx_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        host_rx_out_TVALID : OUT STD_LOGIC;
        host_rx_out_TREADY : IN STD_LOGIC;
        host_rx_out_TKEEP : OUT STD_LOGIC_VECTOR (0 downto 0);
        host_rx_out_TSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        host_rx_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        my_mac_addr : IN STD_LOGIC_VECTOR (47 downto 0);
        promisc : IN STD_LOGIC_VECTOR (0 downto 0);
        rx_modcod_in : IN STD_LOGIC_VECTOR (1 downto 0);
        rx_n_syms_in : IN STD_LOGIC_VECTOR (7 downto 0);
        rx_pkt_count_read : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_drop_count_read : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_fcs_err_count_read : IN STD_LOGIC_VECTOR (31 downto 0);
        last_rx_modcod : OUT STD_LOGIC_VECTOR (1 downto 0);
        last_rx_modcod_ap_vld : OUT STD_LOGIC;
        last_rx_n_syms : OUT STD_LOGIC_VECTOR (7 downto 0);
        last_rx_n_syms_ap_vld : OUT STD_LOGIC;
        rx_pkt_pulse : OUT STD_LOGIC_VECTOR (0 downto 0);
        rx_pkt_pulse_ap_vld : OUT STD_LOGIC;
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ofdm_mac_do_tx IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        first_byte_seen : IN STD_LOGIC_VECTOR (7 downto 0);
        first_was_last : IN STD_LOGIC_VECTOR (0 downto 0);
        host_tx_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        host_tx_in_TVALID : IN STD_LOGIC;
        host_tx_in_TREADY : OUT STD_LOGIC;
        host_tx_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        host_tx_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        host_tx_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        phy_tx_out_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        phy_tx_out_TVALID : OUT STD_LOGIC;
        phy_tx_out_TREADY : IN STD_LOGIC;
        m_axi_csr_master_0_AWVALID : OUT STD_LOGIC;
        m_axi_csr_master_0_AWREADY : IN STD_LOGIC;
        m_axi_csr_master_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_csr_master_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_csr_master_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_csr_master_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_csr_master_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_WVALID : OUT STD_LOGIC;
        m_axi_csr_master_0_WREADY : IN STD_LOGIC;
        m_axi_csr_master_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_csr_master_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_WLAST : OUT STD_LOGIC;
        m_axi_csr_master_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_ARVALID : OUT STD_LOGIC;
        m_axi_csr_master_0_ARREADY : IN STD_LOGIC;
        m_axi_csr_master_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_csr_master_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_csr_master_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_csr_master_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_csr_master_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_csr_master_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_RVALID : IN STD_LOGIC;
        m_axi_csr_master_0_RREADY : OUT STD_LOGIC;
        m_axi_csr_master_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_csr_master_0_RLAST : IN STD_LOGIC;
        m_axi_csr_master_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_RFIFONUM : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_BVALID : IN STD_LOGIC;
        m_axi_csr_master_0_BREADY : OUT STD_LOGIC;
        m_axi_csr_master_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_csr_master_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_csr_master_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        phy_csr : IN STD_LOGIC_VECTOR (63 downto 0);
        my_mac_addr : IN STD_LOGIC_VECTOR (47 downto 0);
        modcod : IN STD_LOGIC_VECTOR (1 downto 0);
        tx_pkt_count_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ofdm_mac_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        phy_csr : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ofdm_mac_ctrl_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        my_mac_addr : OUT STD_LOGIC_VECTOR (47 downto 0);
        promisc : OUT STD_LOGIC_VECTOR (0 downto 0);
        modcod : OUT STD_LOGIC_VECTOR (1 downto 0);
        mac_enable : OUT STD_LOGIC_VECTOR (0 downto 0);
        tx_pkt_count_o : IN STD_LOGIC_VECTOR (31 downto 0);
        tx_pkt_count_o_ap_vld : IN STD_LOGIC;
        tx_pkt_count_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        rx_pkt_count_o : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_pkt_count_o_ap_vld : IN STD_LOGIC;
        rx_pkt_count_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        rx_drop_count_o : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_drop_count_o_ap_vld : IN STD_LOGIC;
        rx_drop_count_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        rx_fcs_err_count_o : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_fcs_err_count_o_ap_vld : IN STD_LOGIC;
        rx_fcs_err_count_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        last_rx_modcod : IN STD_LOGIC_VECTOR (1 downto 0);
        last_rx_modcod_ap_vld : IN STD_LOGIC;
        last_rx_n_syms : IN STD_LOGIC_VECTOR (7 downto 0);
        last_rx_n_syms_ap_vld : IN STD_LOGIC;
        rx_hdr_err_count_o : IN STD_LOGIC_VECTOR (31 downto 0);
        rx_hdr_err_count_o_ap_vld : IN STD_LOGIC;
        rx_hdr_err_count_i : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component ofdm_mac_csr_master_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component ofdm_mac_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_do_rx_fu_312 : component ofdm_mac_do_rx
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_do_rx_fu_312_ap_start,
        ap_done => grp_do_rx_fu_312_ap_done,
        ap_idle => grp_do_rx_fu_312_ap_idle,
        ap_ready => grp_do_rx_fu_312_ap_ready,
        first_byte => p_0_reg_466,
        phy_rx_in_TDATA => phy_rx_in_TDATA_int_regslice,
        phy_rx_in_TVALID => phy_rx_in_TVALID_int_regslice,
        phy_rx_in_TREADY => grp_do_rx_fu_312_phy_rx_in_TREADY,
        host_rx_out_TDATA => grp_do_rx_fu_312_host_rx_out_TDATA,
        host_rx_out_TVALID => grp_do_rx_fu_312_host_rx_out_TVALID,
        host_rx_out_TREADY => grp_do_rx_fu_312_host_rx_out_TREADY,
        host_rx_out_TKEEP => grp_do_rx_fu_312_host_rx_out_TKEEP,
        host_rx_out_TSTRB => grp_do_rx_fu_312_host_rx_out_TSTRB,
        host_rx_out_TLAST => grp_do_rx_fu_312_host_rx_out_TLAST,
        my_mac_addr => my_mac_addr_read_reg_424,
        promisc => promisc_read_reg_419,
        rx_modcod_in => rx_modcod_in_read_reg_438,
        rx_n_syms_in => rx_n_syms_in_read_reg_433,
        rx_pkt_count_read => rx_pkt_count_read_reg_471,
        rx_drop_count_read => rx_drop_count_read_reg_476,
        rx_fcs_err_count_read => rx_fcs_err_count_read_reg_481,
        last_rx_modcod => grp_do_rx_fu_312_last_rx_modcod,
        last_rx_modcod_ap_vld => grp_do_rx_fu_312_last_rx_modcod_ap_vld,
        last_rx_n_syms => grp_do_rx_fu_312_last_rx_n_syms,
        last_rx_n_syms_ap_vld => grp_do_rx_fu_312_last_rx_n_syms_ap_vld,
        rx_pkt_pulse => grp_do_rx_fu_312_rx_pkt_pulse,
        rx_pkt_pulse_ap_vld => grp_do_rx_fu_312_rx_pkt_pulse_ap_vld,
        ap_return_0 => grp_do_rx_fu_312_ap_return_0,
        ap_return_1 => grp_do_rx_fu_312_ap_return_1,
        ap_return_2 => grp_do_rx_fu_312_ap_return_2);

    grp_do_tx_fu_343 : component ofdm_mac_do_tx
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_do_tx_fu_343_ap_start,
        ap_done => grp_do_tx_fu_343_ap_done,
        ap_idle => grp_do_tx_fu_343_ap_idle,
        ap_ready => grp_do_tx_fu_343_ap_ready,
        first_byte_seen => tx_first_data_reg_452,
        first_was_last => tx_first_last_reg_457,
        host_tx_in_TDATA => host_tx_in_TDATA_int_regslice,
        host_tx_in_TVALID => host_tx_in_TVALID_int_regslice,
        host_tx_in_TREADY => grp_do_tx_fu_343_host_tx_in_TREADY,
        host_tx_in_TKEEP => host_tx_in_TKEEP_int_regslice,
        host_tx_in_TSTRB => host_tx_in_TSTRB_int_regslice,
        host_tx_in_TLAST => host_tx_in_TLAST_int_regslice,
        phy_tx_out_TDATA => grp_do_tx_fu_343_phy_tx_out_TDATA,
        phy_tx_out_TVALID => grp_do_tx_fu_343_phy_tx_out_TVALID,
        phy_tx_out_TREADY => grp_do_tx_fu_343_phy_tx_out_TREADY,
        m_axi_csr_master_0_AWVALID => grp_do_tx_fu_343_m_axi_csr_master_0_AWVALID,
        m_axi_csr_master_0_AWREADY => csr_master_0_AWREADY,
        m_axi_csr_master_0_AWADDR => grp_do_tx_fu_343_m_axi_csr_master_0_AWADDR,
        m_axi_csr_master_0_AWID => grp_do_tx_fu_343_m_axi_csr_master_0_AWID,
        m_axi_csr_master_0_AWLEN => grp_do_tx_fu_343_m_axi_csr_master_0_AWLEN,
        m_axi_csr_master_0_AWSIZE => grp_do_tx_fu_343_m_axi_csr_master_0_AWSIZE,
        m_axi_csr_master_0_AWBURST => grp_do_tx_fu_343_m_axi_csr_master_0_AWBURST,
        m_axi_csr_master_0_AWLOCK => grp_do_tx_fu_343_m_axi_csr_master_0_AWLOCK,
        m_axi_csr_master_0_AWCACHE => grp_do_tx_fu_343_m_axi_csr_master_0_AWCACHE,
        m_axi_csr_master_0_AWPROT => grp_do_tx_fu_343_m_axi_csr_master_0_AWPROT,
        m_axi_csr_master_0_AWQOS => grp_do_tx_fu_343_m_axi_csr_master_0_AWQOS,
        m_axi_csr_master_0_AWREGION => grp_do_tx_fu_343_m_axi_csr_master_0_AWREGION,
        m_axi_csr_master_0_AWUSER => grp_do_tx_fu_343_m_axi_csr_master_0_AWUSER,
        m_axi_csr_master_0_WVALID => grp_do_tx_fu_343_m_axi_csr_master_0_WVALID,
        m_axi_csr_master_0_WREADY => csr_master_0_WREADY,
        m_axi_csr_master_0_WDATA => grp_do_tx_fu_343_m_axi_csr_master_0_WDATA,
        m_axi_csr_master_0_WSTRB => grp_do_tx_fu_343_m_axi_csr_master_0_WSTRB,
        m_axi_csr_master_0_WLAST => grp_do_tx_fu_343_m_axi_csr_master_0_WLAST,
        m_axi_csr_master_0_WID => grp_do_tx_fu_343_m_axi_csr_master_0_WID,
        m_axi_csr_master_0_WUSER => grp_do_tx_fu_343_m_axi_csr_master_0_WUSER,
        m_axi_csr_master_0_ARVALID => grp_do_tx_fu_343_m_axi_csr_master_0_ARVALID,
        m_axi_csr_master_0_ARREADY => ap_const_logic_0,
        m_axi_csr_master_0_ARADDR => grp_do_tx_fu_343_m_axi_csr_master_0_ARADDR,
        m_axi_csr_master_0_ARID => grp_do_tx_fu_343_m_axi_csr_master_0_ARID,
        m_axi_csr_master_0_ARLEN => grp_do_tx_fu_343_m_axi_csr_master_0_ARLEN,
        m_axi_csr_master_0_ARSIZE => grp_do_tx_fu_343_m_axi_csr_master_0_ARSIZE,
        m_axi_csr_master_0_ARBURST => grp_do_tx_fu_343_m_axi_csr_master_0_ARBURST,
        m_axi_csr_master_0_ARLOCK => grp_do_tx_fu_343_m_axi_csr_master_0_ARLOCK,
        m_axi_csr_master_0_ARCACHE => grp_do_tx_fu_343_m_axi_csr_master_0_ARCACHE,
        m_axi_csr_master_0_ARPROT => grp_do_tx_fu_343_m_axi_csr_master_0_ARPROT,
        m_axi_csr_master_0_ARQOS => grp_do_tx_fu_343_m_axi_csr_master_0_ARQOS,
        m_axi_csr_master_0_ARREGION => grp_do_tx_fu_343_m_axi_csr_master_0_ARREGION,
        m_axi_csr_master_0_ARUSER => grp_do_tx_fu_343_m_axi_csr_master_0_ARUSER,
        m_axi_csr_master_0_RVALID => ap_const_logic_0,
        m_axi_csr_master_0_RREADY => grp_do_tx_fu_343_m_axi_csr_master_0_RREADY,
        m_axi_csr_master_0_RDATA => ap_const_lv32_0,
        m_axi_csr_master_0_RLAST => ap_const_logic_0,
        m_axi_csr_master_0_RID => ap_const_lv1_0,
        m_axi_csr_master_0_RFIFONUM => ap_const_lv2_0,
        m_axi_csr_master_0_RUSER => ap_const_lv1_0,
        m_axi_csr_master_0_RRESP => ap_const_lv2_0,
        m_axi_csr_master_0_BVALID => csr_master_0_BVALID,
        m_axi_csr_master_0_BREADY => grp_do_tx_fu_343_m_axi_csr_master_0_BREADY,
        m_axi_csr_master_0_BRESP => ap_const_lv2_0,
        m_axi_csr_master_0_BID => ap_const_lv1_0,
        m_axi_csr_master_0_BUSER => ap_const_lv1_0,
        phy_csr => phy_csr_read_reg_443,
        my_mac_addr => my_mac_addr_read_reg_424,
        modcod => modcod_read_reg_414,
        tx_pkt_count_read => tx_pkt_count_read_reg_486,
        ap_return => grp_do_tx_fu_343_ap_return);

    control_s_axi_U : component ofdm_mac_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        phy_csr => phy_csr);

    ctrl_s_axi_U : component ofdm_mac_ctrl_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_ctrl_AWVALID,
        AWREADY => s_axi_ctrl_AWREADY,
        AWADDR => s_axi_ctrl_AWADDR,
        WVALID => s_axi_ctrl_WVALID,
        WREADY => s_axi_ctrl_WREADY,
        WDATA => s_axi_ctrl_WDATA,
        WSTRB => s_axi_ctrl_WSTRB,
        ARVALID => s_axi_ctrl_ARVALID,
        ARREADY => s_axi_ctrl_ARREADY,
        ARADDR => s_axi_ctrl_ARADDR,
        RVALID => s_axi_ctrl_RVALID,
        RREADY => s_axi_ctrl_RREADY,
        RDATA => s_axi_ctrl_RDATA,
        RRESP => s_axi_ctrl_RRESP,
        BVALID => s_axi_ctrl_BVALID,
        BREADY => s_axi_ctrl_BREADY,
        BRESP => s_axi_ctrl_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        my_mac_addr => my_mac_addr,
        promisc => promisc,
        modcod => modcod,
        mac_enable => mac_enable,
        tx_pkt_count_o => tx_pkt_count_o,
        tx_pkt_count_o_ap_vld => tx_pkt_count_o_ap_vld,
        tx_pkt_count_i => tx_pkt_count_i,
        rx_pkt_count_o => rx_pkt_count_o,
        rx_pkt_count_o_ap_vld => rx_pkt_count_o_ap_vld,
        rx_pkt_count_i => rx_pkt_count_i,
        rx_drop_count_o => rx_drop_count_o,
        rx_drop_count_o_ap_vld => rx_drop_count_o_ap_vld,
        rx_drop_count_i => rx_drop_count_i,
        rx_fcs_err_count_o => rx_fcs_err_count_o,
        rx_fcs_err_count_o_ap_vld => rx_fcs_err_count_o_ap_vld,
        rx_fcs_err_count_i => rx_fcs_err_count_i,
        last_rx_modcod => last_rx_modcod,
        last_rx_modcod_ap_vld => grp_do_rx_fu_312_last_rx_modcod_ap_vld,
        last_rx_n_syms => last_rx_n_syms,
        last_rx_n_syms_ap_vld => grp_do_rx_fu_312_last_rx_n_syms_ap_vld,
        rx_hdr_err_count_o => rx_hdr_err_count_o,
        rx_hdr_err_count_o_ap_vld => rx_hdr_err_count_o_ap_vld,
        rx_hdr_err_count_i => rx_hdr_err_count_i,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    csr_master_m_axi_U : component ofdm_mac_csr_master_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 1,
        MAX_WRITE_BURST_LENGTH => 1,
        C_M_AXI_ID_WIDTH => C_M_AXI_CSR_MASTER_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_CSR_MASTER_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_CSR_MASTER_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_CSR_MASTER_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_CSR_MASTER_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_CSR_MASTER_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_CSR_MASTER_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_CSR_MASTER_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_CSR_MASTER_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_CSR_MASTER_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_CSR_MASTER_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 1,
        CH0_NUM_WRITE_OUTSTANDING => 1,
        CH0_USER_RFIFONUM_WIDTH => 2,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 1)
    port map (
        AWVALID => m_axi_csr_master_AWVALID,
        AWREADY => m_axi_csr_master_AWREADY,
        AWADDR => m_axi_csr_master_AWADDR,
        AWID => m_axi_csr_master_AWID,
        AWLEN => m_axi_csr_master_AWLEN,
        AWSIZE => m_axi_csr_master_AWSIZE,
        AWBURST => m_axi_csr_master_AWBURST,
        AWLOCK => m_axi_csr_master_AWLOCK,
        AWCACHE => m_axi_csr_master_AWCACHE,
        AWPROT => m_axi_csr_master_AWPROT,
        AWQOS => m_axi_csr_master_AWQOS,
        AWREGION => m_axi_csr_master_AWREGION,
        AWUSER => m_axi_csr_master_AWUSER,
        WVALID => m_axi_csr_master_WVALID,
        WREADY => m_axi_csr_master_WREADY,
        WDATA => m_axi_csr_master_WDATA,
        WSTRB => m_axi_csr_master_WSTRB,
        WLAST => m_axi_csr_master_WLAST,
        WID => m_axi_csr_master_WID,
        WUSER => m_axi_csr_master_WUSER,
        ARVALID => m_axi_csr_master_ARVALID,
        ARREADY => m_axi_csr_master_ARREADY,
        ARADDR => m_axi_csr_master_ARADDR,
        ARID => m_axi_csr_master_ARID,
        ARLEN => m_axi_csr_master_ARLEN,
        ARSIZE => m_axi_csr_master_ARSIZE,
        ARBURST => m_axi_csr_master_ARBURST,
        ARLOCK => m_axi_csr_master_ARLOCK,
        ARCACHE => m_axi_csr_master_ARCACHE,
        ARPROT => m_axi_csr_master_ARPROT,
        ARQOS => m_axi_csr_master_ARQOS,
        ARREGION => m_axi_csr_master_ARREGION,
        ARUSER => m_axi_csr_master_ARUSER,
        RVALID => m_axi_csr_master_RVALID,
        RREADY => m_axi_csr_master_RREADY,
        RDATA => m_axi_csr_master_RDATA,
        RLAST => m_axi_csr_master_RLAST,
        RID => m_axi_csr_master_RID,
        RUSER => m_axi_csr_master_RUSER,
        RRESP => m_axi_csr_master_RRESP,
        BVALID => m_axi_csr_master_BVALID,
        BREADY => m_axi_csr_master_BREADY,
        BRESP => m_axi_csr_master_BRESP,
        BID => m_axi_csr_master_BID,
        BUSER => m_axi_csr_master_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => csr_master_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => csr_master_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => csr_master_0_RDATA,
        I_CH0_RFIFONUM => csr_master_0_RFIFONUM,
        I_CH0_AWVALID => csr_master_0_AWVALID,
        I_CH0_AWREADY => csr_master_0_AWREADY,
        I_CH0_AWADDR => grp_do_tx_fu_343_m_axi_csr_master_0_AWADDR,
        I_CH0_AWLEN => grp_do_tx_fu_343_m_axi_csr_master_0_AWLEN,
        I_CH0_WVALID => csr_master_0_WVALID,
        I_CH0_WREADY => csr_master_0_WREADY,
        I_CH0_WDATA => grp_do_tx_fu_343_m_axi_csr_master_0_WDATA,
        I_CH0_WSTRB => grp_do_tx_fu_343_m_axi_csr_master_0_WSTRB,
        I_CH0_BVALID => csr_master_0_BVALID,
        I_CH0_BREADY => csr_master_0_BREADY);

    regslice_both_host_tx_in_V_data_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_tx_in_TDATA,
        vld_in => host_tx_in_TVALID,
        ack_in => regslice_both_host_tx_in_V_data_V_U_ack_in,
        data_out => host_tx_in_TDATA_int_regslice,
        vld_out => host_tx_in_TVALID_int_regslice,
        ack_out => host_tx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_host_tx_in_V_data_V_U_apdone_blk);

    regslice_both_host_tx_in_V_keep_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_tx_in_TKEEP,
        vld_in => host_tx_in_TVALID,
        ack_in => regslice_both_host_tx_in_V_keep_V_U_ack_in,
        data_out => host_tx_in_TKEEP_int_regslice,
        vld_out => regslice_both_host_tx_in_V_keep_V_U_vld_out,
        ack_out => host_tx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_host_tx_in_V_keep_V_U_apdone_blk);

    regslice_both_host_tx_in_V_strb_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_tx_in_TSTRB,
        vld_in => host_tx_in_TVALID,
        ack_in => regslice_both_host_tx_in_V_strb_V_U_ack_in,
        data_out => host_tx_in_TSTRB_int_regslice,
        vld_out => regslice_both_host_tx_in_V_strb_V_U_vld_out,
        ack_out => host_tx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_host_tx_in_V_strb_V_U_apdone_blk);

    regslice_both_host_tx_in_V_last_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_tx_in_TLAST,
        vld_in => host_tx_in_TVALID,
        ack_in => regslice_both_host_tx_in_V_last_V_U_ack_in,
        data_out => host_tx_in_TLAST_int_regslice,
        vld_out => regslice_both_host_tx_in_V_last_V_U_vld_out,
        ack_out => host_tx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_host_tx_in_V_last_V_U_apdone_blk);

    regslice_both_host_rx_out_V_data_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_rx_out_TDATA_int_regslice,
        vld_in => grp_do_rx_fu_312_host_rx_out_TVALID,
        ack_in => host_rx_out_TREADY_int_regslice,
        data_out => host_rx_out_TDATA,
        vld_out => regslice_both_host_rx_out_V_data_V_U_vld_out,
        ack_out => host_rx_out_TREADY,
        apdone_blk => regslice_both_host_rx_out_V_data_V_U_apdone_blk);

    regslice_both_host_rx_out_V_keep_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_rx_out_TKEEP_int_regslice,
        vld_in => grp_do_rx_fu_312_host_rx_out_TVALID,
        ack_in => regslice_both_host_rx_out_V_keep_V_U_ack_in_dummy,
        data_out => host_rx_out_TKEEP,
        vld_out => regslice_both_host_rx_out_V_keep_V_U_vld_out,
        ack_out => host_rx_out_TREADY,
        apdone_blk => regslice_both_host_rx_out_V_keep_V_U_apdone_blk);

    regslice_both_host_rx_out_V_strb_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_rx_out_TSTRB_int_regslice,
        vld_in => grp_do_rx_fu_312_host_rx_out_TVALID,
        ack_in => regslice_both_host_rx_out_V_strb_V_U_ack_in_dummy,
        data_out => host_rx_out_TSTRB,
        vld_out => regslice_both_host_rx_out_V_strb_V_U_vld_out,
        ack_out => host_rx_out_TREADY,
        apdone_blk => regslice_both_host_rx_out_V_strb_V_U_apdone_blk);

    regslice_both_host_rx_out_V_last_V_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => host_rx_out_TLAST_int_regslice,
        vld_in => grp_do_rx_fu_312_host_rx_out_TVALID,
        ack_in => regslice_both_host_rx_out_V_last_V_U_ack_in_dummy,
        data_out => host_rx_out_TLAST,
        vld_out => regslice_both_host_rx_out_V_last_V_U_vld_out,
        ack_out => host_rx_out_TREADY,
        apdone_blk => regslice_both_host_rx_out_V_last_V_U_apdone_blk);

    regslice_both_phy_tx_out_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => phy_tx_out_TDATA_int_regslice,
        vld_in => grp_do_tx_fu_343_phy_tx_out_TVALID,
        ack_in => phy_tx_out_TREADY_int_regslice,
        data_out => phy_tx_out_TDATA,
        vld_out => regslice_both_phy_tx_out_U_vld_out,
        ack_out => phy_tx_out_TREADY,
        apdone_blk => regslice_both_phy_tx_out_U_apdone_blk);

    regslice_both_phy_rx_in_U : component ofdm_mac_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => phy_rx_in_TDATA,
        vld_in => phy_rx_in_TVALID,
        ack_in => regslice_both_phy_rx_in_U_ack_in,
        data_out => phy_rx_in_TDATA_int_regslice,
        vld_out => phy_rx_in_TVALID_int_regslice,
        ack_out => phy_rx_in_TREADY_int_regslice,
        apdone_blk => regslice_both_phy_rx_in_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_do_rx_fu_312_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_do_rx_fu_312_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_do_rx_fu_312_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_do_rx_fu_312_ap_ready = ap_const_logic_1)) then 
                    grp_do_rx_fu_312_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_do_tx_fu_343_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_do_tx_fu_343_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_do_tx_fu_343_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_do_tx_fu_343_ap_ready = ap_const_logic_1)) then 
                    grp_do_tx_fu_343_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    rx_pkt_pulse_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (rx_pkt_pulse_1_vld_in = ap_const_logic_1) and (rx_pkt_pulse_1_vld_reg = ap_const_logic_0))) then 
                rx_pkt_pulse_1_vld_reg <= ap_const_logic_1;
            elsif (((rx_pkt_pulse_1_vld_in = ap_const_logic_0) and (rx_pkt_pulse_1_vld_reg = ap_const_logic_1))) then 
                rx_pkt_pulse_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;

    tx_done_pulse_1_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (tx_done_pulse_1_vld_in = ap_const_logic_1) and (tx_done_pulse_1_vld_reg = ap_const_logic_0))) then 
                tx_done_pulse_1_vld_reg <= ap_const_logic_1;
            elsif (((tx_done_pulse_1_vld_in = ap_const_logic_0) and (tx_done_pulse_1_vld_reg = ap_const_logic_1))) then 
                tx_done_pulse_1_vld_reg <= ap_const_logic_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_do_rx_fu_312_host_rx_out_TVALID = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then
                host_rx_out_TDATA_reg <= grp_do_rx_fu_312_host_rx_out_TDATA;
                host_rx_out_TKEEP_reg <= grp_do_rx_fu_312_host_rx_out_TKEEP;
                host_rx_out_TLAST_reg <= grp_do_rx_fu_312_host_rx_out_TLAST;
                host_rx_out_TSTRB_reg <= grp_do_rx_fu_312_host_rx_out_TSTRB;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_do_rx_fu_312_last_rx_modcod_ap_vld = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then
                last_rx_modcod_reg <= grp_do_rx_fu_312_last_rx_modcod;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_do_rx_fu_312_last_rx_n_syms_ap_vld = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then
                last_rx_n_syms_reg <= grp_do_rx_fu_312_last_rx_n_syms;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                modcod_read_reg_414 <= modcod;
                my_mac_addr_read_reg_424 <= my_mac_addr;
                p_0_reg_466 <= phy_rx_in_TDATA_int_regslice;
                p_vld9_reg_462 <= phy_rx_in_read_nbread_fu_253_p2_0;
                p_vld_reg_448 <= empty_nbread_fu_241_p5_0;
                phy_csr_read_reg_443 <= phy_csr;
                promisc_read_reg_419 <= promisc;
                rx_modcod_in_read_reg_438 <= rx_modcod_in;
                rx_n_syms_in_read_reg_433 <= rx_n_syms_in;
                tx_first_data_reg_452 <= host_tx_in_TDATA_int_regslice;
                tx_first_last_reg_457 <= host_tx_in_TLAST_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_do_tx_fu_343_phy_tx_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_1))) then
                phy_tx_out_TDATA_reg <= grp_do_tx_fu_343_phy_tx_out_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                rx_drop_count_read_reg_476 <= rx_drop_count_i;
                rx_fcs_err_count_read_reg_481 <= rx_fcs_err_count_i;
                rx_pkt_count_read_reg_471 <= rx_pkt_count_i;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_do_rx_fu_312_rx_pkt_pulse_ap_vld = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then
                rx_pkt_pulse_1_data_in_reg <= grp_do_rx_fu_312_rx_pkt_pulse;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_const_logic_1) and (rx_pkt_pulse_1_vld_in = ap_const_logic_1) and (rx_pkt_pulse_1_vld_reg = ap_const_logic_1)) or (not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (rx_pkt_pulse_1_vld_in = ap_const_logic_1) and (rx_pkt_pulse_1_vld_reg = ap_const_logic_0)))) then
                rx_pkt_pulse_1_data_reg <= rx_pkt_pulse_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_const_logic_1) and (tx_done_pulse_1_vld_in = ap_const_logic_1) and (tx_done_pulse_1_vld_reg = ap_const_logic_1)) or (not(((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) and (tx_done_pulse_1_vld_in = ap_const_logic_1) and (tx_done_pulse_1_vld_reg = ap_const_logic_0)))) then
                tx_done_pulse_1_data_reg <= tx_done_pulse_1_data_in;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tx_pkt_count_read_reg_486 <= tx_pkt_count_i;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, p_vld_fu_376_p1, p_vld9_fu_388_p1, ap_CS_fsm_state4, mac_enable_read_read_fu_180_p2, ap_block_state4_on_subcall_done, ap_CS_fsm_state6, ap_block_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (p_vld9_fu_388_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (p_vld_fu_376_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                elsif (((mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (p_vld9_fu_388_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (p_vld_fu_376_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (p_vld_fu_376_p1 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state6 => 
                if (((ap_const_boolean_0 = ap_block_state6) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln310_fu_369_p2 <= std_logic_vector(unsigned(rx_hdr_err_count_i) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6)
    begin
        if ((ap_const_boolean_1 = ap_block_state6)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(p_vld_reg_448, grp_do_rx_fu_312_ap_done, grp_do_tx_fu_343_ap_done, ap_predicate_op103_call_state4)
    begin
                ap_block_state4_on_subcall_done <= (((grp_do_tx_fu_343_ap_done = ap_const_logic_0) and (p_vld_reg_448 = ap_const_lv1_1)) or ((ap_predicate_op103_call_state4 = ap_const_boolean_1) and (grp_do_rx_fu_312_ap_done = ap_const_logic_0)));
    end process;


    ap_block_state6_assign_proc : process(tx_done_pulse_1_ack_in, rx_pkt_pulse_1_ack_in, regslice_both_host_rx_out_V_data_V_U_apdone_blk, regslice_both_phy_tx_out_U_apdone_blk)
    begin
                ap_block_state6 <= ((regslice_both_phy_tx_out_U_apdone_blk = ap_const_logic_1) or (regslice_both_host_rx_out_V_data_V_U_apdone_blk = ap_const_logic_1) or (rx_pkt_pulse_1_ack_in = ap_const_logic_0) or (tx_done_pulse_1_ack_in = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state6, ap_block_state6)
    begin
        if (((ap_const_boolean_0 = ap_block_state6) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op103_call_state4_assign_proc : process(p_vld_reg_448, p_vld9_reg_462)
    begin
                ap_predicate_op103_call_state4 <= ((p_vld9_reg_462 = ap_const_lv1_1) and (p_vld_reg_448 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, ap_block_state6)
    begin
        if (((ap_const_boolean_0 = ap_block_state6) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    csr_master_0_AWVALID_assign_proc : process(ap_CS_fsm_state5, grp_do_tx_fu_343_m_axi_csr_master_0_AWVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            csr_master_0_AWVALID <= grp_do_tx_fu_343_m_axi_csr_master_0_AWVALID;
        else 
            csr_master_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    csr_master_0_BREADY_assign_proc : process(ap_CS_fsm_state5, grp_do_tx_fu_343_m_axi_csr_master_0_BREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            csr_master_0_BREADY <= grp_do_tx_fu_343_m_axi_csr_master_0_BREADY;
        else 
            csr_master_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    csr_master_0_WVALID_assign_proc : process(ap_CS_fsm_state5, grp_do_tx_fu_343_m_axi_csr_master_0_WVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            csr_master_0_WVALID <= grp_do_tx_fu_343_m_axi_csr_master_0_WVALID;
        else 
            csr_master_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    empty_nbread_fu_241_p5_0 <= (0=>(host_tx_in_TVALID_int_regslice), others=>'-');
    grp_do_rx_fu_312_ap_start <= grp_do_rx_fu_312_ap_start_reg;
    grp_do_rx_fu_312_host_rx_out_TREADY <= (host_rx_out_TREADY_int_regslice and ap_CS_fsm_state4);
    grp_do_tx_fu_343_ap_start <= grp_do_tx_fu_343_ap_start_reg;
    grp_do_tx_fu_343_phy_tx_out_TREADY <= (phy_tx_out_TREADY_int_regslice and ap_CS_fsm_state4);

    host_rx_out_TDATA_int_regslice_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_host_rx_out_TDATA, grp_do_rx_fu_312_host_rx_out_TVALID, ap_CS_fsm_state4, host_rx_out_TDATA_reg)
    begin
        if (((grp_do_rx_fu_312_host_rx_out_TVALID = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            host_rx_out_TDATA_int_regslice <= grp_do_rx_fu_312_host_rx_out_TDATA;
        else 
            host_rx_out_TDATA_int_regslice <= host_rx_out_TDATA_reg;
        end if; 
    end process;


    host_rx_out_TKEEP_int_regslice_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_host_rx_out_TVALID, grp_do_rx_fu_312_host_rx_out_TKEEP, ap_CS_fsm_state4, host_rx_out_TKEEP_reg)
    begin
        if (((grp_do_rx_fu_312_host_rx_out_TVALID = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            host_rx_out_TKEEP_int_regslice <= grp_do_rx_fu_312_host_rx_out_TKEEP;
        else 
            host_rx_out_TKEEP_int_regslice <= host_rx_out_TKEEP_reg;
        end if; 
    end process;


    host_rx_out_TLAST_int_regslice_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_host_rx_out_TVALID, grp_do_rx_fu_312_host_rx_out_TLAST, ap_CS_fsm_state4, host_rx_out_TLAST_reg)
    begin
        if (((grp_do_rx_fu_312_host_rx_out_TVALID = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            host_rx_out_TLAST_int_regslice <= grp_do_rx_fu_312_host_rx_out_TLAST;
        else 
            host_rx_out_TLAST_int_regslice <= host_rx_out_TLAST_reg;
        end if; 
    end process;


    host_rx_out_TSTRB_int_regslice_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_host_rx_out_TVALID, grp_do_rx_fu_312_host_rx_out_TSTRB, ap_CS_fsm_state4, host_rx_out_TSTRB_reg)
    begin
        if (((grp_do_rx_fu_312_host_rx_out_TVALID = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            host_rx_out_TSTRB_int_regslice <= grp_do_rx_fu_312_host_rx_out_TSTRB;
        else 
            host_rx_out_TSTRB_int_regslice <= host_rx_out_TSTRB_reg;
        end if; 
    end process;

    host_rx_out_TVALID <= regslice_both_host_rx_out_V_data_V_U_vld_out;
    host_rx_out_TVALID_int_regslice <= grp_do_rx_fu_312_host_rx_out_TVALID;
    host_tx_in_TREADY <= regslice_both_host_tx_in_V_data_V_U_ack_in;

    host_tx_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state2, p_vld_reg_448, grp_do_tx_fu_343_host_tx_in_TREADY, ap_CS_fsm_state4, mac_enable_read_read_fu_180_p2, host_tx_in_TVALID_int_regslice)
    begin
        if (((host_tx_in_TVALID_int_regslice = ap_const_logic_1) and (mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            host_tx_in_TREADY_int_regslice <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_1))) then 
            host_tx_in_TREADY_int_regslice <= grp_do_tx_fu_343_host_tx_in_TREADY;
        else 
            host_tx_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    last_rx_modcod_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_last_rx_modcod, grp_do_rx_fu_312_last_rx_modcod_ap_vld, ap_CS_fsm_state4, last_rx_modcod_reg)
    begin
        if (((grp_do_rx_fu_312_last_rx_modcod_ap_vld = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            last_rx_modcod <= grp_do_rx_fu_312_last_rx_modcod;
        else 
            last_rx_modcod <= last_rx_modcod_reg;
        end if; 
    end process;


    last_rx_n_syms_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_last_rx_n_syms, grp_do_rx_fu_312_last_rx_n_syms_ap_vld, ap_CS_fsm_state4, last_rx_n_syms_reg)
    begin
        if (((grp_do_rx_fu_312_last_rx_n_syms_ap_vld = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            last_rx_n_syms <= grp_do_rx_fu_312_last_rx_n_syms;
        else 
            last_rx_n_syms <= last_rx_n_syms_reg;
        end if; 
    end process;

    mac_enable_read_read_fu_180_p2 <= mac_enable;
    p_vld9_fu_388_p1 <= phy_rx_in_read_nbread_fu_253_p2_0;
    p_vld_fu_376_p1 <= empty_nbread_fu_241_p5_0;
    phy_rx_in_TREADY <= regslice_both_phy_rx_in_U_ack_in;

    phy_rx_in_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state2, p_vld_fu_376_p1, p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_phy_rx_in_TREADY, ap_CS_fsm_state4, mac_enable_read_read_fu_180_p2, phy_rx_in_TVALID_int_regslice)
    begin
        if (((phy_rx_in_TVALID_int_regslice = ap_const_logic_1) and (mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (p_vld_fu_376_p1 = ap_const_lv1_0))) then 
            phy_rx_in_TREADY_int_regslice <= ap_const_logic_1;
        elsif (((p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            phy_rx_in_TREADY_int_regslice <= grp_do_rx_fu_312_phy_rx_in_TREADY;
        else 
            phy_rx_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    phy_rx_in_read_nbread_fu_253_p2_0 <= (0=>(phy_rx_in_TVALID_int_regslice), others=>'-');

    phy_tx_out_TDATA_int_regslice_assign_proc : process(p_vld_reg_448, grp_do_tx_fu_343_phy_tx_out_TDATA, grp_do_tx_fu_343_phy_tx_out_TVALID, ap_CS_fsm_state4, phy_tx_out_TDATA_reg)
    begin
        if (((grp_do_tx_fu_343_phy_tx_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_1))) then 
            phy_tx_out_TDATA_int_regslice <= grp_do_tx_fu_343_phy_tx_out_TDATA;
        else 
            phy_tx_out_TDATA_int_regslice <= phy_tx_out_TDATA_reg;
        end if; 
    end process;

    phy_tx_out_TVALID <= regslice_both_phy_tx_out_U_vld_out;

    rx_drop_count_o_assign_proc : process(rx_drop_count_i, p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_ap_return_1, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_drop_count_o <= grp_do_rx_fu_312_ap_return_1;
        else 
            rx_drop_count_o <= rx_drop_count_i;
        end if; 
    end process;


    rx_drop_count_o_ap_vld_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_drop_count_o_ap_vld <= ap_const_logic_1;
        else 
            rx_drop_count_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    rx_fcs_err_count_o_assign_proc : process(rx_fcs_err_count_i, p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_ap_return_2, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_fcs_err_count_o <= grp_do_rx_fu_312_ap_return_2;
        else 
            rx_fcs_err_count_o <= rx_fcs_err_count_i;
        end if; 
    end process;


    rx_fcs_err_count_o_ap_vld_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_fcs_err_count_o_ap_vld <= ap_const_logic_1;
        else 
            rx_fcs_err_count_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    rx_hdr_err_count_o_assign_proc : process(rx_hdr_err_count_i, ap_CS_fsm_state2, mac_enable_read_read_fu_180_p2, rx_header_err_read_read_fu_204_p2, add_ln310_fu_369_p2)
    begin
        if (((rx_header_err_read_read_fu_204_p2 = ap_const_lv1_1) and (mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            rx_hdr_err_count_o <= add_ln310_fu_369_p2;
        else 
            rx_hdr_err_count_o <= rx_hdr_err_count_i;
        end if; 
    end process;


    rx_hdr_err_count_o_ap_vld_assign_proc : process(ap_CS_fsm_state2, mac_enable_read_read_fu_180_p2, rx_header_err_read_read_fu_204_p2)
    begin
        if (((rx_header_err_read_read_fu_204_p2 = ap_const_lv1_1) and (mac_enable_read_read_fu_180_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            rx_hdr_err_count_o_ap_vld <= ap_const_logic_1;
        else 
            rx_hdr_err_count_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    rx_header_err_read_read_fu_204_p2 <= rx_header_err;

    rx_pkt_count_o_assign_proc : process(rx_pkt_count_i, p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_ap_return_0, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_pkt_count_o <= grp_do_rx_fu_312_ap_return_0;
        else 
            rx_pkt_count_o <= rx_pkt_count_i;
        end if; 
    end process;


    rx_pkt_count_o_ap_vld_assign_proc : process(p_vld_reg_448, p_vld9_reg_462, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_pkt_count_o_ap_vld <= ap_const_logic_1;
        else 
            rx_pkt_count_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    rx_pkt_pulse <= rx_pkt_pulse_1_data_reg;

    rx_pkt_pulse_1_ack_in_assign_proc : process(rx_pkt_pulse_1_vld_reg)
    begin
        if (((rx_pkt_pulse_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (rx_pkt_pulse_1_vld_reg = ap_const_logic_1)))) then 
            rx_pkt_pulse_1_ack_in <= ap_const_logic_1;
        else 
            rx_pkt_pulse_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    rx_pkt_pulse_1_data_in_assign_proc : process(ap_start, ap_CS_fsm_state1, p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_rx_pkt_pulse, grp_do_rx_fu_312_rx_pkt_pulse_ap_vld, ap_CS_fsm_state4, rx_pkt_pulse_1_data_in_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            rx_pkt_pulse_1_data_in <= ap_const_lv1_0;
        elsif (((grp_do_rx_fu_312_rx_pkt_pulse_ap_vld = ap_const_logic_1) and (p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_pkt_pulse_1_data_in <= grp_do_rx_fu_312_rx_pkt_pulse;
        else 
            rx_pkt_pulse_1_data_in <= rx_pkt_pulse_1_data_in_reg;
        end if; 
    end process;


    rx_pkt_pulse_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, p_vld_reg_448, p_vld9_reg_462, grp_do_rx_fu_312_rx_pkt_pulse_ap_vld, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            rx_pkt_pulse_1_vld_in <= ap_const_logic_1;
        elsif (((p_vld9_reg_462 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_0))) then 
            rx_pkt_pulse_1_vld_in <= grp_do_rx_fu_312_rx_pkt_pulse_ap_vld;
        else 
            rx_pkt_pulse_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    rx_pkt_pulse_ap_vld <= rx_pkt_pulse_1_vld_reg;
    tx_done_pulse <= tx_done_pulse_1_data_reg;

    tx_done_pulse_1_ack_in_assign_proc : process(tx_done_pulse_1_vld_reg)
    begin
        if (((tx_done_pulse_1_vld_reg = ap_const_logic_0) or ((ap_const_logic_1 = ap_const_logic_1) and (tx_done_pulse_1_vld_reg = ap_const_logic_1)))) then 
            tx_done_pulse_1_ack_in <= ap_const_logic_1;
        else 
            tx_done_pulse_1_ack_in <= ap_const_logic_0;
        end if; 
    end process;


    tx_done_pulse_1_data_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            tx_done_pulse_1_data_in <= ap_const_lv1_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            tx_done_pulse_1_data_in <= ap_const_lv1_0;
        else 
            tx_done_pulse_1_data_in <= "X";
        end if; 
    end process;


    tx_done_pulse_1_vld_in_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            tx_done_pulse_1_vld_in <= ap_const_logic_1;
        else 
            tx_done_pulse_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    tx_done_pulse_ap_vld <= tx_done_pulse_1_vld_reg;

    tx_pkt_count_o_assign_proc : process(tx_pkt_count_i, p_vld_reg_448, grp_do_tx_fu_343_ap_return, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_1))) then 
            tx_pkt_count_o <= grp_do_tx_fu_343_ap_return;
        else 
            tx_pkt_count_o <= tx_pkt_count_i;
        end if; 
    end process;


    tx_pkt_count_o_ap_vld_assign_proc : process(p_vld_reg_448, ap_CS_fsm_state4, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4) and (p_vld_reg_448 = ap_const_lv1_1))) then 
            tx_pkt_count_o_ap_vld <= ap_const_logic_1;
        else 
            tx_pkt_count_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

end behav;
